### ISSUE TITLE
Use a custom URL Style (not mapbox)

### ISSUE THREAD

**Issue by Tarasteed** [mapbox/mapboxgl-powerbi#103]
Hi,

Can someone tell me how can i save my features to update MapBox ?
For now, i just try to change the descriptions in capabilities but when i create my package, it don't appear.
I'm beginner with PowerBI and custom visual and i read a lot of documentation but i can't find a way to update this custom visual.

Thanks guys !

**Comment by ryanbaumann** [comment]
@Tarasteed thanks for your ticket.  Can you detail what you're trying to do for your use case?  

Can you describe in more detail what are the inputs and outputs you want to achieve using the Mapbox Visual when you save your features to update Mapbox?  Include a screenshot if possible with a visual indicator of what you want to do.

**Comment by Tarasteed** [comment]
Hi !
I solved my issue by changing the GUID number.
I just want to allow the using of a Map style URL which is not a MapBox URL.

Thanks for your reply !

Have a good day.


Axel Rose


Le sam. 14 avr. 2018 à 18:56, Ryan Baumann <notifications@github.com> a
écrit :

**Comment by Tarasteed** [comment]
Yes, we made a little file that allow that on a SharePoint projet and the
generated URL which work on it don't work on the MapBox custom visual of
PowerBi.
It just load again and again, so i think i have to make some modifications.

(By the way i'm french, so sorry if my english is not very good)


Le sam. 14 avr. 2018 à 19:22, Ryan Baumann <notifications@github.com> a
écrit :

**Comment by ryanbaumann** [comment]
That's awesome @Tarasteed - is that something you could make a PR (pull request) for on this repository?

**Comment by Tarasteed** [comment]
I think yes, if it works !

Thanks again !


Axel Rose

Le sam. 14 avr. 2018 à 21:11, Ryan Baumann <notifications@github.com> a
écrit :

**Comment by ryanbaumann** [comment]
Note that you will probably need to change [this line](https://github.com/mapbox/mapboxgl-powerbi/blob/master/src/ts/mapboxMap.ts#L370) to source data from non `api.mapbox.com` sources.  I'd recommend using this approach in the `transformRequest` to check if the URL is from api.mapbox.com: 
 https://github.com/mapbox/mapboxgl-jupyter/blob/master/mapboxgl/templates/base.html#L13

**Comment by Tarasteed** [comment]
I will check that but i'm not sure that is the right line.
In my case it's only for the Map Style like
mapbox://styles/mapbox/streets-v10
<https://api.mapbox.com/styles/v1/mapbox/streets-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#2/0.0/0.0>
I want to use my own map style stored on my own server.



Cordialement,


Axel Rose

2018-04-15 3:41 GMT+02:00 Ryan Baumann <notifications@github.com>:

**Comment by Tarasteed** [comment]
i don't know which files to change to allow a style with an Url like that:
https://my-host-example/v1/venuesrevisions/43?api_key={MyApiKey}
I'm a little bit lost.

**Comment by Tarasteed** [comment]
@szilardhuber It gave me few errors like : 
![error](https://user-images.githubusercontent.com/23456529/38920938-c82e94bc-42f4-11e8-9954-2126bdcae479.PNG)
When i'm trying to use a style url like : 
https://api.example.io/v1/venuesrevisions//43?api_key=********-****-****-****-************
It display JSON content.

**Comment by szilardhuber** [comment]
It seems to be telling us that the returned JSON object is not a valid mapbox style (missing propeties in the JSON: version, sources, layers).

Can you check that the returned JSON object follows this specification? https://www.mapbox.com/mapbox-gl-js/style-spec

**Comment by Tarasteed** [comment]
It was a mistake, now i have that : 
![error](https://user-images.githubusercontent.com/23456529/38922190-e64e6ec4-42f7-11e8-89e3-145334feae36.PNG)
The only difference is that i have that : 
`"sources": {
        "composite": {
         "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6",
            "type": "vector"`
I have to mapbox url.

**Comment by szilardhuber** [comment]
The error: `No 'Access-Control-Allow-Origin` header is present on the requested resource.` means that the web server serving your JSON refuses the request sent from a website that was served from an other domain (app.powerbi.com). I think you should have the webserver serve that JSON object for cross-origin requests and try that way,.

**Comment by Tarasteed** [comment]
Thanks for helping me @szilardhuber !
I will check that and keep you updated.

**Comment by Tarasteed** [comment]
Hi !
After a quick update on my json file and some fix with the domains, i found something.
My custom url call a lot of url to fill the layers ect and it works only if i change the
`<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />`
to
`<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.26.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.26.0/mapbox-gl.css' rel='stylesheet' />`

It works only with my test on Jsfiddle, i made the modifications on vector.ejs but  i think i'v missed something somewhere.
To conclude, my custom style works fine on Jsfiddle but not perfectly on Web PowerBi and Desktop.

**Comment by szilardhuber** [comment]
Thanks for the update @Tarasteed !

The PowerBI plugin works with `v0.44` Mapbox GL API so I think there might still be some issue in your custom style. I suggest you try to fix your JsFiddle to work with the same version as the PowerBI plugin. 

Also if you could share the new error messages with us with the custom style (and the domain issues fixed) either from the JSFiddle or from the PowerBI plugin that would be helpful.

**Comment by Tarasteed** [comment]
The problem is that my custom style is a mix of two differents style : 
- One for the outdoor of a building
- One for the indoor of a building

So we just change some domain url that were called, and it works perfectly on Jsfiddle, my two style are just mixed (because in the future, i want to add a dropdown to select indoor or outdoor).
I will try to fix that using v0.26.0 and see i it's possible because i don't know how to make it works with the v0.44.2.

**Comment by ryanbaumann** [comment]
@Tarasteed is your GL Style Sheet up to date? https://www.mapbox.com/mapbox-gl-js/style-spec/

**Comment by Tarasteed** [comment]
@ryanbaumann I think yes because it works on Jsfiddle with mapbox-gl.js v0.26.0.

**Comment by ryanbaumann** [comment]
The style spec has changed quite a lot since GL JS v0.26 -- if it doesn't work with the latest GL JS v0.44.2, then your style sheet is likely not valid according to the latest spec.

**Comment by Tarasteed** [comment]
So i will have to read all the specs and verify all the lines of my style sheet ?
(I will keep trying to see if i can do something to force the version to 0.26.0 at the same time)

**Comment by ryanbaumann** [comment]
@tarasteed here is the style validation tool you can run against your style JSON to check:  https://github.com/mapbox/mapbox-gl-js/tree/03680eb57489cf442f8c538141ea27c73d98d532/src/style-spec

`npm install @mapbox/mapbox-gl-style-spec --global`
`gl-style-validate style.json`

**Comment by Tarasteed** [comment]
@ryanbaumann Thanks, i was just looking that !
But i don't have any output also with the --json flag.
What i've missed ?

**Comment by ryanbaumann** [comment]
Is it possible to copy your Mapbox GL Stylesheet here so we can troubleshoot @tarasteed?

**Comment by Tarasteed** [comment]
@ryanbaumann This is the style url i use : [https://toolsgeolys.azurewebsites.net/styles/tevolys.json](url)

**Comment by szilardhuber** [comment]
@Tarasteed Is it the style definition that is not working for your jsfiddle with a newer Mapbox API version? I quickly put together a simple map on my machine with this style and it works just fine with v0.44.1

**Comment by Tarasteed** [comment]
@ryanbaumann Mapbox-gl.js v0.26.0
![image](https://user-images.githubusercontent.com/23456529/39036286-4ca2ff9c-447d-11e8-9043-972e4ba454df.png)

Mapbox-gl.js v0.44.2
![image](https://user-images.githubusercontent.com/23456529/39036748-c44dffaa-447e-11e8-8093-651d7c201ff2.png)

**Comment by ryanbaumann** [comment]
@Tarasteed There are two changes to make here:

1. Remove all references to `source-layer` for layers using the geojson source `venue`.
    * Updated style sheet.  [style.json.zip](https://github.com/mapbox/mapboxgl-powerbi/files/1932420/style.json.zip)
2. A bug fix in Mapbox Visual for Power BI to support custom style sheets from non-Mapbox domains.
    * See https://github.com/mapbox/mapboxgl-powerbi/pull/109 to try this custom pbiviz build to test your use case.

**Comment by ryanbaumann** [comment]
Did this work for you @Tarasteed?  Will close if so

**Comment by ryanbaumann** [comment]
Excellent @Tarasteed.  Support for non-Mapbox hosted sources and style sheets will ship in the next version,
