### ISSUE TITLE
Color Heatmap by aggregated measure value

### ISSUE THREAD

**Issue by Mi2nBalamurugan** [mapbox/mapboxgl-powerbi#104]
Hi, I am trying to use the Heatmap feature of the Mapbox visual in Power BI. If I add a measure to the 'Color' field of the visual and select Heatmap from the visual's Format pane, it plots the heatmap based on the density of the points in the map and not on the value of the measure. Please let me know if that is how the map is supposed to behave, or am I doing something wrong.

**Comment by szilardhuber** [comment]
Hi @Mi2nBalamurugan , heatmap color is based on density, the color field is only used by Circle visualization.

You can customize the color of the heatmap by setting min-med-max colors but they will still be based on the density.

**Comment by ryanbaumann** [comment]
@Mi2nBalamurugan this is a great feature request.  We could support.heatmap color by metric value building on top of the cluster property aggregation code.

 I recommend using the cluster layer for now to show the relationship of a metric value among points.

**Comment by Tarasteed** [comment]
Hi @Mi2nBalamurugan,
I was trying to do the same things on my project with some points and some values.

I found you can "simply" disable the isGradient of the points to allow color gradient in MapBoxMap.ts !

![image](https://user-images.githubusercontent.com/23456529/39622190-883b740c-4f91-11e8-9644-c8643ee123eb.png)
![image](https://user-images.githubusercontent.com/23456529/39622264-ca44d65e-4f91-11e8-82b2-d9f3358b4ec8.png)
