### ISSUE TITLE
Choropleth issue: There is no source with this ID

### ISSUE THREAD

**Issue by baspeti** [mapbox/mapboxgl-powerbi#117]
When setting choropleth data to custom, and typing various values into the text fields (I managed to trigger the issue by editing `vectorProperty`), you can end up with no choropleth visualisation and an error message like: `There is no source with this ID`

![choropleth missing source id](https://user-images.githubusercontent.com/5700926/39294399-f3a50a2a-493b-11e8-8824-d9cd463577a1.gif)

**Comment by petispaespea** [comment]
Fixed by #120
