### ISSUE TITLE
Filter behavior in 1.1 3

### ISSUE THREAD

**Issue by cmtoomey** [mapbox/mapboxgl-powerbi#134]
With choropleth map + crosstab, clicking on item in crosstab causes the map to zoom to z0. Similar to #133.

Base on this [PR](https://github.com/mapbox/mapboxgl-powerbi/pull/132)

Filter should keep existing extent OR zoom-to-extent of filtered item.

![pbitest1](https://user-images.githubusercontent.com/12201602/39936094-3b60a9a8-5500-11e8-84c0-ff53f77d77f0.gif)

**Comment by ryanbaumann** [comment]
I'd rate this as a nice-to-have for the initial release.  A user can always turn autozoom off using the UI toggle.

**Comment by cmtoomey** [comment]
@ryanbaumann I think that workaround is totally acceptable, and would think your assumption tile upload is valid here. 

However, that does not resolve the issue of Mapbox-provided tiles. This UX appears to be linked to the fact that the bbox of those tiles is, appropriately, `the world.` While some, and perhaps most users, will have their own tilesets to visualize, a majority of users will likely take advantage of Mapbox's OOB tilesets, meaning that the workaround won't actually resolve the majority of cases.

Zoom-out based on an interaction of a subset of data is, for the majority of cases, backwards - it should either be static or zoom-in-to-extent of selection(s). I think default of `disable auto-zoom` is appropriate here.

**Comment by ryanbaumann** [comment]
Set the default behavior in #132 to allow the user to set the map auto-zoom state in the map settings.  Closing this issue, while leaving open #133 for further consideration when filtering a Choropleth layer beyond it's bounds.
