### ISSUE TITLE
Documentation for out-of-box tilesets

### ISSUE THREAD

**Issue by cmtoomey** [mapbox/mapboxgl-powerbi#136]
Base on this [PR](https://github.com/mapbox/mapboxgl-powerbi/pull/132)

Out-of-box support is provided for Countries, States, and US Postcodes. For custom tilesets, we instruct users to make sure they have fields that match for the data join. However, we do not provide the users with available columns, types, or any documentation at all relating to what fields can be matched for OOB tilesets.

We should provide user the following:
1. List of columns
2. Column types
3. Downloadable CSVs for lookup tables so they can update datasets accordingly.

**Comment by ryanbaumann** [comment]
Here is the list of supported `Location` names are supported in the Mapbox Visual for Power BI 1.2.3 release for Global Countries, US States, and US Postcodes choropleth layers.

https://docs.google.com/spreadsheets/d/1k5HvzWdeuELwnL-Ta1Jt7wghOOrRpmQU438_LfohBEI/edit?usp=sharing

- [ ] @samgehret translate this data into public-facing documentation on mapbox.com

**Comment by samgehret** [comment]
This is live now:
https://www.mapbox.com/help/integrate-mapbox-visual-with-power-bi/
