### ISSUE TITLE
Choropleth layer initialization & toggle on/off bug

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#139]
# Problem 

Toggling a new Choropleth Layer on/off causes two specific race-condition bugs:

1. The layer `flickers` on/off when changing integer zoom levels
2. The new Choropleth layer does not `autozoom` to the tileset bounds

# Solution

* Look for conditions where https://github.com/mapbox/mapboxgl-powerbi/blob/master/src/ts/layers/choropleth.ts#L54 could return null when it should just be waiting for the source tileset (`choropleth-source`) to load.  This is likely the cause of the layer not autozooming issue.
* Why do we need this line?  https://github.com/mapbox/mapboxgl-powerbi/blob/master/src/ts/layers/choropleth.ts#L73 . Try removing it, it could be related to the layer `flicker` issue

cc/ @szilardhuber @petispaespea @baspeti @cmtoomey

**Comment by ryanbaumann** [comment]
Closing this issue should fix the bugs in the issues below:

* https://github.com/mapbox/mapboxgl-powerbi/issues/135

**Comment by szilardhuber** [comment]
@ryanbaumann with GL Js API updated to 0.45 I can't reproduce #135 so the flickering does not exist any more IMHO. Can you please confirm that or give some more insights on it?

And I think autozoom error was also because of that issue so I think that is fixed as well.

**Comment by ryanbaumann** [comment]
Fixed in PR #132
