### ISSUE TITLE
Add `Label` data format option

### ISSUE THREAD

**Issue by Tarasteed** [mapbox/mapboxgl-powerbi#141]
Hi ! 
Can someone tell me how can i do to add labl to my circle point ?
I have a field "Name" and i want to display it on my circle.

**Comment by ryanbaumann** [comment]
@tarasteed we don't have a `symbol` label for a `circle` layer type yet.  Let's add this as a feature request!

**Comment by Tarasteed** [comment]
@ryanbaumann Oh ok thanks, Is there a way to do otherwise ?

**Comment by ryanbaumann** [comment]
This would require a PR to add labels to circles only in Power BI.  You could add labels to Mapbox Studio based on the same data set you use for the circle layer in Power BI today as a workaround.

**Comment by Tarasteed** [comment]
I can't do that in my case but thanks !

Le jeu. 17 mai 2018 à 16:54, Ryan Baumann <notifications@github.com> a
écrit :

**Comment by Tarasteed** [comment]
I added that : 
`const circleLabelLayer = mapboxUtils.decorateLayer({
                    id: 'circle-label',
                    type: 'symbol',
                    source: 'data',
                    layout: {
                        'text-field': `{sizeValue}`,
                        'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
                        'text-size': 15
                    },
                    paint: {
                        "text-halo-color": "white",
                        "text-halo-width": 1
                    }
                });
                this.map.addLayer(circleLabelLayer);`
And it works perfectly with the field "Size" of circle.

**Comment by ryanbaumann** [comment]
@tarasTeed awesome!  Could you make a PR with these changes to master so we can review the code together?  Thank you.
