### ISSUE TITLE
Update to latest build of GL JS to address click-handler bug on IE & Edge

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#160]
Update to the latest master branch of GL JS to address click handler bugs in v0.45

https://github.com/mapbox/mapbox-gl-js/pull/6757

There should be a beta release on NPM soon cc/ @samgehret

**Comment by ryanbaumann** [comment]
Changed to test the latest master build here.  https://github.com/mapbox/mapboxgl-powerbi/pull/163/commits/929afe6ef8a6e97bc3336c8d7ee893f228e261c7.  Be sure to update this before release to the production release of GL JS.

**Comment by ryanbaumann** [comment]
There is a beta version of GL JS 0.46 going out today - for the next build, we'll want to:

- [ ] Update `package.json` to use GL JS `beta-0.46.0`
- [ ] Update `pbiviz.json` to point to the `node_modules/mapbox-gl-js/dist/mapbox-gl.js` version of GL JS https://github.com/mapbox/mapboxgl-powerbi/blob/master/pbiviz.json#L21
- [ ] Remove the local-built copy of GL JS in https://github.com/mapbox/mapboxgl-powerbi/tree/master/src/js

**Comment by samgehret** [comment]
@ryanbaumann Believe we can close this one.
