### ISSUE TITLE
Do not show any values in tooltip, unless added to tooltip column

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#161]
In the latest drilldown branch, the `lon/lat`, `color`, and `size` values show up in the tooltip by default.  We should not add these to the tooltip unless the user puts them in the `tooltip` column.  

cc/ @samgehret @szilardhuber @baspeti 

![](https://cl.ly/3D1P1g37472M/download/Image%202018-06-09%20at%2010.01.55%20AM.png)

**Comment by Ragha2207** [comment]
One more request is that the tooltip shouldnt also display the values of the column selected as the "color". In the above case, for example density.
