### ISSUE TITLE
Modify Lasso and Polygon icons to indicate selection.

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#168]
Can you darken the lasso or polygon selector when it is selected to indicate that it is enabled? Right now its hard to determine which one is selected. For example, when I click the lasso icon to enable lasso select, the icon doesn't change, so I'm not sure it's enabled.

When I hover over the icon, it becomes slightly darkened, but does not stay darkened when selected. I think we can even make this a bit darker than it is currently.

**Comment by ryanbaumann** [comment]
cc/ @baspeti @szilardhuber
