### ISSUE TITLE
Allow User to Deselect Lasso or Polygon Selector from Chloropleth maps

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#171]
Currently when a user selects Lasso or Polygon selector on the maps, there is no way to deselect it without using the selector first, and the clicking outside the boundary.

Once lasso or polygon is selected, they should be able to click which ever one is selected to unselect it.

For example, if I select lasso, the icon darkens to indicate its selected. If I click lasso again, the icon should go back to original state and it should not be selected anymore... same for polygon draw.

**Comment by baspeti** [comment]
Well, I know it is quite hidden, but hitting the `Esc` key cancels both polygon and lasso drawing. I just wanted to note that. And yes, I agree, clicking on the icon again would also be a good way to deselect.
