### ISSUE TITLE
Allow CTRL+Click to add/remove a polygon from the selection

### ISSUE THREAD

**Issue by indiciagerry** [mapbox/mapboxgl-powerbi#173]
Requirements:

[Sample Code](https://gist.github.com/samgehret/5a880ef0114cdd23ca04b3c9d63add88)

The lasso and polygon seletion is really cool!

But if you dont select precisely what you want, you have to retry again and again...
You also may need to deselect a zone in the middle of the selection and you cannot do it as it is now.

So it will be nice if you allow CTRL+Click to add/remove a polygon from the selection.

BTW, thanks for the good work!

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by samgehret** [comment]
@indiciagerry available in beta https://github.com/mapbox/mapboxgl-powerbi/blob/v1.3_beta/dist/mapboxGLMap.pbiviz

**Comment by samgehret** [comment]
Closed as live.
