### ISSUE TITLE
Bug with IE 11 Support

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#175]
The visualization shows the map now but it throws JS exception as Map Box uses findIndex method that is not supported by IE11.

 We’d recommend to rewrite this method using some method instead.

Please also consider adding types to every variable and function/method argument in order to avoid such issues.

@szilardhuber @baspeti

**Comment by samgehret** [comment]
@szilardhuber @baspeti I took a first stab today and made some updates which seem to be working. The original branch was called ie11 and it is merged to master.

**Comment by ryanbaumann** [comment]
Can we close this issue after https://github.com/mapbox/mapboxgl-powerbi/pull/176?

**Comment by samgehret** [comment]
Closed
