### ISSUE TITLE
The circle/pin does not show when filtering to only one location and size is used.

### ISSUE THREAD

**Issue by indiciagerry** [mapbox/mapboxgl-powerbi#180]
The problem only appen when filtering to only one location and a value in the size bucket.
The auto-zoom focus on the area but the pin does not appear.

**Comment by ryanbaumann** [comment]
Thanks for the bug report @indiciagerry - can you include a sample screenshot/video of your issue, alongside a sample pbix workbook file so we can re-create?  Thank you!

**Comment by indiciagerry** [comment]
Here is a sample.

The sample contain 2 tabs, one with the mapbox from the store and another with a newer version.

There is 5 points in the map in the sample. When you select only one of them, the dot disappear.

If you remove the value in the "size" bucket its OK, the dot stay visible in the new version.

In the version from the store, the dot always disappear but it look like its from the "too much zooming-in" problem that you have corrected in the new version. 

[sample.zip](https://github.com/mapbox/mapboxgl-powerbi/files/2141454/sample.zip)

**Comment by indiciagerry** [comment]
No update on this issue?

**Comment by ryanbaumann** [comment]
Cc/ @samgehret

**Comment by samgehret** [comment]
@indiciagerry I will try to reproduce. Thanks for reporting it.

**Comment by flogan2000** [comment]
@samgehret Is there any news on this? I have a table with 3 Data Types Job, Engineer and Office, there's 250k jobs which works fine on size for Job on own, or with Engineer. 

If Office (Single point) as well Job and Engineer (50 points) still work but Office doesn't show.

If just Office and/or Engineer (and vice versa) they disappear. If I remove the Job Value in Size they all show.

**Comment by ryanbaumann** [comment]
Consolidating this issue with https://github.com/mapbox/mapboxgl-powerbi/issues/259
