### ISSUE TITLE
Choropleth using Data Colors - forgets color settings after filtering

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#183]
[mapbox issue 183 repo.zip](https://github.com/mapbox/mapboxgl-powerbi/files/2136885/mapbox.issue.183.repo.zip)
I've noticed an issue when using the Choropleth feature and setting Data Colors (based on a text/string field). When an external filter (e.g. a Slicer tile) changes the list of Data Colors, the visual sometimes "forgets" the settings. 

The repo steps are a bit complicated - see attached. The scenario is 3 Status values for a set of Locations: Poor/Fair/Good, which should translate into Red/Yellow/Green. 

Note when opened, the Indicator Slicer is set to C, which should show only Poor/Fair as Red/Yellow - instead it defaults to the 1st colors in the palette.  Changing the Indicator Slicer to A, then B, then C, the colors show correctly.  With the Slicer set to C, close, save and re-open - the preset colors disappear again, but come back when you cycle through the Indicator Slicer.

Once set for a text value, the colors need to stay locked, no matter the impact of external filters.

**Comment by ryanbaumann** [comment]
Thanks for the detailed bug report, @Mike-Honey!  

cc/ @samgehret

**Comment by oflageul** [comment]
Hello,
I report the same issue but in my case I don't use the Choropleth option.

But it's the same, I had defined 3 colors on the map in Data Colors. If I save, close and re-open the pbix, the colors set differs. Generally, two data get the same color when I re-open the file.

I hope you can fix this. 

Thank you!

**Comment by JayDoc386** [comment]
Using the patch it fixed my issues of the colors shifting when using outside filters.  I am using the dot view not Choropleth option.  One thing I notice is that when setting the data colors, Unless I enter them view the Custom Color option it never sets the color that I select from the default listing of colors.  Example if I select blue it will set the color to Red.  If I set the color to Blue it will set the color to a light red.  The only colors that held were white or black.

**Comment by JayDoc386** [comment]
On 1.4 I notice that in the Windows Power BI Mobile App it says "this machine doesnt support WebGL." It did not do that on 1.3 via the Mobile App.  It does work fine on Android and iOS via the Power BI App.  It also shows fine via the web version.

**Comment by tonmcg** [comment]
Here's a more concrete example of the issue:
The choropleth below shows the California county-level vote difference between Clinton and Trump -- the redder a county, the more votes went for Trump. And vice versa.

<img width="1564" alt="screen shot 2018-11-02 at 4 39 38 pm" src="https://user-images.githubusercontent.com/12642427/47939523-04c56d00-debe-11e8-89be-d87617247184.png">

When I select a county with an external slicer, I expect the color to remain the same. For example, when I filter on San Francisco County, which had more votes cast for Clinton, the polygon should remain blue. It does not.

<img width="1571" alt="screen shot 2018-11-02 at 4 39 50 pm" src="https://user-images.githubusercontent.com/12642427/47939542-17d83d00-debe-11e8-8d3b-6a9169167825.png">

PBIX file that replicates the issue:
https://github.com/tonmcg/spatial-analysis/blob/master/app/Power%20BI%20World%20Tour%20-%20Seattle.pbix

**Comment by samgehret** [comment]
Acceptance Criteria:
- [ ] In capabilities.json make the Data Colors option GroupingOrMeasure
- [ ] When the first example in this issue, the color should not change as the user reported. Once the colors are set, they should never change without manually changing them.

**Comment by samgehret** [comment]
@Mike-Honey we will be tackling this bug in the next few weeks. hoping you could help us validate our work.

**Comment by mattdlewis** [comment]
I'd happily take a look at this too.

**Comment by Mike-Honey** [comment]
@samgehret  - yes please!

**Comment by samgehret** [comment]
This feature is live in the marketplace

**Comment by Mike-Honey** [comment]
@samgehret  - a bit disappointed something seems broken in the marketplace version. When I use a text field for the Color, the collection of values appears in the Properties / Data Colors, but every area on my map appears black.

**Comment by samgehret** [comment]
@Mike-Honey i think we discussed this bug and you were able to work around it with a filter. We will fix this on the next release.
