### ISSUE TITLE
Add ability to make a 3d heatmap

### ISSUE THREAD

**Issue by kbauhaus** [mapbox/mapboxgl-powerbi#185]
This feature was requested through communications with the Mapbox support team. Would require data driven heights.

cc @samgehret

**Comment by AlaskanPreston** [comment]
Thanks Kayla!!!  Let me know if there's any way I can help answer questions.

**Comment by ryanbaumann** [comment]
Duplicate of https://github.com/mapbox/mapboxgl-powerbi/issues/188 -> closing this to track in the other issue.
