### ISSUE TITLE
Cross filtering doesn't work when clicking on a data point on Mapbox visual

### ISSUE THREAD

**Issue by Ratchawit** [mapbox/mapboxgl-powerbi#186]
Normally when user clicks on a visual element of Power BI, other visuals on the same page will be cross filtered. This is not the case for Mapbox visual where clicking results in zooming in. 
If it is by design, please consider adding an option to allow cross filtering. It would be consistent user experience with other existing PBI visuals and allow user to see extra information in other visuals that cannot fit into the map's tooltip.

**Comment by samgehret** [comment]
@Ratchawit Cross filtering should also work in the latest beta. Can you give it a try?

**Comment by Ratchawit** [comment]
@samgehret Fixed in beta. Thank you.
