### ISSUE TITLE
Ability to make 3d Choropleth Extrusions Out of the Box

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#188]
Add functionality where users can make 3d Chroropleth Extrusions as a standard feature.

[Sample Code](https://github.com/mapbox/mapboxgl-powerbi/tree/Choropleth-3dExtrusion)

Needed features:
- Create a new height field within the Fields Panel
- Within the Choropleth Format Panel, there needs to be settings for base, and a height multiplier. In case there are different levels, users should be able to adjust how far the extrusions are able to "pop out"
- If the "Height" field is filled in, while choropleths are enabled, the extrusion should be automatically applied to the map.
- Should support drilling between choropleth layers, as well as custom polygons and shapes.

**Comment by PedroRiveraTorresMoir** [comment]
Hi @samanpwbb , is there a timeline for this feature? The visual is already great but knowing this would be nice to factor it into our internal roadmaps. This feature is very important for our Architecture, Engineering and Construction flows, as it allows field workers to modify and publish datasets in studio to tilesets, and immediately have our PowerBI visuals update the rendering. Thanks for any info on this.

**Comment by samgehret** [comment]
@PedroRiveraTorresMoir scoped into our next [release](https://github.com/mapbox/mapboxgl-powerbi/projects/3).

**Comment by szilardhuber** [comment]
@samgehret metric for `fill-extrusion-height` is meters in Mapbox GL JS API but for our sample dataset with US States and population we have to set it to 200000 meters to make the differences visible. Do you think we should add a 1000 multiplier to the height field (so user have to set 200 for 200.000 meters) or should we add this multiplier to the settings with a default value of 1000?

**Comment by PedroRiveraTorresMoir** [comment]
/@samgehret how challenging would it be to create an alternative mode to choropleth height? The current version allows height to be defined by a client-side field. Another, very useful option would be to extract the height and base height properties of the vector source. This would allow us to, for example, be able to see a 3d building with different colors by floor based on occupancy for example.

**Comment by samgehret** [comment]
Closed this is live. @PedroRiveraTorresMoir tracking your new request here

https://github.com/mapbox/mapboxgl-powerbi/issues/250

**Comment by otravers** [comment]
I must be extremely dense, but while I see Extrusion Height and Pitch in the Format panel, I do not see Height in the Fields panel:

![image](https://user-images.githubusercontent.com/3731532/59278389-e41d7c80-8c2f-11e9-9785-0295aa03a89f.png)

This is with PBI Desktop June 2019 and Mapbox 1.4. I even tried from a brand new PBIX file to make sure I had the latest version from the custom visual marketplace.

**Comment by ryanbaumann** [comment]
The `Size` data field with the Choropleth layer type is what you're looking for, I believe

**Comment by ryanbaumann** [comment]
Good catch, thanks @ortavers.  Let's open a separate ticket to track that bug.
