### ISSUE TITLE
Add Geocoder to visual

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#19]
- Viz should use a search box.  https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
- Viz settings should have a toggle to turn the search box on/off
- Viz search box should be on by default.
- Geocoder should have an option to drop a pin at the searched location. User should be able to turn dropping the pin off, and just zoom to the typed in location.
- Geocoder should have a dedicated zoom level option to know what zoom level to change the map to when the search criteria is dropped in.

**Comment by vitaly-livshits** [comment]
@ryanbaumann , would the geocoder also be available to preprocess the data before it gets plotted by the visualization? Or would it only be available as a search control? 

I believe the current version of the Power BI visualization requires lat/long coordinates to be supplied for each data element. We would like to pass in other location types and have them be geocoded by the visualization before plotting.

**Comment by ryanbaumann** [comment]
@vitaly-livshits this existing feature request is just to add a search bar to the visualization.  Could you open up a new issue to track geocoding data from Power BI to show in the map?

**Comment by vitaly-livshits** [comment]
Sure. Just opened https://github.com/mapbox/mapboxgl-powerbi/issues/73

**Comment by samgehret** [comment]
@baspeti added a requirements section into the initial comment.

**Comment by samgehret** [comment]
Closed as live.
