### ISSUE TITLE
Loading spinner does not disappears

### ISSUE THREAD

**Issue by shreyanshmohnot** [mapbox/mapboxgl-powerbi#193]
In my power bi visual, I have created a custom map on mapbox.com styles and I am rendering it in here. After the map is fully loaded and all data points appear over the map, the spinner does not disappear. It still keeps on loading. How can I remove spinner from the background?

![capture](https://user-images.githubusercontent.com/9215778/42469545-09e567b0-8386-11e8-920c-9c7045aea826.PNG)

**Comment by samgehret** [comment]
@shreyanshmohnot This should be fixed in our latest version. Just went live on the marketplace today.
