### ISSUE TITLE
Docs: Make a choropleth map - missing Data Colors feature

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#197]
In recent betas there is a new feature when a text/string field is used in the Color well. A Data Colors section appears in the Visualizations / Format pane, where you can set specific colors for each text value.

This is not described in the doco:
https://www.mapbox.com/help/power-bi-choropleth-map/

**Comment by ryanbaumann** [comment]
Thanks, @Mike-Honey we need to add this to the docs!  cc/ @samgehret

**Comment by ErinQuinn** [comment]
@Mike-Honey just want to say thanks for the new concept of `doco` :)

**Comment by samgehret** [comment]
This is live https://www.mapbox.com/help/integrate-mapbox-visual-with-power-bi/#style-dimensional-values-with-the-data-colors-feature
