### ISSUE TITLE
Add selection setting to allow plotting data `above` or `below` labels on map

### ISSUE THREAD

**Issue by stephshadwell** [mapbox/mapboxgl-powerbi#199]
I have updated to the new version of map box with power bi, to take advantage of some of the new features. However, i have noted that it seems to have changed some maps produced using the old version, so that the data points now seem to sit behind the map layer as opposed to on top. Is this to do with the upgrade, as i have not seen this previously? Or is it to associated with map style design that needs to be amended to account for the new version?

New Version
![image](https://user-images.githubusercontent.com/41364065/42885911-2e79f616-8a9a-11e8-9faf-c259c8302380.png)

Previous Version
![image](https://user-images.githubusercontent.com/41364065/42886048-837ae6d4-8a9a-11e8-841f-f94ad2de74a4.png)

Thanks

**Comment by ryanbaumann** [comment]
@stephshadwell the default behavior of the visual is to place visualization layers behind the lowest `symbol` layer in the map.  That means that data plotted in Power BI onto the map style will appear below text labels and icons.  This is what we've seen from BI developers that most visualizations need. 

In version 1.1.3 on the Office Store, we did not apply the `lowest symbol layer` logic for custom styles.  Now we do in v 1.2 just launched on the office store 🎉 .  

I can see two action items from your ticket here:

1. Do you need to have an option to place the data marks on top of the map?  If yes, please make this ticket a feature request to add a setting allowing the BI developer to plot a layer `on top` or `below` labels.  This could just be a binary `yes/no` checkbox for `below labels`.  The default would be `yes`.
2. In your custom map style, it looks like you've added custom polygons as a reference.  It looks great!  
    * Since your circle layer will be plotted below the lowest symbol layer in your style, to ensure that your circles will be plotted on top of your reference polygons, in Studio you'll want to change the layer order of your polygon reference layer to be below the lowest symbol layer.  In the light, dark, streets, and terrain Mapbox styles, this is the `waterway-label` layer.  
    * Here's an example of how to change your layer order in Studio:

![](https://cl.ly/1V241X072d2Q/download/Screen%20recording%202018-07-21%20at%2011.43.22%20AM.gif)

**Comment by stephshadwell** [comment]
Thanks for this tip, it has worked perfectly. It would be great if it could become a feature that you can just switch easily in Power BI, as i can see it being used both ways depending on what you are displaying.

Thanks for all your help

**Comment by ryanbaumann** [comment]
Thanks @stephshadwell!  @samgehret updated this to a feature request.

**Comment by samgehret** [comment]
Acceptance Criteria:
- [ ] add a new dropdown option to "viz settings" called "Label Position." There should be 2 options for "Above data" and "Below data".

**Comment by samgehret** [comment]
This feature is live in the marketplace
