### ISSUE TITLE
Choropleth features from  beta not present in current release

### ISSUE THREAD

**Issue by MikeAinOz** [mapbox/mapboxgl-powerbi#200]
I have a very nice choropleth working from the beta power bi visual that I downloaded on 13th June     "version": "1.1.3" . The one I’ve recently downloaded from the marketplace (version 1.2.3) does not have these features yet, it still looks like the old version but the version number has gone up I think.
![choropleth1](https://user-images.githubusercontent.com/363841/42923089-0b62d300-8b67-11e8-884b-f6f109d3919f.jpg)

![choropleth2](https://user-images.githubusercontent.com/363841/42923093-0e8ddb9c-8b67-11e8-8fe7-0197bb11ab54.jpg)

You can tell the one that I’m after from the three colour selectors, then slide on the choropleth layer on the format tab and the location on the fields tab.

My beta is working really well, so I’d like to deploy it to the service when the updated visual is available.

When is this likely to be available? I love your work and I want to be able to show it to everyone!

**Comment by ryanbaumann** [comment]
The updated visual is available on the marketplace today @MikeAinOz !  Check it out at https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381472?tab=Overview
