### ISSUE TITLE
Docs - Mapbox Visual compatibility with Report Server, Embedded, Publish to Web, etc.

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#201]
Create documentation on www.mapbox.com/help and in the Readme.md doc in this repo about compatibility with various Power BI tools.

| Mapbox Visual  Version | PBI Report Server | PBI Mobile (iOS/Android) | PBI Embedded | PBI Publish to Web | PBI Desktop | Chrome | Firefox | Safari | Edge | IE11 |
|------------------------|-------------------|-------------------|--------------|--------------------|-------------|--------|---------|--------|------|------|
| v 1.2.3                | TBD - soon             | Yes  | Yes          | Yes                | Yes         | Yes    | Yes     | Yes    | Yes  | Yes  |

Power BI Report Server does support the Mapbox Visual.  We're confirming when the newest Report Server update will launch so that the latest v1.2.3 version of the Mapbox Visual on the Office Store will work using the latest v1.12.0 version of the Power BI Visuals API.  cc/ @alulsh 

If you need support for the v1.2.3 Mapbox Visual for Power BI today, we can cut a custom version for you using an older Power BI Visual tools version.  Drop a note on this issue if you need it, and we will reach out.

### Firewall rules - Domain names and ports to use with Power BI in a secure environment

The Mapbox Visual by default operates using API resources hosted on `api.mapbox.com` securely requested using HTTPS and your Mapbox access token.  If you need all requests to be made inside of your corporate or air-gapped network, you can host [Mapbox Atlas](https://www.mapbox.com/atlas/) on your own server and run the Mapbox Visual for Power BI completely on-premise.

**No data** in the Power BI data model is ever sent to Mapbox APIs.  Only the requested reference resources including map style sheets, vector tiles, icons, and fonts are retrieved from Mapbox APIs.

| Domain          | Port | Resource                        |
|--------------------|------|-----------------------------|
| api.mapbox.com     | 443  | icons, map styles, fonts |
| *.tiles.mapbox.com | 443  | vector tiles                |

### How many data points does the Mapbox Visual support?

Mapbox supports up to the maximum allowed by Power BI, 30,000 rows, for all visualization types including Choropleth (fill), cluster, heatmap, and circle.  If your data is >30k rows, the Mapbox Visual will sample your data down to 30k rows and visualize the resultant sample.  If you need to visualize more than 30k rows for your use case, reach out to our sales team to connect you with a Mapbox Partner to setup a custom solution for your use case.

cc/ @samgehret

**Comment by ryanbaumann** [comment]
Updated readme in master branch at https://github.com/mapbox/mapboxgl-powerbi/commit/32455776ca019e4ea1fbfa696f4861c5668b811e

**Comment by samgehret** [comment]
@HeyStenson we have our compatibility information in the readme. Can we create a section on our help site as well? Do you think we need to?

**Comment by HeyStenson** [comment]
@samgehret I think this information could be a good candidate for adding into the Troubleshooting guide we're working on. One thing to keep in mind, though, is that we'll need to stay on top of updating the info in both places (this repo's readme AND the troubleshooting guide) when changes occur.

**Comment by samgehret** [comment]
This is live now:
https://www.mapbox.com/help/integrate-mapbox-visual-with-power-bi/
