### ISSUE TITLE
Get Power BI `Certified Visual` status

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#202]
Submit the Mapbox Visual for Power BI to the Office Store's certification process https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified

cc/ @samgehret 

Potential challenges

* Accessing exernal resources (api.mapbox.com)
* Applying ESlint checks (we should do this anyway)

**Comment by Mike-Honey** [comment]
Keen to see this resolved as it is affecting my clients especially the Moore Foundation. Please let me know how this can be prioritised.

**Comment by Solarsw** [comment]
Same here. What needs to be done such that this happens?

**Comment by Embedded82** [comment]
Is there a timeline for this?

**Comment by szilardhuber** [comment]
According to Power BI [documentation](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#source-code-requirements) no custom visual can get certified that:

> Accessing external services or resources. For example, no HTTP/S or WebSocket requests can go out of Power BI to any services

As all map custom visuals need to download map content from outside Power BI, none can get certified for now. (Power BI team did not provide a timeline for this, but they are thinking about doing something with this restriction.)

**Comment by Arthur-Ni** [comment]
> According to Power BI [documentation](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#source-code-requirements) no custom visual can get certified that:
> 
> > Accessing external services or resources. For example, no HTTP/S or WebSocket requests can go out of Power BI to any services
> 
> As all map custom visuals need to download map content from outside Power BI, none can get certified for now. (Power BI team did not provide a timeline for this, but they are thinking about doing something with this restriction.)

The ArcGIS visual also accesses external services, but still is part of the standard visuals, so this requirement seems odd.
