### ISSUE TITLE
More complex tilesets not showing in choropleth

### ISSUE THREAD

**Issue by MikeAinOz** [mapbox/mapboxgl-powerbi#203]
I have a 3M tileset mikeainoz.2y7pnzxg that shows up just fine on the choropleth. This is a feature collection of polygons. I have two more complex tilesets mikeainoz.9l4fvniy and mikeainoz.sa4_qld_stroked that ar 12-13M and contain multipolygon features that I cannot get to work. I'm assuming I've stuck some limit here. I've checked the doco and I kind find anything relevant to this. What should I do next? I'm going to simplify the files anyway, I just need some guidance here.

**Comment by ryanbaumann** [comment]
@MikeAinOz what's the minimum zoom level of the tileset that you uploaded to your Mapbox account?  For example, this tileset  has minzoom of14 meaning it won't be visible until I zoom into building level detial in a city.  Additionally, only polygons that have a matching `property` value will show up in my map.  

![](https://cl.ly/2b2S0q2q1A35/download/Image%202018-07-26%20at%207.01.43%20AM.png)

To adjust the zoom level of your tilesets, you can use Tippecanoe https://www.mapbox.com/help/adjust-tileset-zoom-extent/, a command line tool for endlessly customizing how your data appear in tiles.

Please drop your PBI workbook file here and we can help troubleshoot.

**Comment by MikeAinOz** [comment]
@ryanbaumann my zoom level for the non-working tilesets is z6 - z12 which I assume to be the problem as the z0 - z12 works fine. I've been manipulating the GeoJson with Python, so I'd prefer to set the zoom level there, What and where is the property set? I've also got QGIS if I can use that to do the trick, Tippecanoe not an option I'm on Windows :-(. Thanks for all your help, I found the Python Mapbox SDK realy easy to use for the larger tilesets

**Comment by ryanbaumann** [comment]
Does the visual show up if you zoom in past the min zoom of the tileset @mikeainoz?

**Comment by MikeAinOz** [comment]
@ryanbaumann I tried zooming in, no joy. I've attached the pbix renamed as a zip

[MapBoxSA4Qld.zip](https://github.com/mapbox/mapboxgl-powerbi/files/2239506/MapBoxSA4Qld.zip)

**Comment by MikeAinOz** [comment]
@ryanbaumann Thanks Ryan, that's awesome I realize now that my previously working one for Queensland electorates was joined on Name rather than Number which led me astray on this one as I assumed number. Tippecanoe looks good, I'll have to get a Linux VM up and running to use it. Detecting shared borders will go a long way to reducing tileset size. Thanks for your help I'll be showing this sample to a partner business later in the week, so that they can see how great the mapbox PowerBI visual really is :-)

**Comment by samgehret** [comment]
@MikeAinOz Looks like Ryan helped you out here. Closing this issue. Feel free to re-open if this is not the case.
