### ISSUE TITLE
Tooltip on map doesn't display format of field

### ISSUE THREAD

**Issue by stephshadwell** [mapbox/mapboxgl-powerbi#206]
Requirements:
- Only fields in the tooltip panel show up on the map.
- Tooltips respect the data format coming from power bi... so if I looked at the data in a row visualization, it should look the same on the tooltip.
- Aggregations and metrics in the tooltip should respect the form of the metrics being aggregated.

I have noticed that the tooltip on both chloropleth & circle maps does not show the field format correctly. This seems to occur on fields when you have reformatted within Power BI. See screenshots (example is of a chloropleth, but the same functionality is seen on circle maps)

**Tooltip on map**
![image](https://user-images.githubusercontent.com/41364065/43384409-e1367420-93d5-11e8-8567-71578821dc43.png)

**Proportion Field within data table, showing format**
![image](https://user-images.githubusercontent.com/41364065/43384455-05fe823e-93d6-11e8-9692-27476a7ada33.png)

It also doesn't seem to carry through the number of decimal places that have been formatted to fields either, so in places you end up with a large number of decimal places being shown.

Thanks

**Comment by ryanbaumann** [comment]
Thanks for the bug report @stephshadwell!  cc/ @samgehret

**Comment by samgehret** [comment]
Moved to v1.3 @stephshadwell

**Comment by stephshadwell** [comment]
just to say i have downloaded the beta version yesterday, and this does not seem to be fixed (assuming this fix should be in the latest beat viz), see screenshot below

![image](https://user-images.githubusercontent.com/41364065/46802636-ca9cfb80-cd55-11e8-80f8-bee0ff0c5e5c.png)

The crude hospitalisation rate is in the table showing with 2dp as per formatting in the data, but still showing with multiple decimal places in the tooltip

**Comment by Mike-Honey** [comment]
I'm seeing the same issue, also using the current marketplace version 1.3.

**Comment by Mike-Honey** [comment]
I found a workaround is to replace the automatic aggregation of the numeric field with a simple SUM Measure.  

e.g.

`# Hectares = SUM( 'Protected Areas'[Hectares] )`

This is best practise anyway as it centralises and simplifies any further references to that field in other Measures.

**Comment by iCatCat** [comment]
Hello!
I have the same bug. I have 2 measures, that are formatted as %-numbers. Wenn I add only 1 measure to the tooltip it is displayed correctly (not always, but deleting the measure from the tooltip and adding it again or changing the order of fields helps most of the time). Wenn I add the second measure, it is also correct, but the previous measure ist not formatted anymore :) You can see it on the screenshot:
![grafik](https://user-images.githubusercontent.com/24561276/48190672-99f3b600-e343-11e8-942c-f20ec016833f.png)

**Comment by Mike-Honey** [comment]
Thanks for reporting @iCatCat - that's a subtle wrinkle I hadn't noticed.  I can repro that in my file by adding any other measure.  Only one of them is formatted correctly.
