### ISSUE TITLE
Continuous color palettes with `0` in domain stops do not interpolate color values properly

### ISSUE THREAD

**Issue by prateekraina** [mapbox/mapboxgl-powerbi#208]
Hi,

I have created a report with sample data of 3 rows in which there is a Status Field having 3 values : 1,2 & 3
When I put this field in Color field the Med Color is not getting applied.

Attached file for reference.
[MapBox Issue.zip](https://github.com/mapbox/mapboxgl-powerbi/files/2252353/MapBox.Issue.zip)

Prateek Raina

**Comment by ryanbaumann** [comment]
Is your Color a categorial (dimension) value @prateekraina?  If so, there is a special `data colors` format panel that will appear for categorical value color selection.

Documentation ticket for this - https://github.com/mapbox/mapboxgl-powerbi/issues/197

cc/ @samgehret

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by prateekraina** [comment]
Hi @ryanbaumann ,

Thanks for the response. I can settle with the workaround for now.

Regards,
Prateek Raina

**Comment by samgehret** [comment]
Fixed this in the latest beta @prateekraina

**Comment by samgehret** [comment]
This is live now.
