### ISSUE TITLE
Add ability to disable map controls

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#209]
Requirements:
- Be able to toggle the controls on/off at runtime without refreshing the visual.
- Add setting to capabilities.json to switch on/off

Similarly to how Power BI Desktop just added [fine-grained control](https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2018-feature-summary/) over the visual header of each chart, it would be great to be able to hide each map tool (lasso, polygon, zoom controls).

One use case is to be able to create a minimap (e.g. a choropleth) to help navigate a large map thanks to cross-filtering, In this case these tools get in the way, as illustrated below on the top right:

![image](https://user-images.githubusercontent.com/3731532/43665587-b219a696-973e-11e8-822e-9ca568f9d861.png)

Another use case would be to put Mapbox in a tooltip.

**Comment by samgehret** [comment]
@otravers Great feedback! Marking as a feature request for consideration. Really how you are using a minimap to drive the larger map!

**Comment by samgehret** [comment]
@otravers available in beta: https://github.com/mapbox/mapboxgl-powerbi/blob/v1.3_beta/dist/mapboxGLMap.pbiviz

**Comment by samgehret** [comment]
Closing, this is live
