### ISSUE TITLE
Add optional auto-generated legend

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#210]
It would be great to have the option to display a [legend](https://www.mapbox.com/help/extending-interactivity/#add-a-legend) that explains what Circle Color / Size, Choropleth Color, or Cluster Grouping are driven by. Below is a example taken from [this page](https://www.e-education.psu.edu/geog486/node/1869):

![image](https://user-images.githubusercontent.com/3731532/43687185-0a5cd7c2-989f-11e8-9602-c40bb8424e52.png)

This is simpler than what I'd like to see in Mapbox because there's no color-coding. Multivariate symbols are discussed [here](https://www.e-education.psu.edu/geog486/node/1871) and [here](http://gisnouveau.blogspot.com/2015/).

**Comment by ryanbaumann** [comment]
Agree @otravers.  Would a legend palette similar to what is in Mapboxgl-Jupyter work here https://github.com/mapbox/mapboxgl-jupyter/pull/100#issuecomment-400011952?  

Would you need the legend placed on top of the viz?  Or ideally could you move the legend to another viz element?

**Comment by otravers** [comment]
@ryanbaumann yes what you've been working on in Mapboxgl-Jupyter is right on the money. Indeed it would be fantastic if the legend was a movable object. Even more awesome would be the ability to only display the legend in its own chart in the PBI canvas, so that it's effectively the legend to the whole dashboard.

**Comment by samgehret** [comment]
Implementation (work in progress)
- A legend option would need to be added for each layer type: circle, cluster, heatmap, and choropleth. It should be a toggle on/off. 
- Choropleth / Extrusion should be the MVP: It should have a legend to explain the colors, and also explain the heights. It should also contain the metric name as well. For example:
![image](https://user-images.githubusercontent.com/3859246/48156404-3786b100-e282-11e8-871e-8c743ea2b6b1.png)

**Comment by samgehret** [comment]
Acceptance Criteria:

- [ ] Choropleth has a legend control for color only, no extrusion legend
- [ ] Circle Layer has a legend control, indicating color only
- [ ] Cluster layer has a legend control, indicating color only

Nice to have:
-[ ] Heatmap layer has a legend control for color 
- Circle and Cluster layer has a legend control for size.

**Comment by samgehret** [comment]
This feature is live in the marketplace

**Comment by otravers** [comment]
Awesome @samgehret, thanks! Should I create new issues for the remaining nice-to-haves in your list?

**Comment by samgehret** [comment]
@otravers Absolutely! We love getting your feedback.
