### ISSUE TITLE
Add Label Formatting

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapboxgl-powerbi#211]
> Can you please make label formatting available? 
> In the attached example you can see how the labels make the map useless. 

![image](https://user-images.githubusercontent.com/16272584/43811484-adb1cf4e-9a8a-11e8-9124-8f6fa1394eaf.png)

**Comment by ryanbaumann** [comment]
Additionally, while we work this, we should add label support for Circle layers.  Tracking in https://github.com/mapbox/mapboxgl-powerbi/issues/141
