### ISSUE TITLE
Handle color selection like in default Power BI charts

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#212]
Currently Mapbox lets us define Mid / Med / Max / Highlight colors. First, that language is not consistent with PBI's default charts (Minimum / Center / Maximum). I think custom charts should remain as closely aligned with PBI defaults as possible in order to reduce the learning curve.

More importantly, Power BI default charts offer the ability to diverge colors by value (provided you select the _Diverging_ option), which is handy when you have outliers that would otherwise overwhelm how everything else is color coded. It's also nice to be able to define where the center is (e.g. 0 if you have a measure with negative and positive values). Here's what that looks like, please consider doing something similar:

![image](https://user-images.githubusercontent.com/3731532/42473162-dcfd8ef6-8391-11e8-993d-3a5bba9cbe40.png)

Below is a choropleth example using the default filled map, see how the minimum / center / maximum values were handpicked based on the actual data. Power BI will soon add the ability to drive chart options with DAX functions, which will make this even more powerful and customizable (e.g. decide that the center color is the median, mean, or something else).

![image](https://user-images.githubusercontent.com/3731532/44004790-f46d2fca-9e3e-11e8-9600-5cffde67c061.png)

See:
https://docs.microsoft.com/en-us/power-bi/service-tips-and-tricks-for-color-formatting#use-diverging-color-scales

**Comment by ryanbaumann** [comment]
Cc/ @samgehret

**Comment by samgehret** [comment]
Acceptance Criteria:
- [ ] Within Circle and Choropleth, implement a toggle called "Diverging"
- [ ] When Diverging is enabled, Minimum, Center, and Maximum text boxes become available, such as in the above screenshot.
- [ ] Any value which is above the Maximum value will be the Max color.
- [ ] Any value which is below the Minimum value will be the Min Color.
- [ ] Values which are between Maximum Value and Center Value should have an appropriate gradient between the Max and Med Color.
- [ ] Values which are between Minimum Value and Center Value should have an appropriate gradient between the Min and Med Color.

**Comment by samgehret** [comment]
This is live in the marketplace @otravers
