### ISSUE TITLE
Can't add latitude and longitude from Powerbi (from dimensional attribute via SSAS)

### ISSUE THREAD

**Issue by dbdave** [mapbox/mapboxgl-powerbi#215]
Not sure exactly when it started but older versions (early 2018) allow this, latest and at least the last few published do not.
I can't drag latitude or longitude from a dimensional attribute stored as a double. The attribute comes from SSAS stored as a double

Please let me know what extra info I can provide
![image](https://user-images.githubusercontent.com/3037794/44643817-3f6ddd80-aa15-11e8-9705-e4ff25325615.png)

**Comment by dbdave** [comment]
note: when dragging from fields to visualizations the field is rejected int he latitude and longitude boxes.
it is working as I expect in version 1.1.3

**Comment by samgehret** [comment]
@dbdave Sorry you are having that issue! Can you send over a .pbix file?

**Comment by dbdave** [comment]
@samgehret Managed to solve this one myself - SSAS was outputting my double as text for... ssas reasons. I've managed to make it work with a specific attribute value as the double which is now working as it should. Still not sure why it was working in 1.1.3 but I suspect it probably shouldn't have been working (which you guys have corrected at some point) as that could end up being expensive for large volumes of geo points.
