### ISSUE TITLE
Refactor color and size cals to always use domains, continuous color palettes

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#22]
All color and size interpolation calculations should:

**If data value is continuous/measure:**
1. Calculate natural breaks domains with geoStats - http://www.intermezzo-coop.eu/mapping/geostats/.  Domains should have 5-6 discrete breaks.
2. (if color) Calculate continuous color scales using the PowerBI Color palette selector UI and Chroma.js.
3. Create `interpolate` Mapboxgl expressions based on natural breaks domains to style color or size of data

**If data value is discrete/dimension:**
1. (if color) Calculate discrete color scale using PowerBI discrete color palettes.
2. Create `match` Mapboxgl expressions to style color, size of data features

* All setting color selections should use color scale selections if data is continuous/measure.
* All setting color selections should use discrete color picker selections if data is discrete/dimension.

#Example 
Currently, heatmap visualizations only allow the user to select a single `color`.  The color selection changes the max density color used in the heatmap viz.  This is confusing to the user, who wants to control the entire color ramp for the data in the viz.

![](https://cl.ly/2o0u463K3E1M/download/Image%202018-01-03%20at%208.22.05%20AM.png)

cc @gyulalaszlo

**Comment by szilardhuber** [comment]
I managed to add a gradient selector control in a test project but I can't get it replace the property that it should replace but it is displayed as a separate control.

I have created an issue for this: https://github.com/Microsoft/PowerBI-visuals/issues/301

**Comment by petispaespea** [comment]
@ryanbaumann Please test PR #50, it should have everything but the gradient selector.

**Comment by ryanbaumann** [comment]
Other than the gradient selector, this is working awesome.  Nice job @petispaespea

**Comment by ryanbaumann** [comment]
Does this reply help solve this issue @szilardhuber ?  https://github.com/Microsoft/PowerBI-visuals/issues/301#issuecomment-363785222

**Comment by szilardhuber** [comment]
>  Does this reply help solve this issue on using continuous color palettes @szilardhuber ? Microsoft/PowerBI-visuals#301 (comment)

No, that's not helpful at all. @petispaespea could you push them a bit more to help us solve this issue? I'm pretty sure it is either a bug on their side or something is not even implemented that they suggest is.

**Comment by LeoLu28** [comment]
@ryanbaumann  in mapbox powerbi can we set values or range values in a specific color?
example 0 = red, 1 - 4 =  yellow and > 5 is Green?
Thank you

**Comment by ryanbaumann** [comment]
Hey @leolu28 -- This ticket tracks adding specific value ranges to colors as a feature request.  We'll take your feedback when building our roadmap, thank you!

**Comment by ryanbaumann** [comment]
This is now possible in the latest version of the Mapbox Visual if you use `string` values for your categories @LeoLu28 - try it out and let us know your feedback at https://github.com/mapbox/mapboxgl-powerbi/pull/163
