### ISSUE TITLE
Multiple levels issue on choropleth

### ISSUE THREAD

**Issue by ghost** [mapbox/mapboxgl-powerbi#228]
I've created a choropleth with 2 custom tilesets.
When I set the maximum and minimum zoom levels it changes then on both tile levels. Surely this is incorrect?

I want to use one level of custom boundaries (polygons) when 'zoomed out' and a more detailed set when 'zoomed in'.

**Comment by samgehret** [comment]
@ChristopherWesson Unfortunately, we can only have one choropleth layer exposed at a time. The only way to switch between them is drilling, so you can't switch between them using min/max zoom. However, your proposed functionality is a great idea and one we will consider for the future. Thanks!
