### ISSUE TITLE
Integrate Mapbox Tilequery API with Choropleth Fill Maps

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#233]
Placeholder feature, needs to be built out.

Basically for any fill map... including those with custom polygons, the Mapbox CV would do some data prep to associate data points to specific polygons using our tilequery api:

https://www.mapbox.com/help/tilequery-api-playground/

That way, users can just use lat/long data and take advantage of fill maps without having to manicure data to match to polygon IDs.

**Comment by PedroRiveraTorresMoir** [comment]
Polygon heatmaps based on points density per polygon would be very interesting. I wonder how this would work when polygons are 3D extruded with a base height though (in the soon to be released visual), as lat, long pairs often miss the altitude property. Would this feature still work? Or would it only apply to base_height=0 polygons?


________________________________

**Comment by otravers** [comment]
This would effectively provide the ability to perform spatial joins, correct? Tableau and QGIS can do this, Power BI doesn't (ESRI said they were considering adding it but I'm not holding my breath):
https://unilytics.com/tableaus-new-killer-mapping-feature-spatial-join/
