### ISSUE TITLE
Add legend option to all maps

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#24]
# Feature request

Based on a users data visualization type, we should generate an optional legend to display.

Example in this tutorial of a good legend generation for color and size -> https://www.mapbox.com/help/gl-dds-map-tutorial/

@szilardhuber

**Comment by ryanbaumann** [comment]
This helper library could be useful here: https://github.com/Microsoft/powerbi-visuals-utils-chartutils/blob/master/docs/api/legend.md

**Comment by otravers** [comment]
Covered by #210?

**Comment by ryanbaumann** [comment]
Yep!  Thanks @otravers
