### ISSUE TITLE
Add ability to create multiple circle layers representing different dataset columns

### ISSUE THREAD

**Issue by kbauhausness** [mapbox/mapboxgl-powerbi#244]
Currently, it's not possible to create multiple circle layers. This ticket tracks the request for a feature allowing users to create multiple circle layers in Mapbox Visual for Power BI and represent them both on one map.

For example, one circle layer could show store locations and the other could show warehouse locations.

cc @samgehret

**Comment by samgehret** [comment]
@kbauhaus this currently may be possible. if they have attributes associated with their lat/long points such as "Store" or "Warehouse", these circles could be colored based on those attributes. Power BI slicers could be used to show one or the other or both. Would this solve their use case?

**Comment by rwmnau** [comment]
This would work but there doesn't appear to be any way to set a "legend" property to color the circles separately - does this functionality exist? If it does, it would appear to answer this question and I'd love to use it!
