### ISSUE TITLE
No Choropleth Shapes Showed Up with My Uploaded Tileset

### ISSUE THREAD

**Issue by TiffanyFHA** [mapbox/mapboxgl-powerbi#246]
I uploaded a small kml file to be a tileset in my account. I used a small sample excel data file to test in Power BI desktop with choropleth, but no custom shapes showed up on the map no matter how I zoomed in or out.

**Comment by TiffanyFHA** [comment]
Uploaded a few screenshots to show my configuration

**Comment by stephshadwell** [comment]
check what the field is called in the tileset. Essentially the Vector Property Level 1 text needs to match the name of the field in the tileset, the location field is matching with

**Comment by TiffanyFHA** [comment]
Thanks Stephshadwell! Like you said, the location field name should be EXACTLY the same with the tileset property name.
