### ISSUE TITLE
3D extrusions on fill maps for Power Bi does not work

### ISSUE THREAD

**Issue by warrendean81** [mapbox/mapboxgl-powerbi#247]
From Link: https://blog.mapbox.com/six-new-features-for-mapbox-visual-for-power-bi-472e9e1d3998
3D extrusions on fill maps:
Add an extra dimension to your fill visualizations by using 3D extrusions. In addition to data-driven coloring of polygons, users can now add data-driven heights to these polygons as well. Just drop a metric into the “size” dimension and set your relative “extrusion height.”

Error message received:
Add only Location & Color fields to use a choropleth layer.
Yet to do 3D extrusions we need to add a size dimension

Using both Microsoft store version and version v1.3beta

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by samgehret** [comment]
@warrendean81 thanks for reporting. The way Microsoft releases new versions of any custom visual involve clearing a series of caches after the visual is approved. So it basically gets released at different times for different users. The Extrusions should definitely be working for you over the next few days. However, I can confirm the feature works in the [beta version](https://github.com/mapbox/mapboxgl-powerbi/blob/v1.3_beta/dist/mapboxGLMap.pbiviz)

**Comment by mryckman** [comment]
@samgehret thanks for the info. For what it's worth, I tried the beta version in the link and I'm definitely seeing some new options - including the geocoder and extrusion settings in the choropleth layer. But if I try to add a field to the "size" thing I get the informational message that a choropleth can only have color and location properties. Am I doing something wrong?

**Comment by samgehret** [comment]
@mryckman oh yeah! one thing that you might need to check is whether your circle layer is turned off. only choropleth should be enabled.

**Comment by mryckman** [comment]
Thanks again, @samgehret ... I think I found it... and I probably just missed this myself. It seems you need both a color field and a size field. If I remove color and only use size, the error appears, but using both size and color makes it work as expected.

**Comment by samgehret** [comment]
This is live now... closing issue.
