### ISSUE TITLE
Implement report tooltip ability

### ISSUE THREAD

**Issue by katoen** [mapbox/mapboxgl-powerbi#249]
As per October '18 update support for report tooltips in custom visuals is generally available. 
[link](https://docs.microsoft.com/en-us/business-applications-release-notes/October18/intelligence-platform/power-bi-custom-visuals/custom-visual-support-report-tooltips)

As a starting point, this seems like a good reference how to implement this:
[Add canvas tooltips support to sampleBarChart (#35)](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/commit/42aa6b6d69dea0b5e75bb6a78779b524efde9800)

**Comment by otravers** [comment]
I second this. Here's a mockup where the report tooltip shows a place's photo. (That tooltip is actually from the table to the right of the map, but this shows the purpose and look & feel).

![image](https://user-images.githubusercontent.com/3731532/49382794-1173f580-f6f6-11e8-8bef-1d7b6a99ed03.png)

**Comment by ryanbaumann** [comment]
I'll take a look at adding this to beta-1.4, looks like a simple change.

**Comment by ryanbaumann** [comment]
Attempted to implement this in beta 1.4 - I was able to enable the custom tooltip in the UI for the Mapbox Visual, but not get the tooltip injected with the custom report from another page.  I'll push my attempt to a PR for later reference.  Pushing to v1.5

**Comment by otravers** [comment]
[This page](https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/adding-report-page-tooltips/#applying-report-page-tooltips) might help.

Also, report tooltips work in Maq's KPIColumn (I tested it), here's the related commit for reference:
https://github.com/maqsoftware/PowerBI-visuals/pull/339

**Comment by ryanbaumann** [comment]
Thanks for the reference code, @otravers!

**Comment by lsilvoy** [comment]
Could you please provide an update on the report tool tips. I'm using a mapbox product in my PowerBI dashboard and my client is requesting report page tool tips. It would be great to know if this feature will be available soon!
