### ISSUE TITLE
Extract Base and Height from vector source to see 3d buildings with different colors

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#250]
How challenging would it be to create an alternative mode to choropleth height? The current version allows height to be defined by a client-side field. Another, very useful option would be to extract the height and base height properties of the vector source. This would allow us to, for example, be able to see a 3d building with different colors by floor based on occupancy.

**Comment by ryanbaumann** [comment]
@PedroRiveraTorresMoir no promises, but I'll take a look at scoping this in the next few days.

**Comment by PedroRiveraTorresMoir** [comment]
Thanks!

**Comment by ryanbaumann** [comment]
Scoping this feature -

1. Add a `Extrusion Height Type` dropdown to the Choropleth settings
    * Options: `interpolate`, `identity`
2. If `interpolate` is selected (default) - show the `extrusion height` number selector, same as today
3. If `identity` is selected (optional) - show a new field, `extrusion property name`.
    * User enters property name from vector tile property to style height by.  I.E. if there is a property named `extrusion_height` that contains an integer, then the user types `extrusion_height` into the `extrusion_property_name` text field
    * Extrusion height is set equal to the value of the integer field
    * Requirement - Vector tile property must be a numeric data type

Estimated effort: 1 day

**Comment by PedroRiveraTorresMoir** [comment]
@ryanbaumann this is great. I imagine that adding` base height property name` field next to the proposed `extrusion propery name` field would be of similar scope? This would be very useful to model floors that are above terrain level.

**Comment by PedroRiveraTorresMoir** [comment]
@ryanbaumann since you seem to be scoping for 5.0, I thought it'd be convenient to lobby for additional features like this one as well!
