### ISSUE TITLE
Updating to Mapbox CV 1.3 is messy

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#252]
I have a file with existing Mapbox Custom Visuals. When I use the marketplace to update to Mapbox 1.3, it says it will update existing visuals.  This is normal for custom visuals.

However the update isn't actually working.  I'm left with 2 Mapbox icons in my Visualisation pane for that PBIX, and none of the existing visuals were updated. When I try to update the visuals manually (by clicking the 2nd button in the visualizations pane, the fields in the field wells are all jumbled, e.g. a field from the Tooltips well ends up in the Color well.

My workaround is to duplicate each Mapbox visual first, then rebuild it's fields and check all the settings in one copy, referring back to the other copy.  It's quite painful.

I hope whatever is causing this can be eliminated or minimized in future updates.

**Comment by ryanbaumann** [comment]
Thanks for the bug report @Mike-Honey.  What version of the Mapbox Visual are you upgrading from in your workbook to get to v1.3?

cc/ @samgehret

**Comment by Mike-Honey** [comment]
I expect it was v1.2, but I couldnt figure this out definitely. AFAIK there's no way to tell using the Power BI Desktop UI?

My usual trick is to rename the PBIX to a zip and explore the \Report\Custom Visuals folder. But there arent any subfolders named MapBox?  There are several named with a GUID starting PBI_CV_... . 

After removing all the non-Mapbox custom visuals I was left with 3 of those folders. The versions (from the package.json files in each PBI_CV_ subfolder were:
1.1.0
1.1.3
1.2.3

**Comment by ryanbaumann** [comment]
@Mike-Honey I'm going to close this issue - we're tracking compatibility changes for new releases as part of our release process now cc/ @samgehret
