### ISSUE TITLE
Inconsistent auto zoom behavior on choropleth using external slicers

### ISSUE THREAD

**Issue by tonmcg** [mapbox/mapboxgl-powerbi#257]
The choropleth map shows inconsistent auto zoom behavior when filtering polygons using external slicers. [This PBIX report shows election results](https://github.com/tonmcg/spatial-analysis/blob/master/app/Power%20BI%20World%20Tour%20-%20Seattle.pbix) for every county in the U.S. When external slicers are used to filter either states or counties, the map doesn't consistently zoom in to the filtered region.

![auto zoom issues](https://user-images.githubusercontent.com/12642427/47963495-1c564000-dffb-11e8-9bc0-5f7d0a12aafc.gif)

There doesn't seem to be a pattern to when the auto zoom fails. Generally, auto zoom on California and New York always fails. Auto zoom also fails on other states as well, but not as consistently as New York and California.

**Comment by Mike-Honey** [comment]
I've struck a similar issue on another project, but using a custom tileset. Here's a repro:

https://github.com/Mike-Honey/spatial/tree/master/mapbox/location%20prototype

**Comment by ErikGoncalvesCoder** [comment]
I have a same problem with auto zoom at power bi filter interaction.

**Comment by ryanbaumann** [comment]
@ErikGoncalvesCoder are you able to reproduce the issue using the latest Beta v1.4?  
https://github.com/mapbox/mapboxgl-powerbi/raw/beta-1.4/dist/mapboxGLMap.pbiviz

**Comment by Erik-Goncalves** [comment]
@ryanbaumann thank your support, 
the problem seems to be solved but I making more some tests.

**Comment by Erik-Goncalves** [comment]
@ryanbaumann Do you have a date for implementation of the beta version?

**Comment by ryanbaumann** [comment]
It's officially accepted to the Microsoft store - v1.4 should be available for you via the store by Friday March 22

**Comment by Erik-Goncalves** [comment]
Ok @ryanbaumann, thank you for the help.
