### ISSUE TITLE
Choropleth hover and mouseover options

### ISSUE THREAD

**Issue by tonmcg** [mapbox/mapboxgl-powerbi#260]
Making available the following three options for the `hover` or `mouseover` events on polygons in a choropleth will create a much better user experience:

1. Ability to disable the highlight altogether. Often we may want nothing to happen when a user hovers over a polygon. The tooltip may convey all the information we need. See a toy example here:
![tooltip_hover](https://user-images.githubusercontent.com/12642427/48174378-bfe27180-e2d5-11e8-93f7-b18d47941292.gif)

2. Ability to adjust the stroke color only. On hover, I'd like to be able to set the stroke to be another color than the default. See below for an example an how the stroke changes from grey to black on hover:
![stroke_color](https://user-images.githubusercontent.com/12642427/48173896-aa6c4800-e2d3-11e8-8281-8d947a581e47.gif)

3. Ability to set the fill opacity only. Related to #248, I'd like to be able to define an opacity less than 1 on hover. See how the state fill changes when there's a hover event:
![opacity_example](https://user-images.githubusercontent.com/12642427/48174213-21561080-e2d5-11e8-9a7f-cb107338da68.gif)

**Comment by ryanbaumann** [comment]
Great, clear use case and feature request ticket @tonmcg.  Thank you.  We'll consider these features for upcoming releases.

cc/ @samgehret

**Comment by ryanbaumann** [comment]
We should look at this feature after completing the featureState refactor, which will greatly increase the performance of mouseover interactions for hover/highlight/tooltip events.  https://github.com/mapbox/mapboxgl-powerbi/issues/286

**Comment by mate-turi** [comment]
Feature request will be handled in the new project. Your reported feature request can be found [here.](https://github.com/starschema/mapboxgl-powerbi/issues/35)
