### ISSUE TITLE
[Feature] Add a measure distance tool                                                                                                                                                                                                                                                                    

### ISSUE THREAD

**Issue by danielkorc** [mapbox/mapboxgl-powerbi#261]
MapBox PowerBI visualization is missing two key features - find location based on coordinates (geocoder only accepts addresses), ideally the coordinates format can be selected (not just basic Lat/Long); and the other feature missing is to measure distance between points or even better to show radius of ceertain distance. Any plans to implement that? That would make this visualization actually practical for real life mapping use.

**Comment by ryanbaumann** [comment]
Great feature request, thank you for ticketing @danielkorc!

Summarizing the request below:

1. Allow `reverse geocoding`, with a user-specified coordinate format, inputs into the `search` input bar (to complement the `forward geocoding` name -> location capability currently in the visual)
2. Add a measurement tool between two points, in addition to the current drawing / selection tools

cc/ @samgehret

**Comment by ryanbaumann** [comment]
I'm re-orienting this ticket to focus on measuring the distance between two points.  Opening up another issue for tracking reverse geocoding search.

**Comment by otravers** [comment]
One way to do this would be to include turf.js support.
https://docs.mapbox.com/help/how-mapbox-works/geospatial-analysis/

(This is possibly my greediest feature request to date, and that's saying something!)
