### ISSUE TITLE
No ability to restrict the bounds of the map (for panning and zooming) in Power BI

### ISSUE THREAD

**Issue by djodonnell** [mapbox/mapboxgl-powerbi#262]
In Mapbox GL you have the ability to restrict the bounds of the map with respect to panning and zooming.

https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/

e.g. from Mapbox GL

```
// Set bounds to New York, New York
var bounds = [
    [-74.04728500751165, 40.68392799015035], // Southwest coordinates
    [-73.91058699000139, 40.87764500765852]  // Northeast coordinates
];

var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-73.9978, 40.7209],
    zoom: 13,
    maxBounds: bounds // Sets bounds as max
});
```

We should have the ability to optionally restrict the bounds of the rendered map.  My use case in particular is rendering indoor floorplans and although I can render these on a "world map" the user still has the ability to move over the entire world.

**Comment by ryanbaumann** [comment]
Thanks for the well written feature request!  Cc @samgehret

We should also consider adding an option to lock map position (no pan or zoom)

**Comment by ryanbaumann** [comment]
Related to https://github.com/mapbox/mapboxgl-powerbi/issues/263 - I would strongly consider first making the "no interactivity" / "pin the map" option before this feature.
