### ISSUE TITLE
No ability to prevent zooming and panning of the map (aka "turn off interactivity") in Power BI

### ISSUE THREAD

**Issue by djodonnell** [mapbox/mapboxgl-powerbi#263]
There is currently no way to turn off map interactivity in Power BI.  This option is available in Mapbox GL.

https://www.mapbox.com/mapbox-gl-js/example/interactive-false/

e.g. taken from Mapbox GL

```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-74.50, 40],
    zoom: 9,
    // causes pan & zoom handlers not to be applied, similar to
    // .dragging.disable() and other handler .disable() functions in Leaflet.
    interactive: false
});
```
This option should be made available in Power BI as there are use cases where the initial map position needs to be fixed and you do not want the user being able to pan or zoom on the map.

**Comment by otravers** [comment]
@ryanbaumann this brings a meta question: do you maintain a coverage list that compares what's in the JS API vs. what's available in the PBI custom chart? I don't believe for instance that I can change the tileset language or case in PBI. Is it an end goal to eventually reach feature parity?

**Comment by ryanbaumann** [comment]
@otravers tagging in @samgehret as the solution owner for the Mapbox Visual in Power BI for that question.

**Comment by ryanbaumann** [comment]
> I don't believe for instance that I can change the tileset language or case in PBI. Is it an end goal to eventually reach feature parity?

Some features in GL JS make sense to expose to an end BI developer, and others don't make as much sense.  We will continue prioritizing features to expose in Power BI from GL JS based on user and developer needs @otravers.

Putting this on the radar for v1.5
