### ISSUE TITLE
No ability to set the original map position and zoom level in Power BI

### ISSUE THREAD

**Issue by djodonnell** [mapbox/mapboxgl-powerbi#264]
Currently there is no ability to set the initial map position and zoom level in Power BI as is available with Mapbox GL.  I have tried to manually position the map and save the workbook (hoping that the position would be retained) but the map just returns to its default.

There are fields within Power BI that look like they should do the job under the map control: Viz Settings (zoom, longitude, latitude) but fiddling with these didn’t have any effect.

In Mapbox GL this can be done when the map is instantiated:

```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-73.9978, 40.7209],
    zoom: 13
});
```

**Comment by ryanbaumann** [comment]
The fields in the pbi viz settings should work to save the map position - can you replicate the issue and provide a sample workbook?

**Comment by djodonnell** [comment]
Thanks for the quick reply Ryan.

I have done some further investigation and these fields do in fact work, but the control does not refresh (and apply the settings) until you select another sheet and then return to the original sheet containing the Mapbox map which causes it to re-render.

**Comment by ryanbaumann** [comment]
Ah, that's interesting.  We can report this as a bug to PBI custom visuals - thanks @djodnnell

**Comment by otravers** [comment]
I can replicate this behavior and the clicking out/in workaround. It's a bit irritating when you're fiddling around to try and get the best zoom level and center for the data you're presenting, which may or may not be what autozoom comes up with.

**Comment by ryanbaumann** [comment]
Are you each using a custom Mapbox style sheet created in Studio when you see this zoom-after-interaction behavior?  Or do you see it with both custom map styles and the default light, dark, satellite, etc. Mapbox styles?

**Comment by otravers** [comment]
Happens with both custom and default styles.
