### ISSUE TITLE
Suggested QOL improvements to Choropleth settings

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#265]
I've wasted more time than I'd care to admit trying to get the right values in Source Layer Name and Vector Property Level. Mapbox Studio doesn't preview values for tilesets, which doesn't help in case you don't have the source file at hand. And in some cases I've quadrupled-checked and still get weird behavior, like Mapbox showing boundaries at level 2 that should be from level 1. This can get tedious to troubleshoot.

Suggestions:

- It would be great if Mapbox studio showed more about tilesets, maybe in a data table
- Populate Source Layer and Vector Property Level with valid values retrieved from the vector tile URL for that level.

Also, I think the _Opacity / Outline / Outline Width / Outline Opacity_ settings should be specific to each level.

**Comment by ryanbaumann** [comment]
This is great feedback, @otravers. Thank you for ticketing. 

Adding one level of detail further here:

1. Populate the `source layer` and `vector property` with a dropdown list of available options after a user inputs their mapbox vector tile layer for the Choropleth.
2. Display metadata about the tileset in a preview table, including property data types, minzoom, and sample data values in the properties of your tilesets.

Is that right @otravers ?

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by otravers** [comment]
@ryanbaumann yes that's a perfect summary.
