### ISSUE TITLE
Viz Settings -> Auto Zoom creates plotting issues with multiple pages

### ISSUE THREAD

**Issue by intothenight** [mapbox/mapboxgl-powerbi#267]
This option flag is critical in order to make the map interface dynamic (ie changing data, changes centre point and zoom). However given the time it takes for the visualization to completed its animation, the plotting happens mid animation and does not present the map at its intended final render.

This occurs when you have multiple pages, and any pages that are not currently selected and rendered at time of plotting are affected.

Example:
![a9r274c](https://user-images.githubusercontent.com/44071285/49535286-a69ef780-f878-11e8-867f-4b792dc2282d.png)

**Comment by ryanbaumann** [comment]
Thanks for the bug report @intothenight - can you include a sample workbook or GIF of the issue?  cc/ @samgehret
