### ISSUE TITLE
Include Support for Right-to-Left Language Labels

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapboxgl-powerbi#268]
Currently, if I try to change labels in a Custom Map style to a Right-to-Left language (e.g. Arabic, Farsi, Hebrew, etc.) the style displayed in Power BI will not properly render the labels. 

In order to correct this, the Power BI plugin could add support for the r-to-l GL JS plugin: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text

This _should_ allow these custom styles to be rendered correctly.

**Comment by ryanbaumann** [comment]
We should add this as a default plugin as soon as we refactor for PBI Visual Tools v3 launches to support more localizations in Power BI.  https://github.com/mapbox/mapboxgl-powerbi/issues/281

**Comment by adild2k** [comment]
Hi Everyone,

Is there any update on it? If not,what's the possiblity of turning the Arabic off whereever its appearing. How we can achieve this unless and until when the update is available?

Regards

Adil
