### ISSUE TITLE
Better Tooltip Control

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#270]
Only display field in tooltip, if they are specified in the tooltip field. Currently, if there is anything in the tooltip field, the map will display all the available fields in the report.

![image](https://user-images.githubusercontent.com/3859246/50786934-cfe0e800-1269-11e9-812d-48bd5d3242b4.png)

**Comment by banwarp** [comment]
I would also like to have tooltip page support. I found this code snippet on the Power BI Github page:
https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/adding-report-page-tooltips/

"tooltips": {
        "supportedTypes": {
            "default": true,
            "canvas": true
        },
        "roles": [
            "tooltips"
        ]
}

I am not a developer, so I am hesitant to try and make changes myself.

**Comment by banwarp** [comment]
Also, it seems that the Tooltip requires three decimal places when showing decimals. This means that if I want to show percentages without decimal places, the Tooltip inserts one or more zeros in front of the number. Thanks!

![tooltip1](https://user-images.githubusercontent.com/43013293/50921025-d606ce00-13fb-11e9-8b9c-77166bc0b951.png)
![tooltip2](https://user-images.githubusercontent.com/43013293/50921028-d69f6480-13fb-11e9-9be0-daddb790e3b9.png)

**Comment by samgehret** [comment]
Acceptance Criteria:
- [ ] When no dimensions are added to the tooltip field, the tooltip should be disabled.
- [ ] When a dimension is added to the tooltip field, ONLY those fields should come up in the tooltip. (currently when only one field is added, multiple appear like in the above screenshot).
- [ ] The number formats in the tooltip should match the format from the power bi data model (including aggregations like sum, min, max, and average).

**Comment by ryanbaumann** [comment]
In the current `beta-1.4` branch as of 2/3/2019, the tooltip for a `cluster` layer shows values for all aggregation types.  Only the selected aggregation type should show up in the tooltip.  

Example where `maximum` is selected for the `cluster aggregation`, yet all aggregation types are showing up in the tooltip:
![](https://cl.ly/eceda1ca1d90/download/Screen%20recording%202019-02-03%20at%2012.06.22%20PM.gif)

**Comment by ryanbaumann** [comment]
In the current `beta-1.4` branch, also noting that for Choropleth layers, the `location` field is appearing the tooltip, even if it is not in the Tooltip data column for the viz.

Example:
![](https://cl.ly/2dfd2e846d0e/download/Screen%20recording%202019-02-03%20at%2012.16.38%20PM.gif)

**Comment by petispaespea** [comment]
The `beta-1.4` was updated to address these issues.

**Comment by ryanbaumann** [comment]
@petispaespea awesome, that looks to address the two issues above.  Looking good.

**Comment by samgehret** [comment]
This feature is live in the marketplace
