### ISSUE TITLE
Custom data in Mapbox Studio doesn't appear in PowerBI

### ISSUE THREAD

**Issue by mzdraper** [mapbox/mapboxgl-powerbi#272]
Two users have reported this issue.

### Steps to replicate
1. Create a new map style in Studio
2. Add custom point data
3. Publish the style & clear cache - Style URL loads a map with no errors
4. Open a PowerBI report
5. In the Viz settings, set the custom style to the newly created map
6. Check the console

![image](https://user-images.githubusercontent.com/25856619/51338008-89e00d00-1a3d-11e9-9e85-6aa4200d46de.png)

cc @samgehret

**Comment by samgehret** [comment]
@mzdraper you must use the "Use" url... IE mapbox://styles/samgehret/cjqz8dt7m12bg2rlhian942tk

**Comment by mzdraper** [comment]
@samgehret Apologies - the Style URL, not Share URL, is being used and the break is occuring.

**Comment by mzdraper** [comment]
I don't think this issue is specific to the Mapbox PowerBI Plugin. I believe this is a general incompatibility between mapbox.streets-v8 and older versions of Mapbox GL JS.

I was able to replicate the above issue above issue in plain GL JS by adding a style that uses mapbox.streets-v8 data and is rendered with GL JS 0.47.0. Check out this [JSBin](https://jsbin.com/siwitiyuwo/edit?html,output). Interestingly, when updating to 0.48.0 (the same version as PowerBI), the style works.

**Comment by samgehret** [comment]
@Ragha2207 to use custom shape files in Power Bi, you can follow this tutorial here: https://docs.mapbox.com/help/tutorials/power-bi-choropleth-map/#upload-your-tileset-to-mapbox

**Comment by samgehret** [comment]
@mzdraper we are upgrading our version of GL-JS in our next mapbox release.

**Comment by ryanbaumann** [comment]
This was closed in v1.4
