### ISSUE TITLE
JS Error: Cannot read property 'getSource' of undefined at n.getSource

### ISSUE THREAD

**Issue by uve** [mapbox/mapboxgl-powerbi#273]
**Stack Trace:**
TypeError: Cannot read property 'getSource' of undefined at n.getSource (:31:21197) at e.exports (:35:26270) at e.exports.i [as render] (:34:31466) at i (:34:24384) at Object.keydown (:34:24932) at HTMLDivElement.p.keydown (:34:9828)
**Next stack**
TypeError: Cannot read property 'getSource' of undefined at n.getSource (:31:21197) at e.exports (:35:26270) at e.exports.i [as render] (:34:31466) at i (:34:24384) at Object.mouseout (:34:24895) at HTMLDivElement.p.mouseout (:34:9086)

**Comment by ryanbaumann** [comment]
Thanks for posting, @uve!  Are you seeing this error in the production build of Mapbox GL JS published to the Office Store?  `v1.3.0`

cc/ @samgehret

**Comment by ryanbaumann** [comment]
@uve are you seeing this bug on the latest beta v1.4?  https://github.com/mapbox/geocoding/issues/757

**Comment by ryanbaumann** [comment]
Not seeing this reported in v1.4 - closing.
