### ISSUE TITLE
Update Mapbox GL JS to latest version

### ISSUE THREAD

**Issue by mzdraper** [mapbox/mapboxgl-powerbi#278]
**Describe the bug**
There's a compatibility issue between older versions of Mapbox GL JS (around 0.48.0/0.49.0) and Mapbox Streets V8 data. This is causing custom data not to appear and/or styles breaking within PowerBI.

**Possible solution**
Updating to Mapbox GL JS to 0.52.0.

**Who would this benefit?**
This is mostly affecting users (and new users especially) who create a new map in Studio and are unable to see their data in PowerBI. This would greatly benefit the onboarding experience.

related: #272

**Comment by ryanbaumann** [comment]
Updated the GL JS version in latest beta v.1.4 - @mzdraper can you try the beta resolves your issue?  

https://github.com/mapbox/mapboxgl-powerbi/raw/beta-1.4/dist/mapboxGLMap.pbiviz

cc/ @samgehret

**Comment by ryanbaumann** [comment]
Complete in latest beta v1.4 - reference link above for testing.
