### ISSUE TITLE
Update to Powerbi-visuals-tools v3+

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#281]
Power BI Visuals tools introduce modern ECMAScript 2015 modules into TypeScript code.  This will allow us to clean up the code base and make it more maintainable and use tree-shaking to reduce the total custom visual size (improving visual load time performance).  Notably, we should be able to remove the window adaptor hack -https://github.com/mapbox/mapboxgl-powerbi/blob/master/src/js/mapboxglAdaptor.js - to include specific external libraries.

V3 tools are currently in preview, so don't make this upgrade in production until the tools are in GA.

See docs here - https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/

**Comment by ryanbaumann** [comment]
This is slated for launch in Q2 2019 by Microsoft and would really improve the maintainability and testability of this project.  We should switch as soon as it's available in the next few months.  It should also allow us to reduce the size of the visual, making it load faster.  cc/ @samgehret

**Comment by otravers** [comment]
[Blog post](https://powerbi.microsoft.com/en-us/blog/power-bi-developer-community-april-may-update/) from June 4:

> "We are excited to announce that the new release of powerbi-visuals-tools v3 is now available!"

**Comment by ryanbaumann** [comment]
Migration guide - https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/

**Comment by ryanbaumann** [comment]
Adding this to v1.5 project since it's a huge quality of life improvement, and should make future development much easier and the visual package load faster for all users.

**Comment by ryanbaumann** [comment]
I ran into a number of challenges migrating to PBIVIZ v3 tools - most notably we need to migrate all import syntax for all our files to ES6 / webpack imports.  Going to move the migration work to a separate PR.
