### ISSUE TITLE
[beta 1.4] - Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#283]
Version - branch `beta-1.4` at 8AM PST on 2-3-2018
Action - when cross filtering a map from another visual to Mapbox using a Choropleth layer, the map does not cross filter and I see the following error in the console in development mode.

![](https://cl.ly/a1fb1ebf0c94/download/Image%202019-02-03%20at%208.12.15%20AM.png)

![](https://cl.ly/4ad2b8a8b1b0/download/Screen%20recording%202019-02-03%20at%2008.15.07%20AM.gif)

cc/ @petispaespea @samgehret

**Comment by petispaespea** [comment]
The changes in PR #284 should have fixed this one.

**Comment by ryanbaumann** [comment]
That worked!  Thanks @petispaespea
