### ISSUE TITLE
Cluster layer - feature improvements

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#285]
Currently, in Beta-1.4, cluster layers do not have the same functionality as other layers.  We should make cluster layers have equivalent functionality as circle layers.  Specifically:

1. Cluster layers should support cross-filtering based on user selection in the map (on click, or on draw/lasso select).
2. Cluster layers should show hover/highlight styles.
3. Cluster layers should support diverging color gradients.
4. Cluster layers should show popup values for `unclustered` points that the user selected in the `Tooltip` data column.  EX:

![](https://cl.ly/cf1f716f62d3/download/Screen%20recording%202019-02-04%20at%2008.14.23%20AM.gif)

cc/ @samgehret

**Comment by rbrundritt** [comment]
For the lasso selection, how do you see that working. I see two options:

1. The lasso looks at the cluster coordinate and if it is inside the lasso, then use all contained points to filter. This would likely include individual locations that are the cluster but aren't in the lasso.
2. The lasso looks at original data set and works on that.
