### ISSUE TITLE
Integrating Mapbix style into Power BI

### ISSUE THREAD

**Issue by hamzatransline** [mapbox/mapboxgl-powerbi#289]
Hello, 

I've made rhis  Style    [https://api.mapbox.com/styles/v1/hemzaben/cjsljb2fm5hf01fl93y63rky2.html?fresh=true&title=true&access_token=pk.eyJ1IjoiaGVtemFiZW4iLCJhIjoiY2pycTg5aDZ6MDYxZjQzcGVzdDY3b2RydyJ9.YKP-o2M04tlrDwUBjC2LxQ#9.49/48.7953/2.4078 ](url) with a custom polygon and circles with Mapbox studio and I would like to integrate it in Power BI in order to see the polygons and circles in same time, I tried the choropleth but it shows me only the tiles coressponding but not the whole style ! how should I do please ?

**Comment by ryanbaumann** [comment]
@hamzatransline can you add your custom map style to the "style" setting in the map, then plot the data you'd like to reference in your Power BI data model over the top of your custom map style?  

Here's a tutorial - https://docs.mapbox.com/help/tutorials/power-bi/#change-the-map-style

**Comment by hamzatransline** [comment]
@ryanbaumann  the same what I have done: 
This is my aimed style to show in Power BI 
![style map box](https://user-images.githubusercontent.com/6246566/53477860-e3444e80-3a75-11e9-9de9-20b37ad8a44d.PNG)

And this is the resulat  that I have in power BI 
![power bi style](https://user-images.githubusercontent.com/6246566/53477904-f8b97880-3a75-11e9-9307-9a7821d24424.PNG)

So it shows me only style (couleur of background ) not the points and Labels  notice that Polygons are done with Choropleth map ...

**Comment by ryanbaumann** [comment]
@hamzatransline do you see the same error when using the latest Mapbox Visual for Power BI Beta v1.4?  Here's the custom visual file to try: https://github.com/mapbox/mapboxgl-powerbi/raw/beta-1.4/dist/mapboxGLMap.pbiviz

**Comment by hamzatransline** [comment]
@ryanbaumann  This version works very good !!! I realy like the label too! 
Thank you very much , we love Mapbow ;)

This is the result 
![working version](https://user-images.githubusercontent.com/6246566/53505451-1f969f80-3ab4-11e9-9cbd-586abac01bd2.PNG)

**Comment by ryanbaumann** [comment]
Great news @hamzatransline !  We're currently in the process of releasing v1.4 on the Power BI store, so in ~1 month you should get these same features from the Mapobx Visual on the marketplace.

cc/ @samgehret

**Comment by hamzatransline** [comment]
@ryanbaumann , whene I try to print I lose colors of the Label  look at this pictures scrren shot please : 
![label colors](https://user-images.githubusercontent.com/6246566/53727002-7c58d800-3e6f-11e9-86f6-e87d80a1a1f1.PNG)

and this when I try to print it 
![print label colors](https://user-images.githubusercontent.com/6246566/53727019-8aa6f400-3e6f-11e9-9ef2-5ca985a21525.PNG)

**Comment by ryanbaumann** [comment]
Looks like a bug in the new Legend functionality @hamzatransline we're releasing in v1.4 - good find!  Can you file a new issue for that, with a sample workbook and instructions to reproduce the bug?

Thank you.
