### ISSUE TITLE
Bug Mapbox Labels when printing in power BI

### ISSUE THREAD

**Issue by hamzatransline** [mapbox/mapboxgl-powerbi#292]
Hello, 
I identify a bug when printing in Power BI , Mapbox labels does not show colors 
This is the Screenshot before printing 
![label colors](https://user-images.githubusercontent.com/6246566/53753774-599be300-3eb2-11e9-9a35-91ad0b719dd9.PNG)

And this is  when we try to print in Power BI 

![print label colors](https://user-images.githubusercontent.com/6246566/53753784-615b8780-3eb2-11e9-93bb-db2168b07f6c.PNG)

**Comment by ryanbaumann** [comment]
Cc @samgehret

**Comment by zoltan0803** [comment]
@hamzatransline  you have to enable Background graphics in order to display the colors on the legend.
![image](https://user-images.githubusercontent.com/22682473/142193343-afa935b6-eb94-44b2-87e0-f83970a5e44f.png)
