### ISSUE TITLE
Allow Export to .PDF or .PPTX

### ISSUE THREAD

**Issue by ekozelek** [mapbox/mapboxgl-powerbi#293]
Power BI visuals typically support exporting to a .pdf or a .pptx from the Power BI service. It would be great if the Mapbox visual also supported this. You cannot print & save as a .pdf either. 

![2019-03-07_0842_001](https://user-images.githubusercontent.com/38888740/53964561-342af700-40b5-11e9-8061-08564cfe2a0c.png)
![2019-03-07_0849](https://user-images.githubusercontent.com/38888740/53964992-fa0e2500-40b5-11e9-9f30-6af3ef15d824.png)

**Comment by otravers** [comment]
Only certified custom visuals can be exported:
https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint#limitations

Seems this is in the backlog: https://github.com/mapbox/mapboxgl-powerbi/issues/202

**Comment by DatasupportExpedio** [comment]
This feature is very important to us also.  We work in the mining industry and a lot of our clients dashboards contain maps, but not being able to export to pdf or print is a real problem, Thanks!

**Comment by nawaaugustine** [comment]
Yes this would be nice to have

**Comment by Mike-Honey** [comment]
Very important for my many clients who rely on this visual, notably the Moore Foundation. Please let me know how this can be prioritised.
