### ISSUE TITLE
Mapbox choropleth map disappearing

### ISSUE THREAD

**Issue by cecyarmida** [mapbox/mapboxgl-powerbi#294]
Hi, 
I've created a tileset that I am using on my Choropleth map on Power Bi desktop and everything works good.  But, whenever I change tabs or move between windows the map disappears.  I tried closing/opening PBI destop, publishing it to the PBI service and restarting my machine and still is not there.  Any thoughts on this?

**Comment by samgehret** [comment]
@cecyarmida can you supply a .pbix file or a video of the issue?
