### ISSUE TITLE
Add legend to heatmap layers

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#297]
This was defined as a nice-to-have in https://github.com/mapbox/mapboxgl-powerbi/issues/210, not implemented as part of [1.4](https://github.com/mapbox/mapboxgl-powerbi/projects/4#card-13965331).

**Comment by samgehret** [comment]
@otravers conceptually, what would you want a heatmap to show? It's not exactly clear to me and this is one reason we left it out of the last release. In it's current state, the heatmap only shows density of points. One option is to show how less `metric name` on one side and more `metric name` on the other side.

**Comment by otravers** [comment]
Yeah, I'm guessing something like the way density points look like in Mapbox Studio?
![image](https://user-images.githubusercontent.com/3731532/54958395-54bbd380-4f34-11e9-96b3-5af8d4de47a5.png)
