### ISSUE TITLE
Auto zoom not working

### ISSUE THREAD

**Issue by Erik-Goncalves** [mapbox/mapboxgl-powerbi#300]
When using the map as a tooltip, the autozoom does not work correctly.
![image](https://user-images.githubusercontent.com/37163326/55106566-14806080-50ae-11e9-820d-f8d4f3838999.png)

The right one would be the autozoom go to the location of the selection.

**Comment by samgehret** [comment]
@Erik-Goncalves Are you using a choropleth/area map for your mapbox visual? This part is necessary for autozoom to work. It seems like on the right you just have a base map.

**Comment by Erik-Goncalves** [comment]
@samgehret Yes, I'm using choropleth map and auto zoom work correctly but when I use the same map as tooltip it not working.
![image](https://user-images.githubusercontent.com/37163326/56364323-a61e5200-61c4-11e9-99fe-b93a30b6929c.png)
thanks for your support.

**Comment by ryanbaumann** [comment]
One hypothesis here is that the `tooltip` maps are very small in size (i.e. only one tile), so even when zoomed all the way out features may not be visible at low zoom levels.

@Erik-Goncalves what is the `min zoom` of your tileset used to power your Choropleth map?  Here's an example link to one of my public tilesets, which has a zoom extent down to `z0` https://studio.mapbox.com/tilesets/rsbaumann.iucn-mammals-2018-1/

**Comment by Erik-Goncalves** [comment]
@ryanbaumann, thanks for your support.
I use zoom extent z0 to z22
![image](https://user-images.githubusercontent.com/37163326/56897829-e5bb2880-6a65-11e9-9ac1-57642a24686c.png)
When I make some filters in map and zoom level is modified the tooltip work correctly. but when I do not use filters the auto zoom not work.

**Comment by ryanbaumann** [comment]
> When I make some filters in map and zoom level is modified the tooltip work correctly. but when I do not use filters the auto zoom not work.

This is hard to replicate.  If possible, can you attach a minimumexample of your PBIX workbook from PBI Desktop? If that's not possible, then please add some additional detail explaining how to replicate.

**Comment by Erik-Goncalves** [comment]
I create .pbix could please verify.

[Demo - map autozoom.zip](https://github.com/mapbox/mapboxgl-powerbi/files/3128313/Demo.-.map.autozoom.zip)

**Comment by ryanbaumann** [comment]
Thanks @Erik-Goncalves - I'm able to replicate your issue very reliably on the tooltip page.

When I look at the tooltip view of your map, I can see that your tiles do not contain all polygon features at the low zoom level to fit the bounding box of Brazil in a small tooltip screen.  See figure below with arrows to what look like dropped polygon features at low zoom levels:

![](https://cl.ly/44ddf281f659/download/Image%202019-05-05%20at%209.10.58%20AM.png)

The Mapbox Visual Autozoom feature requires that features to autozoom to are visible at low zoom levels.

To solve your autozoom problem with this dense polygon tileset, I would recommend trying to tile your data using [Tippecanoe](https://github.com/mapbox/tippecanoe), and upload the resultant tileset to your Mapbox account.  Below are the suggested Tippecanoe settings to use to create your dense polygon tileset of the entire country of Brazil from the readme:

`tippecanoe -zg -l "Bricks_Shape-cs5st8" -P -ab -o Bricks_Shape-cs5st8.mbtiles --coalesce-densest-as-needed --extend-zooms-if-still-dropping --generate-ids <my-data-file.geojson>`

If you need to install Tippecanoe on a Windows 10 machine, check out this [tutorial](https://gist.github.com/ryanbaumann/e5c7d76f6eeb8598e66c5785b677726e).

**Comment by Erik-Goncalves** [comment]
Thanks, @ryanbaumann,

I made the tests with Tippecanoe but in cases of the polygon at the low zoom level, it's necessary to render before using the auto zoom functionality.

**Comment by ryanbaumann** [comment]
@Erik-Goncalves just so I understand actions taken and effect on this bug - did you try tiling your source data with the Tippecanoe settings above and confirming that you have AutoZoom issues still in PBI?

**Comment by Erik-Goncalves** [comment]
@ryanbaumann yes, I made the update and the problem persists.
Do you have another Tippecanoe settings for the test ?

Thanks for the support.

**Comment by ryanbaumann** [comment]
> Do you have another Tippecanoe settings for the test ?

There are other options we could test, but they would involve simplifying the geometry more.  Specifically you could use the same Tippecanoe settings as above, but first run your data through MapShaper and use the "simplify" options to make the number of geometry points smaller (but still cleanly edge matched).  The goal there is to make the geometry simple enough to represent in a low zoom tile without dropping features.

**Comment by steved-MarketGrunt** [comment]
Hi, How low must the Zoom level be in order to get it working reliably? I have tilesets with zoom levels of 5-10 for which autozoom is not working. Also, is Mapbox Studio Classic still an option to fix the Zoom extent?

**Comment by otravers** [comment]
I have followed @ryanbaumann's instructions from scratch to install Ubuntu on Windows, install Canoe, and shrink my geojson file to an mbtiles file (114MB to 13MB!), and this solved it for me, as illustrated with the screenshot below:

![image](https://user-images.githubusercontent.com/3731532/61248267-b771ee80-a720-11e9-8324-c56f63536a13.png)

I ended up with these zoom settings: "z0 ~ z4. Data will be visible above zoom 4, but may appear simplified." This type of aggressive shrinkage may not be appropriate for a full-scale map, but I think it makes perfect sense for a tooltip.

**Comment by DNC1971** [comment]
I am getting a similar issue with auto zoom. When I turn auto zoom on it goes to the full layer extent not the area with the data. Here are some pictures to highlight what I am talking about. Any suggestions would be appreciated. 

This is where auto zoom goes to. 

![image](https://user-images.githubusercontent.com/19951619/82458824-bf8d7e00-9ae9-11ea-8600-6f938dec2f71.png)

This is the area of the map that has data and I want to zoom to. 

![image](https://user-images.githubusercontent.com/19951619/82458931-e5b31e00-9ae9-11ea-830a-2e3d6364a33d.png)

Here is the data showing the only part of the map with Australia with data. I have tried setting the DZ code to can not be blank and this does not make any difference. 

![image](https://user-images.githubusercontent.com/19951619/82459072-109d7200-9aea-11ea-8233-905045fa114d.png)

How do I get it to zoom to only the part of the map that has data in it not the full extent of the layer. As I want this map to work for a variety of data I need the layer to have all of Australia in it. Help would be greatly appreciate. Whilst I love the potential of this visual this lack of zoom control is meaning that it does not work for me.
