### ISSUE TITLE
Add ability to customize the legend location and font size 

### ISSUE THREAD

**Issue by kbauhausness** [mapbox/mapboxgl-powerbi#301]
Capturing feedback/feature request from a support conversation:

>Is there any way that I can format the legend on a map on Power BI? for example, location of legend, font size and etc.

>I found the option of turning off legend as you suggested.  Now I can insert an image as  legend for the map. I wish Mapbox could provide ways to customize legend in the future.

cc @samgehret

**Comment by otravers** [comment]
Just saw a collapsible legend on https://openinframap.org/, this would be a great addition:

![image](https://user-images.githubusercontent.com/3731532/68086010-e45c2580-fe25-11e9-955a-7ee8a0ef4c0d.png)

![image](https://user-images.githubusercontent.com/3731532/68086018-fccc4000-fe25-11e9-9bc3-4091440c9339.png)
