### ISSUE TITLE
WMS Layer appears behind elements in base map

### ISSUE THREAD

**Issue by Reduards** [mapbox/mapboxgl-powerbi#302]
Im using Mapbox to display WMS on top of the map. However some elements of the mapbox map appears above the wms layer for example roads and buildings. This is not an admirable function, does anyone know how to get around it so the wms layer is on top. I would also suggest that it should not work this way by standard.

Code:

<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<title>Add a WMS source</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
<style>
body { margin:0; padding:0; }
#map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>
 
<div id='map'></div>
<script>
mapboxgl.accessToken = 'YOURTOKEN';
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/reduards/cjuscu7wh1ci51flehnh8a3yq',
zoom: 14,
center: [17.989726, 59.321486]
});
 
map.on('load', function() {
 
map.addLayer({
'id': 'wms-test-layer',
'type': 'raster',
'source': {
'type': 'raster',
'tiles': [
'WMSLINK?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256'
],
'tileSize': 256
},
'paint': {}
}, 'aeroway-line');
});
</script>
 
</body>
</html>

**Comment by ryanbaumann** [comment]
Hi @reduards - if I understand you problem correctly, this a question about Mapbox GL JS in general, not about the Power BI visual.  Is that correct? 

Based on your GL JS code snip, to put the `wms` layer on top, simply remove the `aeroway-line` before-layer identifier in the addLayer function.

```
<title>Add a WMS source</title> <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script> <style> body { margin:0; padding:0; } #map { position:absolute; top:0; bottom:0; width:100%; } </style>
<script> mapboxgl.accessToken = 'YOURTOKEN'; var map = new mapboxgl.Map({ container: 'map', style: 'mapbox://styles/reduards/cjuscu7wh1ci51flehnh8a3yq', zoom: 14, center: [17.989726, 59.321486] });
map.on('load', function() {

map.addLayer({
'id': 'wms-test-layer',
'type': 'raster',
'source': {
'type': 'raster',
'tiles': [
'WMSLINK?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256'
],
'tileSize': 256
},
'paint': {}
});
});
</script>
```
