### ISSUE TITLE
[Feature] Enhance the search tool to allows coordinate input (reverse geocoding)

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#303]
# Problem

I can't search for a longitude/latitude coordinate pair in the Mapbox Visual for Power BI.  I don't have a "name" to search for in my data set, only the coordinates.

# Solution

Enable a reverse geocoding option in the Mapbox Search widget.  This will be addressed by the features outlined in https://github.com/mapbox/mapboxgl-powerbi/issues/304

cc/ @samgehret 

Ported from https://github.com/mapbox/mapboxgl-powerbi/issues/303#issue-438107545

**Comment by otravers** [comment]
Related: it would be nice to be able to click on the map (probably with a modifier such as Ctrl or Alt) and get the point's coordinates. QGIS for instance has something like this.
