### ISSUE TITLE
Autozoom - limit max zoom level

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#306]
With Autozoom on, the map can zoom more than desired.  For example if external filters mean a single point or small shape is selected, the map zooms all the way to level 22. For many scenarios this is too far - it's hard for the user to understand where in the world they are.

It would be ideal to have a property to limit the max auto-zoom level.

**Comment by ryanbaumann** [comment]
The quick fix would be to default limit max zoom for bbox features to say z16.  The next step would be to make the autozoom max zoom configurable.  I think starting at z16 is a good start and minimal work.

cc/ @samgehret
