### ISSUE TITLE
Increase pixel bbox for autozoomed features

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#307]
With Autozoom on for a Choropleth map, when the data is filtered to a single shape, the autozoom crops the shape too closely for my preference - closer than similar tools e.g. geojson.io. 

It would be good to have a property we can adjust the zoom back a bit from the shape edges.

Here's the same shape in MapBox / Power BI:

![Mapbox shape autozoom](https://user-images.githubusercontent.com/9509644/57504245-14bf7d00-7337-11e9-9bd1-6ac411f725f5.png)

... and in geojson.io:

![geojson io shape autozoom](https://user-images.githubusercontent.com/9509644/57505087-5867b600-733a-11e9-87af-cdc3bd5f9c46.png)

**Comment by ryanbaumann** [comment]
Thanks @Mike-Honey - yes, we can test adding a larger pixel buffer to autozoom bounding box on choropleth shapes.  

cc/ @samgehret

**Comment by otravers** [comment]
I agree, auto-zooming gets so close that you lose a sense of context of what's surrounding the area, and I end up always wanting to zoom out a bit. This not just with choropleth, I have the same experience with other visualization modes.
