### ISSUE TITLE
Maps don't display in cloud service with PBI Desktop May 2019

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#308]
I just published a set of maps from the latest Power BI Desktop version: 2.69.5467.1751 64-bit (May 2019). These maps all load fine in the desktop, but appear blank in the service:

![image](https://user-images.githubusercontent.com/3731532/58039982-463c0380-7b02-11e9-9a7b-fc41e8cf57f4.png)

Here's a couple of things I already did for troubleshooting.

- I tried publishing to a new workspace as well as accessing from a separate browser to rule out any caching issues on the client side.

- I checked that the Mapbox custom chart was up to date, it was since it's showing raster options. I also forced an update manually just in case by re-downloading it from the marketplace.

**Comment by ryanbaumann** [comment]
Thanks for the bug report @otravers. 

> These maps all load fine in the desktop, but appear blank in the service:

Questions:
* Is your PBI service powerbi.com, or a local install of PBI report server?  
* If PBI report server is your service, what report server version do you have installed?
* What type of client machine are you attempting to access the visual from on the service - your laptop, a VM, or other?
* What browser (Chrome, FF, IE, etc) are you attempting to access the visual from on the service?

**Comment by otravers** [comment]
- This happens with the PBI service.
- Accessing from either my Windows 10 local PC or my Azure Windows Server VM.
- Using Chrome, Firefox, or IE11. Interestingly the maps do load properly in Edge.

**Comment by ryanbaumann** [comment]
@otravers do you have the LastPass browser extension installed?  If so, try disabling

**Comment by otravers** [comment]
@ryanbaumann I do. I loaded PBI in a Chrome incognito window without Lastpass, and lo and behold, the maps do load. Well done!
