### ISSUE TITLE
Add legend for data-driven layers from Mapbox Studio

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#313]
In Mapbox Studio one can assign properties such as Fill Color based on data conditions:
![image](https://user-images.githubusercontent.com/3731532/59152823-0d64bf80-8a1a-11e9-9781-18731f8d04d4.png)

It would be nice to be able to surface these up as a optional tileset legend (separate from the PBI data legend), where the author would select whether to feature any of the tileset's data-driven criteria (e.g. building color or pattern by type, traffic condition colors).

**Comment by ryanbaumann** [comment]
Agree, this would be a powerful feature - thanks for the request @otravers .  It hits on a larger category of feature requests involving "using map layers as data sources" in Power BI. 

cc/ @samgehret

**Comment by otravers** [comment]
_"Using map layers as data sources in Power BI"_. YES!

For further illustration purposes, and in an unsuccessful attempt to crash Mapbox/PBI, here's a map with:

1) Data-driven choropleth done in Mapbox Studio, since Mapbox in Power BI won't combine the Choropleth data with other data series. (This comment should earn me passive aggressive points.)

2) Data-driven, color-coded Points of Interest. Speaking of which, I wish I could similarly color the POI icons.

3) Data-driven, color-coded 3D buildings. Incidentally the underlying data seems way less qualified than POIs, but I guess that's OpenStreetMap's problem.

4) Color-coded traffic congestion.

5) Satellite + streets background layers, because at this point, why not?

6) Power BI data layer with Circles, which is the only one that can be explained to the end user via a legend.

![image](https://user-images.githubusercontent.com/3731532/59164169-98f05600-8ad7-11e9-9cea-64881cdc0ceb.png)
