### ISSUE TITLE
Make it easier to switch between raster layers, custom tilesets using expression-based formatting

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#314]
I just tested [raster layers](https://github.com/mapbox/mapboxgl-powerbi/issues/309) using tiles from MapTiler and was impressed with the result. 

Now, the UI for custom map styles and raster layers hard codes a single value for each of these two fields in the visualization's settings:
![image](https://user-images.githubusercontent.com/3731532/59204815-73169000-8b6f-11e9-9882-e7c679fa57ed.png)

![image](https://user-images.githubusercontent.com/3731532/59205980-f9cc6c80-8b71-11e9-8406-a3494e59281a.png)

Power BI is adding [expression-based formatting](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-format-visual-titles) into more and more visuals, to let authors use DAX formulas in visualization settings. My suggestion is to be able to use a DAX formula instead of a hard-coded value in the URL fields pictured above. Said DAX formula would let the author use a disconnected table with a list of URLs, and put these URLs in a slicer to let end users switch custom styles or raster layers.

![image](https://user-images.githubusercontent.com/3731532/59205724-76128000-8b71-11e9-9fbb-2e8294e5a3fa.png)

Below is an example with a choropleth on top of a hillshades raster tileset, this looks real good so why not indulge a bit?
![image](https://user-images.githubusercontent.com/3731532/59204678-203cd880-8b6f-11e9-99a0-20417f6033d5.png)

**Comment by ryanbaumann** [comment]
Great feature request @otravers - cc/ @samgehret

**Comment by otravers** [comment]
Functional examples of what this means for the end user can be seen here:
- https://ahorn.lima-city.de/owm/
- https://owm-inc.github.io/VANE-intro/apps/leaflet-owm.html

![image](https://user-images.githubusercontent.com/3731532/59209055-73ffef80-8b78-11e9-91dc-b3156722729a.png)
