### ISSUE TITLE
Raster URL example is no longer available

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#315]
Mapbox comes prefilled with the following URL in the raster setting:
https://geodata.state.nj.us/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015

Here's what that URL displays:

> "ATTENTION: geodata.state.nj.us services are no longer available. Please use the new maps.nj.gov/geo.nj.gov service URLs"

See this document for further details:
http://njgin.state.nj.us/Arc%20GIS%20Server%20WMS%20URL%20Remapping%20Production%20(Public)%2012-28-18.docx

**Comment by ryanbaumann** [comment]
Thanks @otravers - we'll update the default to `https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015`

cc/ @samgehret
