### ISSUE TITLE
Give control over layer visibility in Power BI

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#316]
In Mapbox Studio we have control over the visibility of each layer, but that's baked in once the custom map style is loaded in Power BI. It would be great to surface this up and make it user-selectable in PBI.

The example below shows that maps can get fairly busy, in this case by displaying bus and metro stops (each in their own layer). I'd want Power BI users to elect which layers to show/hide, though I'd want this to be restricted to the layers of my choosing, (most I'd still want to lock so as not to overwhelm the user with pointless options).

![image](https://user-images.githubusercontent.com/3731532/59221246-cf3fdb00-8b94-11e9-83a4-a1f429157fcd.png)

This request is in the same spirit as https://github.com/mapbox/mapboxgl-powerbi/issues/313 (for data). The overall idea is that things should not be locked in Mapbox Studio, but rather exposed as dynamic properties that remain under the author (and sometimes the reader)'s control once within Power BI.

This is a good illustration of what I mean (I like the grouping idea too):
https://github.com/reyemtm/mapbox-layer-control

![image](https://user-images.githubusercontent.com/3731532/67592467-2efae500-f736-11e9-8547-2062bd800acb.png)

I like how it's implemented behind an expandable-on-hover button to reduce clutter on https://openinframap.org/, they also do this for the legend https://github.com/mapbox/mapboxgl-powerbi/issues/301#issuecomment-549137421.

![image](https://user-images.githubusercontent.com/3731532/68086054-5af92300-fe26-11e9-84c4-fab2b6a3e24e.png)

![image](https://user-images.githubusercontent.com/3731532/68086061-6f3d2000-fe26-11e9-94da-9b1e84310e2e.png)

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by nimamaleki** [comment]
Has there been any update on this feature request? I would like to experiment with the implementation, but I don't have much experience with PBI viz projects. If anyone could give me the general idea of how to do this, I would really appreciate it.

**Comment by hauge404** [comment]
Has there been any updates on this?
