### ISSUE TITLE
Package generation issue

### ISSUE THREAD

**Issue by Tarasteed** [mapbox/mapboxgl-powerbi#318]
Hi,
I want to make some mofification to your existing component, so i'm trying to generate a new .pbiviz.
After updating all the packages and installing a new certificate, i'm stuck with the pbiviz start or pbiviz package with the following error:
![image](https://user-images.githubusercontent.com/23456529/59353070-7140fe00-8d22-11e9-924a-f18373c4f30b.png)
Any ideas ?

Thanks.

**Comment by Tarasteed** [comment]
This problem comes because i tried to update @types myslef. The first problem encountered is : 
`info   Building visual...
 error  TYPESCRIPT  C:/*MyPath*/node_modules/@types/unist/index.d.ts : (31,20) Cannot find name 'unknown'.
 error  TYPESCRIPT  C:/*MyPath*/node_modules/@types/unist/index.d.ts : (40,20) Cannot find name 'unknown'.
 error  TYPESCRIPT  C:/*MyPath*/node_modules/@types/unist/index.d.ts : (97,12) Cannot find name 'unknown'.`

**Comment by captjoemcd** [comment]
Delete the C:/MyPath/node_modules/@types/unist/ folder.  It isn't referenced anywhere and you'll be able to build the package once it is deleted.

**Comment by ryanbaumann** [comment]
This should be solved now in the current master branch.  Make sure to use `npm install -g powerbi-visuals-tools@2.6.0` for now until we release v1.6.0 which will be refactored for v3 visuals tools.
