### ISSUE TITLE
Add support for HTML markers

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#323]
As per the [mapbox-gl documentation](https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) and this [great demo](https://blog.mapbox.com/clustering-properties-with-mapbox-and-html-markers-bb353c8662ba).

![image](https://user-images.githubusercontent.com/3731532/61135176-21736500-a48f-11e9-887c-0947229f95a7.png)

See also [Wildlife Watch](https://labs.mapbox.com/bites/00281/?embed).

![image](https://user-images.githubusercontent.com/3731532/61137688-ffc8ac80-a493-11e9-98c6-04de69cf4490.png)

Related: https://github.com/mapbox/mapboxgl-powerbi/issues/87.

**Comment by otravers** [comment]
I'm excited to see this scoped for 1.5. Is the intent to use markers as the vehicle to deliver a symbol layer as discussed in https://github.com/mapbox/mapboxgl-powerbi/issues/87?

Maybe it's worth elaborating on how this can be implemented?

First, the most important aspect in my opinion is that these markers should be data-driven from the Fields panel, not hard-coded under the Format panel. Prior art for something similar can be done with the Icon field in the Icon Map custom visual from Altius:

![image](https://user-images.githubusercontent.com/3731532/61136217-34873480-a491-11e9-8ecf-b221c3eb9c9c.png)

![image](https://user-images.githubusercontent.com/3731532/61136242-436de700-a491-11e9-8568-0396cb2c9ba3.png)

This likely translates as an extra Marker field between Cluster and Tooltips. In Power Query we would generate the necessary HTML, I've done something similar with the Google Streets API (with the resulting HTML rendered in the HMTL Viewer custom visual).

![image](https://user-images.githubusercontent.com/3731532/61137016-a14efe80-a492-11e9-9c57-e4446d36ee80.png)


Second, it would be nice for the markers to respond to the other relevant fields besides location/lat/long, i.e. color and size.

Third, the mapbox.js demo above shows clustered markers, so it would be great to replicate that capability in Power BI.

Fourth, as discussed in https://github.com/mapbox/mapboxgl-powerbi/issues/87, the marker layer "should contain the same viz class base layers as all other visualizations (visibility, opacity, minzoom, and maxzoom".

**Comment by samgehret** [comment]
@otravers For the MVP of this feature, the basic intent to add your own custom icon to the report. So in addition to showing a circle layer, you could show your own icon, as specified by a latitude and longitude.. At first thought, this would be implemented from the format panel, where you can select from a curated list of icons, or provide your own icon url.  However, I see from your comments that you strongly suggest this be implemented from the Fields panel. Let's perhaps take that conversation offline to flesh it out more.

**Comment by otravers** [comment]
@samgehret this could be done from the Format panel yet remain data-driven (which is really my main functional request here, as opposed to the specific menu location) if you were to implement it similarly to how the new icon sets have been added to table/matrix visuals. This leverages expression-based formatting, which lets you use a DAX measure to define the icon pointers programmatically. 

https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2019-feature-summary/#iconSets

![image](https://user-images.githubusercontent.com/3731532/63203196-f070ec00-c05b-11e9-863e-ae993a078f22.png)

Microsoft also included [sets of curated icons](https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2019-feature-summary/#iconStyles) to that feature so you don't *have* to use a DAX measure, though they were selected with your typical table-based KPIs in mind so I'm not sure you'd necessarily want to re-use them for maps:

**
![image](https://user-images.githubusercontent.com/3731532/63203266-6a08da00-c05c-11e9-9b83-10046a642392.png)
**
![image](https://user-images.githubusercontent.com/3731532/63203277-79882300-c05c-11e9-9e4f-534002abb319.png)

Happy to discuss it further next time we talk.
