### ISSUE TITLE
Legend order of tooltips doesn't match model

### ISSUE THREAD

**Issue by npnigro** [mapbox/mapboxgl-powerbi#324]
The tooltip fields are not sorted in the same order as they're placed in the model. It looks like the order is based on the order they've been added to the map. That's inconsistent with how the standard visualizations behave.

![image](https://user-images.githubusercontent.com/26679240/59895582-ec955600-9399-11e9-9830-be8ccdb5800f.png)

![image](https://user-images.githubusercontent.com/26679240/59895686-61689000-939a-11e9-8bdc-6bc2935cfae8.png)

**Comment by mdc52676** [comment]
Has there been any update to this? How does one change the order? Even if I remove all the fields in the tooltips and add them in the order I want them displayed it does not change the order.  There is even an option on each field to move them up and down and rearrange them using the options and it does not change the order.

**Comment by Hugovdberg** [comment]
I concur the order in which the fields are added does not matter. It appears there is a deterministic order based on the field names, although it is not just alphabetical order. If I rename a field it shows up in a different spot in the tooltip, and if I rename it back it goes back to the original spot. Without knowing the algorithm it might be hard to chose the field names such that they appear in the correct order.

**Comment by martinedoesgis** [comment]
+1 
It seems it is not solved and it's an important feature for the UX of the map. At least being able to put one field as "name" of the popup so it appears on top would be a first step.
