### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by steved-MarketGrunt** [mapbox/mapboxgl-powerbi#325]
Hi there,
Is this the appropriate place to post feature requests for Mapbox for Power BI? If not can you point me in the right direction, please?

**Comment by otravers** [comment]
@steved-MarketGrunt It's the right place. Mapbox staff eventually (time permitting) tags them accordingly once they've reviewed the issue and commented or asked for clarification, as you can see in the list of open issues:

![image](https://user-images.githubusercontent.com/3731532/60198409-82ecd000-980f-11e9-9156-c0c8676f51f3.png)

There's been a good number of past such requests from the community that eventually turned into features, as you can peruse here:
https://github.com/mapbox/mapboxgl-powerbi/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22

I suggest you close this issue as it's not an actual issue they can further act upon. The tidier we as users keep this list of issues, the easier it is for developers to follow up.
