### ISSUE TITLE
choropleth color steps per level

### ISSUE THREAD

**Issue by ArnonErez** [mapbox/mapboxgl-powerbi#326]
When using multiple levels in a choropleth visual and setting the steps for the colors (i.e enabling diverging), the range of values for the different levels can be very different.

I'd like to be able to set the min-center-max values per level.

For example, if I have data in the state, county and block group levels, the max value per block group can easily be lower than the min value for state.

**Comment by steved-MarketGrunt** [comment]
In addition to this may I also add choropleth colour may not always be a numerical value but could also be categorical.  Minimum, middle and maximum may not be sufficient for these cases.

**Comment by ArnonErez** [comment]
> In addition to this may I also add choropleth colour may not always be a numerical value but could also be categorical. Minimum, middle and maximum may not be sufficient for these cases.

For categorical you can control the colors from the Data Color setting (not specific to choropleth).
