### ISSUE TITLE
Enable drillthrough page for current selection

### ISSUE THREAD

**Issue by ArnonErez** [mapbox/mapboxgl-powerbi#327]
Default power bi visuals have an option on right click to drillthrough to another page which was preset to allow that.

This is very useful for reducing the load off a single page when there is a lot points in the top level.

e.g Choropleth showing all counties (optionally with more levels) in a state, which allows to drillthrough to another page with county (or lower level) only long/lat data.

**Comment by otravers** [comment]
For the record, context menu and drill through support was added to custom visuals as of the API 2.2.0 update from November 2018:

- [Announcement](https://powerbi.microsoft.com/en-us/blog/power-bi-developer-community-november-update-2018/)
- [Code sample](https://github.com/Microsoft/PowerBI-visuals/blob/gh-pages/tutorials/building-bar-chart/adding-context-menu-to-the-bar.md)
- [Commit example](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/commit/a19b47a4c635e9f48c6bce526a3e0f5d5e73638f)

**Comment by andymaimoni** [comment]
I'm trying to figure out how to use the lasso or polygon tool to select points and carry those points to another tab. Would that be through the drill through functionality or something else?

**Comment by nnikolasn** [comment]
Hi, is there any update on this request please? I would really need proper drill through functionality! Or at least an answer that this will not get fixed/implemented, so I can look for an alternative solution. Thanks in advance!
