### ISSUE TITLE
Pass GeoCoder Lat/Long Coordinates to Power BI

### ISSUE THREAD

**Issue by steved-MarketGrunt** [mapbox/mapboxgl-powerbi#329]
Hi, I was wondering if it's possible to have the GeoCoder feature not only perform address lookups (which it does now) but also pass the Lat and Long co-ordinates from that look up as variables that Power BI measures could use.

**Comment by otravers** [comment]
This would be useful not just for single point geocoding, but also for polygon selection:

1. Bounds of the currently visible map
2. Bounds of lasso'ed shape

If these values are exposed to Power BI then we can use them to make API calls a la Mapbox TileQuery and its peers. As always, give me the underlying data! :)

Somewhat related in spirit: https://github.com/mapbox/mapboxgl-powerbi/issues/233
