### ISSUE TITLE
Add Functionality for Tooltips / Data Labels to be always visible for Circle and Choropleth Layers

### ISSUE THREAD

**Issue by samgehret** [mapbox/mapboxgl-powerbi#332]

**Comment by otravers** [comment]
This will come handy! Last time I checked, none of Power BI's default maps (ruling out rolling your own in R or Python) support this without using horrible workarounds as described here:
https://mitchellpearson.com/2018/08/19/how-to-add-data-labels-to-maps-in-power-bi/

**Comment by otravers** [comment]
The following ticket is almost a requisite dependency otherwise things will often look raw:
https://github.com/mapbox/mapboxgl-powerbi/issues/211
