### ISSUE TITLE
Querying a different columns for each level of map

### ISSUE THREAD

**Issue by humbertoandme** [mapbox/mapboxgl-powerbi#336]
When making a categorical drill down map it would be useful to be able to load a different data column for each level. 

For example : 
A US States maps that shows Democrat States in blue, Republican States in Red, and Swing States in purple. Then being able to drill down to county level to see Democrat Counties in Blue, Republican Counties in Red and Swing Counties in purple.

**Comment by otravers** [comment]
@humbertoandme There's already a couple of ways you can meet your requirement:

1. Reshape your source data and/or measures so you're working off the granular county-level data (e.g. votes), in which case you'll need a state column to assign counties to the proper state. Here's a demo to show you this works:

![choropleth-drilldown](https://user-images.githubusercontent.com/3731532/61334960-ba8cdd80-a7f9-11e9-9a0e-322a749a6c19.gif)

2. If you really want to need a separate column, you could use either bookmarks (caveat: you won't be able to use the regular drill up-down button), or if you want to do it the "proper" way, you could set up a geographical hierarchy with ISINSCOPE as described here:
https://www.kasperonbi.com/use-isinscope-to-get-the-right-hierarchy-level-in-dax/

The issue I have with using hierarchies with color-coded conditional formatting (e.g. choropleths) is that the Min/Center/Values are hardcoded, and what you put for one level (State) won't work at more granular levels.

**Comment by steved-MarketGrunt** [comment]
Hi @humbertoandme, What you have indicated is possible but takes a bit of mucking around. See below for a similar exercise for the latest AU Federal Elections.
![Video_2019-07-17_185107](https://user-images.githubusercontent.com/42726129/61362528-b0d0ac00-a8c5-11e9-90e1-76054c8dec36.gif)
The secret sauce is as @otravers indicated with the Inscope function in DAX. I've attached a zip file which contains the PBIX file for you to have a look at. Hope it helps.
[AU Election Results.zip](https://github.com/mapbox/mapboxgl-powerbi/files/3401040/AU.Election.Results.zip)

**Comment by humbertoandme** [comment]
Hi Oliver, 

This still doesn't work because my data cannot be converted into granular or numerical data. I'm working on a report for legislators at a national level. 
Some states have "State Wide legalization" of a substance, others have "State Wide Prohibition" of the substance, a third set of states has "Home Rules" meaning they leave it up to the counties to decide. In these states "yellow" there may be " Legalization" counties and "Prohibition Counties". Currently, I'm solving the report with two maps next to each other, but clearly the drill down capabilities would be ideal. 


 
![Capture](https://user-images.githubusercontent.com/46010468/61391523-b6040b80-a871-11e9-97e4-66a69afb4b37.PNG)

**Comment by otravers** [comment]
> This still doesn't work because my data cannot be converted into granular or numerical data

@humbertoandme This is where solution #2 comes into play as the Power BI model will "know" you have set up a hierarchy, which you can then leverage to build dynamic measures instead of hard-coding column references.

FYI I'm developing a re-usable template with US states/counties built in to help bootstrap solutions that meet requirements like yours, feel free to contact me offline (olivier@needlestacker.com) if you're interested.

For the purpose of Mapbox development I suggest you close this ticket as the visual can meet your requirement as is, provided you leverage Power BI's native ETL and modeling capabilities.
