### ISSUE TITLE
Line visualization layer & Isochron

### ISSUE THREAD

**Issue by magmagreza** [mapbox/mapboxgl-powerbi#338]
I'd like to suggest the following features/capabilities for the mapbox visual.

- support for polylines/lines/linestring features; i.e. control the width and color of lines of a custom style inside Power BI - Lack of this capability has severely limited our ability to use PBI+mapbox visual for our applications (surface transportation analyses) - having this feature will open up a new market for mapbox (DOTs, metropolitan areas, etc.)

- "isochron" capability to mapbox visual for PBI; i.e. user can click on a point and isochron contours show up on the map and the points that are within the isochron boundary are highlighted

**Comment by otravers** [comment]
@magmagreza Both features have been discussed for a while though it looks like they're not scoped for the forthcoming 1.5 release:

- https://github.com/mapbox/mapboxgl-powerbi/issues/92
- https://github.com/mapbox/mapboxgl-powerbi/issues/96

For the purpose of leaving things tidy, I suggest you close your issue and comment on the existing ones if you wish to add details to either of them.
