### ISSUE TITLE
Please support projections other than Mercator

### ISSUE THREAD

**Issue by Mike-Honey** [mapbox/mapboxgl-powerbi#341]
Please add support for other map projections besides Mercator. For example I'm working on a project focused on the Arctic region, where Mercator is so distorted it lacks any credibility.

**Comment by otravers** [comment]
The underlying API only supports Web Mercator, so this is not really a Power BI-specific issue. You can track this ticket:
https://github.com/mapbox/mapbox-gl-js/issues/3184

For reference:
https://docs.mapbox.com/help/glossary/projection/

**Comment by Mike-Honey** [comment]
Thanks @otravers , that doesnt look very likely at this point.

I stumbled across this project, which seems to be an attempted workaround for mapbox-gl, but I dont think its useful in this context:
https://www.developmentseed.org/dirty-reprojectors-app/

**Comment by otravers** [comment]
@Mike-Honey I'm with you on Mercator, what with Greenland being almost as big as Africa, but that's what commonly used in web maps, especially for business purposes (Power BI's core audience being business users). I think you can close this ticket for the time being as I don't see this happening anytime soon.
