### ISSUE TITLE
increase max number of points

### ISSUE THREAD

**Issue by djouallah** [mapbox/mapboxgl-powerbi#342]
sorry if it was reported already, mapbox is great product, I know it is a PowerBI imposed limits, but i really need to show 80K points, currently i am using R Visual for that.

is there a workaround please

**Comment by otravers** [comment]
Power BI custom visuals are unfortunately limited to 30K points, see this thread for a possible solution if you're inclined to fork Mapbox and test the discussed workaround: https://github.com/microsoft/PowerBI-visuals/issues/209

**Comment by djouallah** [comment]
thanks @otravers , unfortunately i am not a JS developer, i am not sure how to fork the thing, but would love to use one if available :)

**Comment by charrington2** [comment]
Hi @ryanbaumann 

is there any update on this?
Haven't seen any recent comments on v1.7, is this still open?
The 30k limitation on Power BI is really a killer for us...and after reaching that limit, the points seems to show randomly, no warning or error...this is a really disturbing user experience.

Thanks for any comments or help...any workarounds?
Christian
