### ISSUE TITLE
Can't contribute following the doc

### ISSUE THREAD

**Issue by Niiko** [mapbox/mapboxgl-powerbi#347]
Hi,

I encounter some problems when i want to contribute to the project.

I can't initialize and "npm start".

So far, there is a typo in documentation too, command "build-turf" is "turf-build".

For npm install, here is the log (there is no package-lock.json)

[npm_install.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620463/npm_install.log)

I had to manually install two libs

`npm install --save eslint  browserify`

[npm_install_two_libs.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620464/npm_install_two_libs.log)

Here is the log of turf-build

[npm_run_turf.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620465/npm_run_turf.log)

Here is the log of npm start, can't find .api/1.13.0.

[npm_start.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620466/npm_start.log)

In fact, in tsconfig.json, he is in "".api/v1.13.0/PowerBI-visuals.d.ts", but the file is "node_modules/powerbi-visuals-tools/templates/visuals/.api/v1.13.0/PowerBI-visuals.d.ts"

so i re-run npm install after the change, or pbivizstart.

[pbiviz_start.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620467/pbiviz_start.log)
[last_try.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620462/last_try.log)

But now, i have "The "path" argument must be of type string. Received type undefined"

What's the correct way to get things working ?

Also, i'm under windows 10 x64, some extra info.

[pbiviz_info.log](https://github.com/mapbox/mapboxgl-powerbi/files/3620502/pbiviz_info.log)

**Comment by ryanbaumann** [comment]
Sorry for the late reply @Niiko - can you try building using the latest `master` branch since we just released v1.5.0?  Please be sure to use `npm install -g powerbi-visuals-tools@2.6.0` for now until we upgrade the library to PBIVIZ v3+ in release 1.6.0
