### ISSUE TITLE
Add ability to customize stops in legend

### ISSUE THREAD

**Issue by dpdiliberto** [mapbox/mapboxgl-powerbi#348]
Currently, Power BI only allows for 6 legend stops that are automatically defined and doesn't provide the ability for customizing these stops. This request is to provide users with the ability to customize the number of stops, and to customize the interval ranges that are used for these stops.

**Comment by otravers** [comment]
The best way to do this would be to support Format by Field value and Format by Rules, as opposed to hard-coding stops, as discussed here:
https://github.com/mapbox/mapboxgl-powerbi/issues/266

**Comment by ZiZasaurus** [comment]
Two additional requests for legend customization include the ability for users to customize sorting and  control text size, sort order, position, visibility, etc.

**Comment by DatasupportExpedio** [comment]
Agree with above, would be great to be able to customize legends - sorting is a big problem and with changing data cannot seem to get this to work in any consistant way (alphabetically, with sortorder column etc)
