### ISSUE TITLE
Source and Destination (Latitude and Longitude)

### ISSUE THREAD

**Issue by adild2k** [mapbox/mapboxgl-powerbi#349]
I would like to know how to use the source (latitude and longitude) and destination (latitude and longitude) specifically of delivering from the stores like KFC, McDonalds and Pizza Hut? There is no provision in the "Field Well" where i can use the source (latitude and longitude)? Am i missing something?

![image](https://user-images.githubusercontent.com/54456156/66300439-59f7d300-e906-11e9-9c7c-63c2eafa4dfd.png)

**Comment by otravers** [comment]
@adild2k Can you clarify what you're trying to accomplish? Are you trying to map routes between two points? Routes are not currently supported in the Mapbox visual for Power BI.
