### ISSUE TITLE
Search Toolbar

### ISSUE THREAD

**Issue by adild2k** [mapbox/mapboxgl-powerbi#350]
Hi Team,

Is there a way to "hide" the "Search Toolbar" in the component using the "Circle" segment in the "Format" well? Sometimes its really get difficult to show the points as its overlay on those points.

Regards

Adil

![image](https://user-images.githubusercontent.com/54456156/66304046-6af81280-e90d-11e9-9afc-f75cbd41b048.png)

**Comment by otravers** [comment]
@adild2k 

Yes, turn the Geocoder off in the visual's Format panel:
![image](https://user-images.githubusercontent.com/3731532/66512234-e218dc80-eaae-11e9-86d3-4022c58ca599.png)

Please close this issue to keep things tidy for the developers.
