### ISSUE TITLE
Allow for image pinning to map visualization 

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/mapboxgl-powerbi#357]
Would it be possible to implement a feature allowing users to pin images to their map visualization? One customer in particular requested this feature, as sometimes the map resolution available is not enough (too blurry), so they would rather work with a picture (of a map or of the site they're working on). Here is the [Zendesk ticket ](https://mapbox.zendesk.com/agent/tickets/73238)for reference.

**Comment by otravers** [comment]
You can sort of do this with the Raster layer, but that's probably 100x more work that what you have in mind.
