### ISSUE TITLE
Having a Selection on a Mapbox Visualization Persist Across Tabs of a Report

### ISSUE THREAD

**Issue by indiana-nikel** [mapbox/mapboxgl-powerbi#358]
Hello,

I'm looking to use the Mapbox Lasso Select tool as type of slicer but I can't seem to have it behave accordingly. What I'm attempting to do is be able to select a group of latitude/longitude pairs on the map and have a matrix with the same information slice down the what the user has selected.

On the same tab, this works beautifully. However, I'd like the selection on the Mapbox visualization to persist across tabs of the same report. Currently, the selection resets when another tab is selected.

Is there any way I'm able to accomplish this in the current release of this visualization and/or am I missing something?

Best,
Indiana

**Comment by ArnonErez** [comment]
What you are asking is currently not possible in PBI with any kind of visual except slicers when they are synced between pages (or by using a filter on all pages).

Any visual that is not a slicer works very differently regarding the filtering of other visuals.
In PBI it's called cross-filtering or cross-highlighting depending on specific visuals, your general settings and on a per visual basis with the _Edit Interactions_ button in the format tab.

Any selections you make on visuals are reset whenever you switch tabs or choose a different selection without holding ctrl unless it's a slicer.

Depending on your need you might be able to work around the problem by using the drillthrough functionality.
After choosing the points you want, you can find some field for which drillthrough would make sense and on the drillthrough page make sure that the _Keep all filters_ toggle is active.
Then, when you use the drillthrough, the page will be filtered to only your selection (along with any other filters/slicers/selections currently active).

I hope this helps a bit.

**Comment by indiana-nikel** [comment]
I see, this makes sense. I was trying to do a bit too much with one Power BI component (have a visual be a filter while filtering on a visual). The drillthrough recommendation worked perfectly for what I was trying to build functionality for. I appreciate the quick feedback and helpful recommendation!

I do have two follow-up questions:

1. When drilling through, I have to right-click on my Matrix values rather than the Mapbox selection to have a menu appear. Is there functionality on the Mapbox visualization itself for drilling through that I might be missing?

2. When drilling through, the report swaps to another tab. When using the back-arrow that Power BI drops in, my selection disappears (from the selection being a cross-filter rather than a slicer). Is there a way to have Power BI retain memory of that specific cross-filter? This might be a more of a general Power BI question than for Mapbox itself.

**Comment by otravers** [comment]
Related feature request: https://github.com/mapbox/mapboxgl-powerbi/issues/327
