### ISSUE TITLE
Map Tiles do not Load on iOS devices 

### ISSUE THREAD

**Issue by pjleonard37** [mapbox/mapboxgl-powerbi#359]
When creating a dashboard using Microsoft PowerBI with embedded Mapbox map the base map does not load on iOS devices. There is no issue when opening the dashboard through the desktop, but when the application is loaded on iPad and iPhone the map tiles do not appear. Some of the overlaid data loads, but the Mapbox style does not load at all. This may be an issue with Safari Mobile directly. 

Desktop:
![desktop](https://user-images.githubusercontent.com/7976026/68718769-3ca6cc00-0578-11ea-8b36-9cb6a6066f25.png)

iOS:
![iOS](https://user-images.githubusercontent.com/7976026/68718789-44667080-0578-11ea-8208-167881342048.png)

Version:  iOS 13.1.2
Error message: none

**Comment by otravers** [comment]
This may not be an acceptable solution for you, but have you tried through the Power BI iOS app?
