### ISSUE TITLE
Zoom not properly for country Fiji

### ISSUE THREAD

**Issue by rexfan79** [mapbox/mapboxgl-powerbi#360]
Hi,

I am using Mapbox for PowerBI and I found a bug for country Fiji, when slice by Fiji, the map did not zoom correctly like other counties. Could you do a check and debug for this?

Thank you.

**Comment by otravers** [comment]
So that others can reproduce the issue, it would help if you can upload a PBIX file and/or link to a public dashboard with this problem.
