### ISSUE TITLE
Certification of visual

### ISSUE THREAD

**Issue by whoint** [mapbox/mapboxgl-powerbi#361]
Hi, the Mapbox visual in Power BI meets a number of use cases but uncertified visuals do not have all the functionalities.  Primarily, only native and certified visuals can be printed.  May I request for mapbox visuals in Power bI to be certified?  Prints are still widely used by our user base.  Thank you.

**Comment by otravers** [comment]
Duplicate of https://github.com/mapbox/mapboxgl-powerbi/issues/202
