### ISSUE TITLE
Add support for WMTS

### ISSUE THREAD

**Issue by FrieseWoudloper** [mapbox/mapboxgl-powerbi#362]
The official (open data) raster map of the Netherlands is only available as WMTS, not as WMS. Every Dutch government organization is legally obliged to use this map. So I would really like the Mapbox Visual to support WMTS.

**Comment by ryanbaumann** [comment]
Thanks for the issue @FrieseWoudloper - we will absolutely consider this.  

Currently Mapbox GL JS (the SDK that renders the map visual in Mapboxgl-powerbi) does not support WMTS as a source data format - internally it only supports z/x/y coordinate system tiles.
