### ISSUE TITLE
Worldmap showing duplicate continents. How can I solve this? 

### ISSUE THREAD

**Issue by emilevanlier** [mapbox/mapboxgl-powerbi#366]
In Power BI I use the Mapbox visual to show a worldmap. the worldmap has been created by Mapbox studio. The power bi report is embedded into a website. 
A problem my customer just mentioned, is that at their workplace they see double continents. (see attachment) 

What do I need to do in Mapbox Studio to make sure that initially (when the report loads) the worldmap is shown correctly? 

![worldmap1](https://user-images.githubusercontent.com/50400191/73453077-8a5af580-436b-11ea-825c-b983a82330bb.jpg)

**Comment by steved-MarketGrunt** [comment]
I'm not sure if this will help or not but, in Choropleth settings you can change the auto-zoom settings. I'd suggest changing the Min Zoom to ~5 to see if that fixes the issue.

**Comment by emilevanlier** [comment]
Hi, thanks for your advice. I tried this, but unfortunately is not the solution.
I think it’s something what needs to be set in Mapbox studio, but I don’t know how to do it.

When you create a new ‘Basic’ layer in Mapbox Studio, I see that you can zoom this far:
[cid:image001.png@01D5DA97.047522C0]

In Power BI visual you can zoom out to the max ( same as the image above ) and that doesn’t look good for our customers.
I want to be able to set a max. zoom level so that you cannot zoom further than this:
[cid:image003.png@01D5DA97.047522C0]

So, what I tried in Mapbox Studio is to zoom in, so that you see a correct worldmap ( see above).
And in the settings, select ‘Lock’, hoping that this would lock the zoom-level.

[cid:image004.png@01D5DA97.047522C0]

I saved the layer, and used this for the Power BI visual. But then it’s still possible to zoom in to the maximum.
So this didn’t solve the problem unfortunately.
[cid:image005.png@01D5DA97.047522C0]

This is the max. zoomlevel I want to see, how can I do this?
[cid:image006.png@01D5DA97.047522C0]


Met vriendelijke groet / Kind regards,​
​
​CRM Partners​ BV
Emile van Lier
Consultant

Emile.van.Lier@crmpartners.com<mailto:Emile.van.Lier@crmpartners.com>
+31 (6) 22180919<tel:+31%20(6)%2022180919>

[CRM Partners Website]<https://www.crmpartners.com/>
[Youtube]<https://www.youtube.com/user/CRMPartnersnl>
[LinkedIn]<https://www.linkedin.com/company/crm-partners>
[Twitter]<https://twitter.com/crmpartnersnl>
[Facebook]<https://www.facebook.com/CRMPartners/>

**Comment by steved-MarketGrunt** [comment]
I've read through other threads here and it looks like this feature is on the "to-do" list for V1.6(?). 

Also, one of the threads indicated that if one of the data points has a 0,0 co-ordinate the map will default to the max zoom. It might be worth checking to see that all layer references are correctly related back to your PBI dataset.

**Comment by emilevanlier** [comment]
Hi,
Thanks for your response.
Do you have any idea when v1.6 is planned?


Met vriendelijke groet / Kind regards,​
​
​CRM Partners​ BV
Emile van Lier
Consultant

Emile.van.Lier@crmpartners.com<mailto:Emile.van.Lier@crmpartners.com>
+31 (6) 22180919<tel:+31%20(6)%2022180919>

[CRM Partners Website]<https://www.crmpartners.com/>
[Youtube]<https://www.youtube.com/user/CRMPartnersnl>
[LinkedIn]<https://www.linkedin.com/company/crm-partners>
[Twitter]<https://twitter.com/crmpartnersnl>
[Facebook]<https://www.facebook.com/CRMPartners/>

**Comment by emilevanlier** [comment]
Hi, in the latest comments it was mentioned that a solution would (most likely) be provided in release v1.6.  

Can you please inform us when this is planned, so that I can give at least an update to my customers? 

Thank you!
