### ISSUE TITLE
.KML Functionality

### ISSUE THREAD

**Issue by Rand3rino** [mapbox/mapboxgl-powerbi#368]
Hi MapBox team,

I’m working on a project that requires overlaying natural disasters over data points and using those shapes to select my data. The image below is using .kml file from [https://www.gdacs.org/] and visualized with the ArcGIS tool in Power BI. I tried uploading the .kml to MapBox Studio and then pushing it to Power BI but I can’t slice the data with this method. Is this something that can be developed?

<img width="299" alt="Esri Gdacs" src="https://user-images.githubusercontent.com/37269917/74465102-c9587300-4e62-11ea-9003-54967829edd7.PNG">

Thanks,

Randy

**Comment by steved-MarketGrunt** [comment]
Hi @Rand3rino, 
I did this a long time ago and I'm not sure if I remember all the steps completely but, I think this will get you in the ballpark.
Firstly, I created ESRI shapefiles in QGIS, I imported the shapefiles as tilesets in Mapbox. 1 tileset was the boundary file, while the other was point data converted to a boundary file (a QGIS function).  You then follow the drill down choropleth procedure with the boundary tileset as you upper layer and the point boundary as your second layer.

Your upper-level table (the boundaries) will require to filter your lower level (points) data in Power BI.

I hope this helps.
