### ISSUE TITLE
Mapbox map not exporting to PDF, Powerbi Version: 2.78.5740.981 64-bit

### ISSUE THREAD

**Issue by albericipereira** [mapbox/mapboxgl-powerbi#370]
Dear MapBox team, I have been using MapBox visual in my PowerBI reportes since august 2019, however, since the PowerBI version released in january, the Mapbox maps are not exported to PDF formats. I am not sure of the origin of the issue (PBI or Mapbox viz) but decided to contact you, in case you can help to fix the issue.

**Comment by otravers** [comment]
This is not a bug, Mapbox needs to certify their visual first:
https://github.com/mapbox/mapboxgl-powerbi/issues/293
