### ISSUE TITLE
issues tooltips in MApbox Visual for Power BI with  values 0

### ISSUE THREAD

**Issue by lcruzbi** [mapbox/mapboxgl-powerbi#372]
when I use the mapbox component for power bi in choropleth mode and also add a measure such as tooltips, which is known to take the value 0 for several cases, it is not showing such value but it shows the text "null". It occurs with all measures that take a value of "0".
![powerBI - mapbox - tooltips - mode choropleth](https://user-images.githubusercontent.com/62440493/77188906-8159eb00-6ab5-11ea-8501-8f4f1ada1685.jpg)

**Comment by UlfenB** [comment]
BLANK() is also rendered as "null".

**Comment by davidfombella** [comment]
I have the same issue, any updates?

**Comment by mate-turi** [comment]
Bug will be handled in the new project. Your reported bug can be found [here.](https://github.com/starschema/mapboxgl-powerbi/issues/34)
