### ISSUE TITLE
Mapbox Doesnt Render in Lastest Power BI Update

### ISSUE THREAD

**Issue by JayDoc386** [mapbox/mapboxgl-powerbi#374]
Mapbox 1.5.0 does not seem to be working properly in displaying maps consistently with the May update of Power BI Desktop.  It shows occasionally and then just goes to nothing.  It also no longer shows properly in Reports in the Power BI Service.

**Comment by mdc52676** [comment]
I am having the same issue recently.  Has there been any solution?
