### ISSUE TITLE
No "Viz Settings" under "Format"

### ISSUE THREAD

**Issue by francesco1119** [mapbox/mapboxgl-powerbi#376]
Is this repository deprecated? 

On latest Power BI (Version: 2.83.5894.961 64-bit (July 2020)) your map doesn't integrate.

I'm following your [instructions ](https://docs.mapbox.com/help/troubleshooting/integrate-mapbox-visual-with-power-bi/)but I don't see any` Viz Settings` under `Format `

![immagine](https://user-images.githubusercontent.com/3397477/89672591-336b4580-d8e5-11ea-93da-89c7972dfec8.png)

**Comment by francesco1119** [comment]
Plus the box has broken links for the images:

![immagine](https://user-images.githubusercontent.com/3397477/89672705-69a8c500-d8e5-11ea-9be0-c125cdbd79a2.png)

**Comment by ArnonErez** [comment]
I'm not sure what the proper behavior is, but if you put any field in the map then the option should show.
At least it works for me
