### ISSUE TITLE
3 Level Drill down on Choropleth Map, Issue with initial world zoom

### ISSUE THREAD

**Issue by adamweston** [mapbox/mapboxgl-powerbi#377]
Hi folk

New to Map Box, but what an awesome product.  I have a three level choropleth map with drill down which works really well.  The issue arises when you drill down with the auto zoom functionality turned on.  Rather than zooming in, it seems to pan out to the world and then zoom in.  Unable to set the viewpoint throught the Power Bi addin, so are there any workarounds? Video link is https://drive.google.com/file/d/15DwCtYokD9HVfx_OnqUvjtE1IZP-2eQk/view?usp=sharing.

Best regards

Adam

**Comment by dizayee** [comment]
I am facing the same. Did you find any solution for this? I deactivated the auto-zoom for now.

**Comment by elfeki9** [comment]
Any updates regarding this issue ?? 
I am facing the same problem :/
