### ISSUE TITLE
Choropleth: Aggregation function alternatives

### ISSUE THREAD

**Issue by galapah** [mapbox/mapboxgl-powerbi#381]
Hello,

I am visualizing hierarchical geo-demographic data from [Eurostat](https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts#nuts21) with Mapbox Choropleth.

In the table, I provide data for the bottom layer and the visual calculates the aggregated numbers for the upper layers. The problem is that it sums the values. Since my numerical column is on the relative scale (%), summing does not make sense.

Can I specify another aggregation function (e.g. Mean)?

Best,
Jan

**Comment by Arthur-Ni** [comment]
Hi galapah,
I'm trying to do something similar.
Can you explain to me how you use the multiple layers (type of layers on different levels), and how you get the visual to sum when zooming out?

**Comment by UlfenB** [comment]
It's possible to use your own DAX measures and implement your own aggregation functions.
