### ISSUE TITLE
Mapbox Visual Legends in Power BI 

### ISSUE THREAD

**Issue by DatasupportExpedio** [mapbox/mapboxgl-powerbi#386]
Hi, Is it possible to add some customisation to the legends auto-created in PowerBI.  Eg Sort order (essential and seems random at the moment), text size etc, Thanks

**Comment by DavidNphe** [comment]
I agree. Customisation of the legends would be a valuable addition.

**Comment by arefeenshamsuzzoha** [comment]
Agreed with this. I had to turn off the auto-legend and create one from scratch.
