### ISSUE TITLE
Null values are not ignored when rendering

### ISSUE THREAD

**Issue by kevpye-fabdata** [mapbox/mapboxgl-powerbi#391]
I've just started testing mapbox as an alternative to using ESRI Arcgis maps. I'm having an issue with null values however in the lat and long. The lat and long fields are marked as lat / long in our power bi model and they do contain nulls. It seems however they are not being ignored and are rendered in the middle of the sea which causes the maps to zoom out and not be centered as they should be. These nulls do not affect other power bi visuals from either MS or ESRI.

The problem affects both the clustered maps as well as the circle maps. I found a closed issue where this problem was reported and closed as fixed so I don't know why this is happening - maybe a regression? The issue was #62 and the pull request was #64 

Here is a screen grab from the clustered:

![mapbox1](https://user-images.githubusercontent.com/82941745/118627875-fc0abd00-b7c3-11eb-9443-d64545999b2f.PNG)

And the same from the circles:

![mapbox2](https://user-images.githubusercontent.com/82941745/118627920-05942500-b7c4-11eb-8ff4-8be81559adbd.PNG)

I am using mapbox v1.5.0 installed from the marketplace and the latest powerbi desktop - 2.93.641.0 64-bit (May 2021)

Thanks in advance

**Comment by kevpye-fabdata** [comment]
A simple fix is to use the filters applied the visual in power bi to not include any blanks - just FYI. But wasn't sure if this was a bug / regression based on the issue / pull I linked in my main comment

**Comment by rhabb999** [comment]
Believe you can also set the default for a ‘null’ so It doesn’t land in the middle of the ocean.

e.g. if in the UK set it for central England, US set for central US etc

**Comment by kevpye-fabdata** [comment]
@rhabb999 This could be done but the problem with setting such defaults - I assume - would be that the rows would then be counted in the clusters etc which is undesirable in our case. I personally feel the maps should behave - by default - the same way as other power bi maps - which is nulls or blanks are excluded / ignored without additional configuration. If setting defaults, such as your suggestion, works for a particular project that design choice should be up to the project. Just my 2 cents.
