### ISSUE TITLE
Problem with shape size when single data point selected

### ISSUE THREAD

**Issue by cdm784** [mapbox/mapboxgl-powerbi#394]
We use mapbox with BI and we have a complex page that uses location data to show size of circles by counting status hours. When no one data point is selected the shapes show the correct size and location based on our location table. When we select a single location though from a slicer in BI all shapes disappear and nothing is shown on the map. If we take the status hours out from the size field all the points show up and then we select a single point from the slicer and it shows then. 

To break it down further - if we have a field driving the size of the dot on the map when you make a selection from a slicer all dots disappear from the map. If you don't have a field driving size then dots work.

Any thoughts?

**Comment by mattdlewis** [comment]
sounds the same problem as this, scheduled for update in 1.6.0? https://github.com/mapbox/mapboxgl-powerbi/issues/259
