### ISSUE TITLE
Calculation group format string breaks visual

### ISSUE THREAD

**Issue by carlhodder** [mapbox/mapboxgl-powerbi#396]
If you add any format string to any calculation group item within the tabular cube this visual will break (becomes completely blank).

Even if the format string is 'SELECTEDMEASUREFORMATSTRING()'

Fairly quick to reproduce if you use the Tabular Editor:

1. Create calculation group
2. Add calculation item
3. Confirm everything still functions
4. Add format string to calculation item
5. Watch visual turn blank
6. Remove format string, and see visual function again

**Comment by UlfenB** [comment]
I also have this problem. Would be very nice if it could be fixed since dynamic format string (by using calculation groups) is very useful!

**Comment by tenfingerseddy** [comment]
I also am experiencing this on a government project and it will likely result in not using Mapbox visual for a public facing report.

**Comment by mate-turi** [comment]
Bug will be handled in the new project. Your reported bug can be found [here](https://github.com/starschema/mapboxgl-powerbi/issues/25).
