### ISSUE TITLE
Mapbox visualisation not working for embedded solution

### ISSUE THREAD

**Issue by frederikboligportal** [mapbox/mapboxgl-powerbi#404]
The Mapbox visual in Microsoft Power BI Stopped working in Power BI Embedded solutions today, wednesday 6th of july.
The Visual works fine Power BI Desktop and Power BI Service, but doesn't show in Power BI Embedded solutions. 

In devtools i get these issues: 
![image](https://user-images.githubusercontent.com/95859706/177525123-27ecd230-1b33-4478-a5fa-cb7c95aeec4e.png)

Mapbox is a primary navigation tool affecting multiple customers.

**Comment by TonyGaul** [comment]
Same issue with me, PBI Embedded Australia Southeast

**Comment by mBoegebjerg** [comment]
I can confirm that the visual works again in our embedded solution.
