### ISSUE TITLE
assign position of legend

### ISSUE THREAD

**Issue by rgerecke-ops** [mapbox/mapboxgl-powerbi#406]
it's probably infeasible to be able to specify a position for the legend box, but i would love to be able to at least assign it to a different corner--top left instead of bottom right, for example.

**Comment by mate-turi** [comment]
Hello @rgerecke-ops,
This repository is deprecated. Please follow the new repo: https://github.com/starschema/mapboxgl-powerbi/issues/32

As you can see, we are working on this requirement in the new version which will be published very soon.
Regards,
Máté

**Comment by rootsmusic** [comment]
@mate-turi  When this repo was deprecated, the other authors who had opened issues weren't updated about the repo's change in support status.  They should be informed about the deprecation, so they can close their issue here and open an issue in starschema's repo (if their issue is still applicable).
