### ISSUE TITLE
Docs on Mapbox.com

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#56]
- [x] Update readme to have a release process that includes updates on Mapbox.com docs
- [x] Publish initial docs 
    - [x] Docs Copy @noemiwalzebuck @ryanbaumann
    - [x] Inital doc on mapbox.com/help @colleenmcginnis

**Comment by ryanbaumann** [comment]
Mapbox Visual for Power BI tutorial slated to be released on Monday 2/12

**Comment by vitaly-livshits** [comment]
@ryanbaumann, is there an updated ETA that you can share? Thanks.

**Comment by ryanbaumann** [comment]
@vitaly-livshits yes, we have docs staged but have been holding them until the visual is approved for the Microsoft Office Store.  That's in progress.

While it's in progress, let me see if we can publish the docs so users can get started right away.

**Comment by vitaly-livshits** [comment]
@ryanbaumann Yes, that would be great. We are perfectly fine with referencing draft document versions for now.

**Comment by ryanbaumann** [comment]
Great!  We'll get docs up this week @vitaly-livshits.  I'll link here when live.

**Comment by ryanbaumann** [comment]
Docs are live @vitaly-livshits https://www.mapbox.com/help/power-bi/.  Added to Readme here ->
