### ISSUE TITLE
Map zoom out if there are any points with the blank information in latitude or longitude

### ISSUE THREAD

**Issue by mendezke** [mapbox/mapboxgl-powerbi#62]
After any modification the map seems to zoom out if there are any points with the blank information in latitude or longitude.
![2018-02-16_1041](https://user-images.githubusercontent.com/18187394/36304830-655e1ac8-1311-11e8-817a-d8c8f3ddf608.png)

![mapbox_powerbi](https://user-images.githubusercontent.com/18187394/36305281-3c785590-1313-11e8-8487-a31c3111f001.gif)
[Collisions_blank_data.xlsx](https://github.com/mapbox/mapboxgl-powerbi/files/1731105/Collisions_blank_data.xlsx)

**Comment by ryanbaumann** [comment]
Thanks for the bug report @mendezke!  Adding this as a bug to fix - we should not include null longitude/latitude points in the map zoom bounding box calculation.

**Comment by tmurray400** [comment]
This still seems to be an issue in the latest version.

**Comment by ryanbaumann** [comment]
@tmurray400 can you provide an example workbook for us to replicate the issue?

**Comment by tmurray400** [comment]
@ryanbaumann Here is a link to a sample workbook.
https://nexgenpss0-my.sharepoint.com/:u:/g/personal/tim_nexgenpss_com/EVxEwfe5q_pNjkBxdzc-U60BpBwJMYfz_mg8SDnKbQAivw?e=Tt1v0i

**Comment by ryanbaumann** [comment]
Thanks @tmurray400.  Do you have values of 0 or null in your longitude latutde columns?

Cc/ @samgehret

**Comment by tmurray400** [comment]
@ryanbaumann they are blank values in a decimal field categorized as Latitude or Longitude.
![image](https://user-images.githubusercontent.com/45207678/48789379-e1bafb80-ecba-11e8-9a3c-75193c88a17f.png)
