### ISSUE TITLE
Enable vector tile sources using data-join for all layer types (circles, fill, lines, extrusions)

### ISSUE THREAD

**Issue by PedroRiveraTorresMoir** [mapbox/mapboxgl-powerbi#69]
It'd be great to have the ability to select a tile layer, and based on matching Object ID with PowerBI's dataset, perfom a Data-Join, where the Polygons, Lines and Points of the chosen Vetor Tile are colored based on a specific value of the Dataset.

Would this be possible in the current planned release? I believe it's a different type of Data-join than the one contemplated by the choropleth boundary option. The choropleth option is more akin to a TopoJSON layer with heatmap capabilities than a Vector Tile with Data-Join capabilities for all feature types. Both useful, but different use cases.

Thanks.

**Comment by ryanbaumann** [comment]
@PedroRiveraTorresMoir To make sure I understand your question - you'd like to

1. Join data in your Power BI data model to Vector Tile features
2. Render the joined data for more than just a `fill` layer type, in order to create circle, line, or fill map visualizations.

Is that correct?

**Comment by PedroRiveraTorresMoir** [comment]
Precisely!

From what I could tell this would be a different type of visualization. One whose core focus was Data-Joins between PowerBI datasets and Mapbox Vectors. Am I right? If so, is this in the roadmap?

Thanks again

________________________________

**Comment by ryanbaumann** [comment]
@PedroRiveraTorresMoir 

Data-Joins are on the short-term roadmap, absolutely - however, we were mainly scoping them for Choropleth and Hexbin / Fill-Extrusion 3D visualizations.  But linestring visualizations make sense here too, and we could expose that as an `arc` or `line` visualization layer type supporting data-joins.

Do you have a use case for point visualization using the data-join technique?

**Comment by otravers** [comment]
I track logistical flows (tons of a specific commodity) between countries/ports for one of my clients, and would love to be able to do something like these:
- http://bl.ocks.org/yellowcap/03cd4a6c72f661377f7e
- http://www.sankey-diagrams.com/tag/map/

There used to be a custom PBI visual to generate Sankey maps but it was very buggy so we stopped using it. It never made it to the Office store and I can't find it anywhere now. (There's still a Sankey diagram custom visual that we do use, but it's not a map.)

Similarly to my comment about 3D choropleths, here I'd be interested in using arc/line width for one measure and arc/line color for another (like a variance of the first measure). Also line direction would matter, e.g. load ports to discharge ports to ideally these arcs/lines could look like arrows with a start and an end.

If you can add a Time play axis (ArcGIS has one) on top of all this, then minds will be blown for sure :) Imagine the following motion map, rendered as a 3D choropleth with data-encoded arcs, all based on your Power BI measures! The late Hans Rosling would sure love this.
https://www.google.com/publicdata/explore?ds=ml9s8a132hlg_&ctype=m&strail=false&nselm=s&met_s=minimum_wage&fdim_s=currency:eur&scale_s=log&ind_s=false&met_c=minimum_wage&fdim_c=currency:eur&idim=country:lu&ifdim=country&pit=1293840000000&iconSize=0.5&uniSize=0.035&yMax=58.5924685&xMin=-8.2391222&xMax=35.43979471&mapType=t&yMin=35.902422#!ctype=m&strail=false&bcs=d&nselm=s&met_s=minimum_wage&fdim_s=currency:eur&scale_s=log&ind_s=false&met_c=minimum_wage&fdim_c=currency:eur&scale_c=lin&ind_c=false&idim=country:lu&ifdim=country&hl=en_US&dl=en_US&ind=false

**Comment by PedroRiveraTorresMoir** [comment]
Oliver, you may want to take a look at this map that’s about to appear in the office store (supposedly): https://www.youtube.com/watch?v=qaq7Ya9BjCo

The flight tracking example I believe reflects what you wish for, and I believe it has the option to embed a Mapbox Style, though the video doesn’t talk about it I think there’s a field for it. 

Finally, for time based visualizations, I use this visual, and graph the aggregated speed for GPS telemetry data of security patrols on the bars, and the coordinate points on a Map Visual: https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380798?tab=Overview . It doesn’t have “play” functionality of the ArcGIS Premium Map, but you could use this with Mapbox and adjust time segments with the lateral sliders. 

Hope this helps.

**Comment by ryanbaumann** [comment]
This thread is awesome ;)  tons were planning to hook into Power BI, and y'all are helping to shape the roadmap!

Here's an example of of one type of timeseries visual with a choropleth looks like.  For Power BI it would work much in the same way, just as a native feature.

The timeseries map dashboard example: https://www.mapbox.com/labs/busintel/

How to build it: https://www.mapbox.com/live/building-custom-business-intelligence-tools-with-mapbox/

**Comment by otravers** [comment]
@PedroRiveraTorresMoir I'm aware of the Altius custom chart and looking forward to the addition of their visual to the marketplace (it looks like they hit a technical snag). I'm using the Time Brush too. There's also a drilldown player that I guess could work with a date series, but it's been taken off the store soon after its publication for some reason, though I could always compile it from source:
https://github.com/Microsoft/powerbi-visuals-drilldown-player

@ryanbaumann good example, there is indeed so much to do by cross-referencing time and space! I see you also have a time map, which reminds me of the driving distance capability in ArcGIS:
https://www.mapbox.com/labs/timemap/search/

It's exciting that these more complex data visualizations are becoming possible with off-the-shelf tools mostly using drag and drop, as opposed to having to write complex, custom-made D3/R code. It's too much effort for too little benefit for typical BI uses, not everyone is the NYT with D3 founding coders on payroll. And as a BI guy, it's already enough work perfecting my DAX proficiency, knowing some M, the occasional SQL query... stop the madness!

Years ago I thought Google would make it happen with Fusion Tables / Google Charts / Google Maps / Needlebase / Open Refine, but somewhere along the way they seem to have lost interest (like happens with half of their projects it seems). Maps in Google Data Studio look like something from 8 years ago. We need platforms with sustained momentum so that we don't have to change toolsets every 6 months to benefit from the latest tech developments.

**Comment by ryanbaumann** [comment]
@otravers spot on comment re: taking advantage of the latest tools inside of BI instead of writing and learning another new custom code framework.

> I see you also have a time map, which reminds me of the driving distance capability in ArcGIS:

Time map is incredible - check out another great example from Peter with isochrones (also something we could drop into Power BI) - https://blog.mapbox.com/add-isochrones-to-your-next-application-e9e84a62345f

**Comment by PedroRiveraTorresMoir** [comment]
Hi @ryanbaumann . Incredible advances with the Power BI visual!

I was wondering if the following items were still on the roadmap for the visual and if you happen to have a rough estimate for when they might be available: 

Multi-Hexbin aggregated/clustered selection on client data-joined points
3D for building Data Joins
3D building selection to display client data-joined rows where the ID of the 3D selected building appears
Linestring Data Joins

Thanks for any info you might have and congratulations again on the progress.

**Comment by ryanbaumann** [comment]
Thanks, @PedroRiveraTorresMoir!  

We're still gathering info on what's coming next after Native Power BI Tooltips and Choropleths.  Which one of your requests above is most important?  Linestrings and 3D extrusions should be relatively straightforward from a technical perspective after the Choropleth layer is complete.

**Comment by PedroRiveraTorresMoir** [comment]
Linestrings, definitely -- pulled from styles in Mapbox Studio, with two scenarios:

1. Have the legend/color be determined by a client-side field value
2. Enable selection of the linestring from within the map, so that a filter applies to the client-side data showing only the records associated with such linestring ID.

This would be very useful, and no other mapping tool that I know of does this in PowerBI or the other BI tools I know of. 

Imagine the potential of selecting roads, pipes, networks, routes, cables or other line segments and have contextual data for each “chunk”. In addition, when tied to PostGIS, we could have side-by-side views of the Mapbox GIS-aware representation of a network, while also having a graph network chart that displays relationships (the lines) between the nodes.

Thanks for evaluating this feature. As you can tell, I believe many people would find this useful.

**Comment by ryanbaumann** [comment]
Ticketed the linestring viz in a new issue @PedroRiveraTorresMoir  - https://github.com/mapbox/mapboxgl-powerbi/issues/92

**Comment by PedroRiveraTorresMoir** [comment]
Just curious @ryanbaumann . Is the option to add ArcGIS Online Tile Layers available as an option for choropleth viz? I published a Tile Layer from ArcGIS Online, and selected the "available offline" and "build tiles" option but it's not pulling in the polygons. Thanks for any orientation regarding this.

**Comment by ryanbaumann** [comment]
@pedroriveratorresmoir no, ArcGIS Online Tile Layers are not supported in the Mapbox Visual for Power BI.  However, you can upload your source shapefile or geojson file to your Mapbox account and use them in Power BI.  https://www.mapbox.com/help/power-bi-choropleth-map/

**Comment by PedroRiveraTorresMoir** [comment]
That’ll work, thanks.

________________________________
