### ISSUE TITLE
Add Fill-Extrusion layer type and a `Depth` property (Hexbins)

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#70]
It would be great to have an optional data-driven _Depth_ field that's mapped to _fill-extrusion_ in custom Mapbox tilesets.

![image](https://user-images.githubusercontent.com/3731532/36641494-f6436d64-1a0e-11e8-8911-53d8a175a90c.png)

The primary use I see for this is to elevate/depress whole areas (defined by their boundaries) based on a value, like a choropleth uses color. Combined with the Color parameter (i.e. _fill-color_), this would in effect let us create 4D maps (where color and depth reflect different measures). See for example:
- https://codepen.io/ro-ka/pen/ENoOjz (country boundaries)
- http://www.arcgis.com/apps/CEWebViewer/viewer.html?3dWebScene=f034d08dbde649fe97ed2f3ec5bbf381 (US counties)
- http://bl.ocks.org/hopelessoptimism/e5e3bd6effd7fc1874ff (buildings)

You'd for instance use height for a value, and color for the YoY variation rate of that value, similarly to how you can use Color Saturation is some of Power BI's native chart types.

A secondary use would be the 3D display of columns of various height, superimposed on the map like here with hexbins:
https://www.mapbox.com/bites/00304/

(This is a follow up to https://github.com/mapbox/mapboxgl-powerbi/issues/68#issuecomment-368277356)

Related reading:
- http://datavizcatalogue.com/blog/further_exploration_3_3d_maps/
- https://andrewpwheeler.wordpress.com/2012/01/29/example-good-and-bad-uses-of-3d-choropleth-maps/

**Comment by PedroRiveraTorresMoir** [comment]
This would be useful for us as well, with the added ability to cluster points into the polygon’s depth or height field to determine their expressed value. So this feature would basically convert points with lat,long into polygon expression attributes without the need to reference the polygon directly. If the point falls on top of the polygon shape, it would automatically add to the polygon’s height / depth value.

Adding the automatic segmenting a region into hexagons to the previous feature would be an additional plus of course. 

Just ideas that could be useful for our use cases as well…

From: Olivier Travers
Sent: Sunday, February 25, 2018 7:01 AM
To: mapbox/mapboxgl-powerbi
Cc: Subscribed
Subject: [mapbox/mapboxgl-powerbi] Expose fill-extrusion as a Depth property(#70)

It would be great to have an optional data-driven Depth field that's mapped to fill-extrusion in custom Mapbox tilesets.

The primary use I see for this is to elevate/depress whole areas (defined by their boundaries) based on a value, like a choropleth uses color. Combined with the Color parameter (i.e. fill-color), this would in effect let us create 4D maps (where color and depth reflect different measures). See for example:
• https://codepen.io/ro-ka/pen/ENoOjz (country boundaries)
• http://www.arcgis.com/apps/CEWebViewer/viewer.html?3dWebScene=f034d08dbde649fe97ed2f3ec5bbf381 (US counties)
• http://bl.ocks.org/hopelessoptimism/e5e3bd6effd7fc1874ff (buildings)
You'd for instance use height for a value, and color for the YoY variation rate of that value, similarly to how you can use Color Saturation is some of Power BI's native chart types.
A secondary use would be the 3D display of columns of various height, superimposed on the map like here with hexbins:
https://www.mapbox.com/bites/00304/
(This is a follow up to #68 (comment))
Related reading:
• http://datavizcatalogue.com/blog/further_exploration_3_3d_maps/
• https://andrewpwheeler.wordpress.com/2012/01/29/example-good-and-bad-uses-of-3d-choropleth-maps/

**Comment by otravers** [comment]
If I'm not mistaken this eventually landed in issue https://github.com/mapbox/mapboxgl-powerbi/issues/188

**Comment by samgehret** [comment]
Closing this as its addressed in https://github.com/mapbox/mapboxgl-powerbi/issues/188
