### ISSUE TITLE
Surface up traffic data as a data series + provide historical values?

### ISSUE THREAD

**Issue by otravers** [mapbox/mapboxgl-powerbi#72]
Not sure Mapbox sees itself as a data provider, but since you have traffic data to put on your maps, maybe this could be delivered as a data feed for Power BI (and its ilk) to tap?

My understanding is that you're displaying real time congestion, with 4 levels of congestion value:
https://www.mapbox.com/vector-tiles/mapbox-traffic-v1/#overview

First, it would be valuable to have an ability to analyze/map that type of data over time to see trends through the day and week, as well as seasonality over the year. That would make much more sense in the context of a BI app, while real time data is more useful to a navigation app (which I'm guessing is the original use case for your traffic layer). TomTom markets something like this, possibly ESRI too.

Second, I'm not sure how the congestion values are computed, but actual vehicle count data over time would be valuable for purposes such as retail location analysis or urban planning.

**Comment by ryanbaumann** [comment]
Great feature request, @otravers.  

> My understanding is that you're displaying real time congestion, with 4 levels of congestion value:
https://www.mapbox.com/vector-tiles/mapbox-traffic-v1/#overview

Correct, real-time traffic values are served as vectors to the client in 4 levels of congestion buckets.  

It would be a feature request to be able to query congestion values compared to your data in Power BI - but very possible to do.

> First, it would be valuable to have an ability to analyze/map that type of data over time to see trends through the day and week, as well as seasonality over the year.

Historical traffic ETA functionality is on our roadmap.  Would the most useful reference be a visual representation of the traffic at a time of day, or access to specific trip ETAs at a time of day?  Check out some of [our blog posts](https://www.mapbox.com/narratives/big-game-2018-traffic/) for ideas.  cc @mtirwin 

> Second, I'm not sure how the congestion values are computed, but actual vehicle count data over time would be valuable for purposes such as retail location analysis or urban planning.

Agree re: utility for retail and urban planning.  Car counts aren't something that's on our near term roadmap, but you could add any traffic data and use it in a custom map style in Power BI by uploading it to your Mapbox account.

**Comment by otravers** [comment]
>Ability to query values from layers in a vector tileset in a map style, and compare the queried data to your visualization data in Power BI. This feature would work for traffic, and also for any other data layer you have in a Mapbox or Custom style used in Power BI

Oh, I see what you're saying, nice abstraction of my feature request! If I understand you correctly, Mapbox data layers would become a pass-through vehicle for data to flow from Mapbox Studio to PBI. But would it work through _Get Data_ so that we can apply Power Query ETL and DAX logic on top of that data?

>Would the most useful reference be a visual representation of the traffic at a time of day, or access to specific trip ETAs at a time of day

I guess both! I like your Minneapolis blog post, I would put something like this next to the map to cross-filter back and forth between the map and heatmap table/histograms:

![image](https://user-images.githubusercontent.com/3731532/36945139-3861df90-1f88-11e8-8ab2-a2fccfb2789f.png)

>you could add any traffic data and use it in a custom map style in Power BI by uploading it to your Mapbox account.

Riiiight, again you're making the data flow through Mapbox first, I have to wrap my head around that workflow as opposed to load everything directly in the PBI data model, which is my Pavlovian approach. In my head, Mapbox = styled tilesets, but then there's also:
https://www.mapbox.com/help/define-dataset/

For the record and for comparison purposes, ESRI has 2017 USA traffic count in their Living Atlas available in their PBI visual, based on Kalibrate's TrafficMetrix. However the user experience is poor, as far as I can see it's just a collection of tiny dots that you're supposed to hover over:
![image](https://user-images.githubusercontent.com/3731532/36945564-39f1cfc6-1f8f-11e8-8bb3-dc1e5b794050.png)

Looks like one of several examples where you only get a subset of the full-fledged ArcGIS experience in PBI, which is frustrating (underlying message: don't do this with your own PBI visual!). Here's the web version, which requires a separate subscription:
http://www.arcgis.com/home/item.html?id=07bf63e8238b44e7ba44cdcadcc5a8c2

There's a number of local governments that publish open traffic data, of course one always dreams of finding a global open data repository of everything...

**Comment by otravers** [comment]
Keeping this up to date for reference:

1. Mapbox live traffic coverage has been expanding to more countries (with [varying degrees](https://docs.mapbox.com/help/how-mapbox-works/directions/#traffic-data) of accuracy):
https://blog.mapbox.com/traffic-everywhere-5108cb81b403

2. Mapbox now has an enterprise data series for traffic with "Estimated speeds throughout the week based on historical observations.":
https://www.mapbox.com/traffic-data/
