### ISSUE TITLE
Add ability to geocode locations before plotting

### ISSUE THREAD

**Issue by VitalyMCT** [mapbox/mapboxgl-powerbi#73]
Following up from https://github.com/mapbox/mapboxgl-powerbi/issues/19

The current version of the visualization requires the dataset to have lat/long values. We would like to be able to supply other location types and have Mapbox geocode them before plotting.

This could work similarly to the ArcGIS Maps for Power BI visualization. That is, the visualization has 3 placeholders: Latitude, Longitude and Location:

![image](https://user-images.githubusercontent.com/1765732/36999138-3001cd1e-208d-11e8-8b43-1bc68f0dc5f7.png)

**Comment by ryanbaumann** [comment]
Great feature request.  Thanks, @vitaly-livshits - we'll evaluate this for our roadmap next.

One consideration here would be how we can allow you to store the results of a geocode directly in your Power BI data model.  That way you would be able to reference and group/aggregate your data by that geographic hierarchy (county, city, zip, etc), not just visualize a polygon on a map.

**Comment by sergeiGKS** [comment]
I have the same request! 

Thanks!
