### ISSUE TITLE
Enable map `pinning` and max auto-zoom level

### ISSUE THREAD

**Issue by indiciagerry** [mapbox/mapboxgl-powerbi#74]
I have a list of stores with lat long. 
When we navigate from one circle to another using a filter, the transition is cool but the zoom in is way too close. 

It will be nice to define the max zoom in to, in my case, stay at neighbourhood level.

**Comment by ryanbaumann** [comment]
@indiciagerry agree.  We should allow the user to:

1. Turn auto-zoom on data interaction on/off
2. Define the max auto-zoom a map can go to, with a reasonable default level (say zoom 16).

Would that suit your use case?

**Comment by indiciagerry** [comment]
@ryanbaumann Yes, it's exactly what i have in mind.

Thanks!

**Comment by ryanbaumann** [comment]
Lets break this into two parts:

1. Expose an HTML element `pin` icon to the map.  When the user toggles the button on or off, it will enable or disable auto-zoom.  This allows the end consumer to control the map pin state, not just the dashboard editor.
2. Set the max zoom level for an auto-zoom maneuver to 15.  Do not add another checkbox to the format panel, just set a global max zoom that the map.setBounds() auto manuver can zoom to.  This prevents the map from zooming way too far in when only a few close or one features are in the viz.

**Comment by Mike-Honey** [comment]
Where do we set the "global max zoom" ?

**Comment by ryanbaumann** [comment]
@mike-honey the max zoom level for the entire map isn't configurable in Power BI right now - if that's a use case you'd like to add a feature request for, please open a new ticket with a detailed description.
