### ISSUE TITLE
User-configurable categorical color palettes for circle and Choropleth layer types

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#78]
# Problem

Currently, if a user selects a `dimension` from their data and drops it into the `color` field, the color of the layer created will be defined using a static categorical color palette.  This color palette is not configurable.  

This is a valuable tool to have with categorical data, so you can select colors for specific types of categorical dimensions that you want to highlight as a specific color.

# Solution

Programmatically generate a color-selection dropdown in the viz format panel.  There should be one drop-down box available for each unique value in the user dataset (up to a limit to prevent the UI from getting slow - Maybe 100 or 1000 elements?)

The user would be able to select a color from the PowerBI Color Utils dropdown for each unique categorical value.

**Comment by ryanbaumann** [comment]
This is blocked by https://github.com/Microsoft/PowerBI-visuals/issues/330

**Comment by Mike-Honey** [comment]
I support this Solution - it's a very important scenario for several projects I'm working on - color Choropleth areas due to a specific palette (known to users).

I dont understand the technical detail of the block, but is a possible workaround to allow the user to specify a string field from the dataset that contains the required colors e.g. "FD6666" ?  

While that wouldn't be the standard Power BI method, it has some advantages - e.g. consistency across tiles.

**Comment by ryanbaumann** [comment]
Good news @mike-honey, we're working on this during our next sprint.  We'll provide updates on the ticket.

**Comment by ryanbaumann** [comment]
This is complete in https://github.com/mapbox/mapboxgl-powerbi/pull/163 cc/ @Mike-Honey

**Comment by Mike-Honey** [comment]
I've applied the #163 build and can see some other new Format properties e.g. Level. But I can't see anything new to control categorical colors.  Should that appear under Choropleth:?  I'm seeing the previous numeric scale color controls, e.g.

![image](https://user-images.githubusercontent.com/9509644/41276407-7c5c0bde-6e67-11e8-9d08-2e61b4495d66.png)

I tried dragging a text field onto the Color well, figuring that might change the Format options, but instead I get this error:

![image](https://user-images.githubusercontent.com/9509644/41276471-aa1ef1c6-6e67-11e8-8dff-cd3aabf748dd.png)

I'm a bit stuck - any tips appreciated.

**Comment by szilardhuber** [comment]
@Mike-Honey you should be able to set the categorical colors under the Data Colors preferences group like in this video:

![Categorical colors](https://camo.githubusercontent.com/aec805b2b57c4f94388dac227e949f21f9dff855/68747470733a2f2f636c2e6c792f3435336633303338335631712f646f776e6c6f61642f53637265656e2532305265636f7264696e67253230323031382d30362d3039253230617425323031302e3532253230414d2e676966)

These settings are only available if you are not using a measure for the color field. For coloring based on measures the Min/Med/Max colors are used.

**Comment by Mike-Honey** [comment]
Thanks for the speedy reply. That's exactly what I want to achieve. 

But when I drag a text field onto the Color well I get the error I showed above - "Couldnt load the data ...".

**Comment by ryanbaumann** [comment]
@mike-honey could you link you sample workbook file producing the issue on this ticket (as a .zip) to help us recreate?  Thank you!

**Comment by Mike-Honey** [comment]
Sorry for the red herring - I have been unable to repo this issue, and after I removed and re-added a tooltip field my original scenario is working fine too.
