### ISSUE TITLE
Choropleth / Fill Map layer - master ticket

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#80]
This ticket captures the entire scope of `Choropleth` layer support in the Mapbox Visual for Power BI.  cc @szilardhuber @petispaespea @endre-jenei @baspeti 

# Features
- [x] Support polygon shape data from a Vector Tile source as a `mapbox://` URL.
    * Should work seamlessly with user-created [Mapobox Tilesets](https://www.mapbox.com/help/studio-manual-tilesets/).  
    * Mapbox tilesets support drag-and-drop conversions to Vector Tiles from Shapefile, KML, and Geojson data formats.  
- [x] The user interface for selecting a Vector-Tile source layer and Property Name should auto-populate the available fields in a dropdown list.  
    * The default value should be the first available layer name and property value in the drop-down.
    * A user should not have to copy more than the Map ID of a tileset from their Mapbox Tileset URL and paste it into the Vector Tile URL in Mapbox.
    * ![](https://cl.ly/1i0x31120P3L/download/[c4d9e18330d276ec7820bcd0f16a63b8]_Image%202018-03-17%20at%2011.23.03%20AM.png)
    * To get the list for the drop-down, request the tileJSON for the tileset using the Maps API ([exmaple URL here](https://api.mapbox.com/v4/mapbox.mapbox-streets-v7.json?secure&access_token=pk.eyJ1IjoicnNiYXVtYW5uIiwiYSI6IjdiOWEzZGIyMGNkOGY3NWQ4ZTBhN2Y5ZGU2Mzg2NDY2In0.jycgv7qwF8MMIWt4cT0RaQ)) and parse out the list of values for properties and vector layernames.
    * ![](https://cl.ly/3Y1t081m3U3H/download/[86a8de6320c6fbfd7890fe899c95c72f]_Image%202018-03-17%20at%2011.11.59%20AM.png)
- [x] The Choropleth layer should support the following style options in the `Format` panel:
    * A min, med, and max fill-color value selector (or continuous color palette, when available in Power BI custom visuals) for a `measure` data color value
        * Color values for continuous palettes should default to `quantile` domain stops for color value calculations.
    * A categorical fill-color value selector for a `grouping/dimension` data color value (see the circle viz for implementation)
    * A min and max zoom (between 0 and 22) slider for layer visibility
    * A fill-opacity slider
    * An outline color dropdown, outline-width counter, and outline-opacity input selector.
        * This outline style should be rendered as a `line` layer placed one layer above the `fill` layer.  Do not use a `fill` layer with `fill-outline-color`, for maximum flexibility
- [x] The Choropleth layer should support tooltips.
    * Tooltip values should update on mouse-move using the `debounce` function.
    * Tooltip values should display all values from the location, color, and tooltip fields used int he Power BI viz
    * The tooltip values should map from the data in Power BI to the `property` match in the vector tiles (such as postcode, or country) using a [Map lookup data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object, with the Map key being the unique property value to join between Power BI and the Vector Tile source.
- [ ] The Choropleth layer should support rendering multiple layers in the same map.
    * The current [beta](https://github.com/mapbox/mapboxgl-powerbi/pull/76) restricts the Choropleth to be the only viz type used if it is selected.  This is because of concerns around grouping and aggregation when a user includes a highly grouped dimension (location) and a unique dimension per data value (longitude/latitude) in the same data response from the Power BI data api.
    * The Choropleth layer should properly display the data in Power BI grouped and aggregated by only the data in the `location` field, not the data in the longitude/latitude fields.
    * The Choropleth layer should render by default as the lowest visual layer order in the visual layer stack (below clusters, heatmaps, and circles).
- [x] The Choropleth layer should present the user with an errors
    * Error with suggested actions to fix if a `location` dimension is not used in the viz data fields.
- [ ] The layer should have tests validating that layer works with
    * Multiple layers
    * A sample tileset and data set
- [x] Start work from the branch [beta 1.1.0](https://github.com/mapbox/mapboxgl-powerbi/pull/76)

**Comment by szilardhuber** [comment]
@ryanbaumann regarding this 

![auto-populated dropdown](https://camo.githubusercontent.com/f69709e15ae1e2b9b1e66e66b8152ca4e040b59b/68747470733a2f2f636c2e6c792f335931743038316d335533482f646f776e6c6f61642f25354238366138646536333230633666626664373839306665383939633935633732662535445f496d616765253230323031382d30332d3137253230617425323031312e31312e3539253230414d2e706e67)

I have tried to populate dropdowns programmatically but turned out that it is not yet supported. The open ticket for that: https://github.com/Microsoft/PowerBI-visuals/issues/285

**Comment by ryanbaumann** [comment]
Thanks, @szilardhuber - I pinged on that ticket checking if there was any progress.  Let me know if you have any ideas on how to make selecting the `source layer` and `vector property` a better user experience.  I'm thinking we could probably just auto-select the first vector layer in the tileset without a drop-down (99% of tilesets will only use one layer), but I don't think there's a good way to get the `vector property` without some sort of UI showing the list-of-values.

**Comment by ryanbaumann** [comment]
@szilardhuber thinking through this more, how is this for a proposal, since dynamic dropdowns are not supported in Power BI:

* Add a new drop-down named `Data` as the top-level item in the `choropleth` layer.  This drop-down includes 4 default datasets for the user to choose from, plus a `custom` option.
    * Global countries
    * USA States
    * USA Counties
    * USA Postcodes (5-digit)
        * Mapbox to provide URL's, Source Layers, and Vector Property values to the sources above ^^ from US Census and Natural Earth.  The user would not need to take care of it themselves.
    * Custom...
* When a user selects `custom`, they will see the current top 3 options we have displayed in the `Choropleth` layer.  The user will have to copy/paste the values from their Mapbox Account to use a custom polygon layer, just like the custom style.
    * Vector Tile URL
    * Source Layer
    * Vector Property

**Comment by szilardhuber** [comment]
@ryanbaumann I was thinking about adding some minimal html-based GUI for the dynamic dropdown when in edit mode (I'm not 100% sure we can know if we are in edit mode but I think we can). What about we try both versions and decide which to use when we see them?

**Comment by ryanbaumann** [comment]
I moved the documentation section out of this master ticket to a new issue - that is out of scope for this issue. -> https://github.com/mapbox/mapboxgl-powerbi/issues/82

@szilardhuber 
> I'm not 100% sure we can know if we are in edit mode but I think we can

Yes, you can check `options.viewMode` to see if the workbook is in edit mode.  See this PR for an example -> https://github.com/mapbox/mapboxgl-powerbi/pull/66/commits/ab413b5348d5ae34281ac90de919e480d903142e

>  I was thinking about adding some minimal html-based GUI for the dynamic dropdown when in edit mode ... What about we try both versions and decide which to use when we see them?

Where would this GUI live @szilardhuber - on top of the map div element as an HTML component?  I'd like to avoid putting some data format items in the format pannel and some in the map HTML container.  My hunch is that it would confuse users.  

If dynamic dropdowns aren't supported, I'd propose we scope that out for now and just use static dropdowns with a `custom` option as specified above.  Thoughts?

**Comment by vitaly-livshits** [comment]
We've been exploring the choropleth in the latest beta and it's working great. Excellent work!

Are there plans to allow selection of polygons within the map? This would allow the user to cross-filter from Mapbox to other visualizations. It's very useful for data analysis, especially if multi-select is allowed.

**Comment by Mike-Honey** [comment]
I'm a bit confused trying to use the Choropleth feature at all. Is there any info on how to set up the PBI side? What to put in the properties under Choropleth? How to match the "Vector Property" to a "key" field in our PBI dataset?

@vitaly-livshits can you share any info?

Also I read in issue #68 that this is an Enterprise-only feature - is that still the case?

**Comment by ryanbaumann** [comment]
@mike-honey hi!  

This ticket discusses the feature requirements for the Choropleth layer currently in development.  It is not available in the current version of the Mapbox Visual on the Office Store. 

The Choropleth layer will be available to use in the free version of an upcoming release on the office store.

**Comment by petispaespea** [comment]
@ryanbaumann Following the documentation I was not able to create a Slider UI control but Spinner. I opened an issue: https://github.com/Microsoft/PowerBI-visuals/issues/319.

**Comment by ryanbaumann** [comment]
As we aim to finish up this ticket, here are the items that remain open:

| feature 	| status 	| comment 	|
|-------------------------------------------------------------	|---------	|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| support polygons from vector tile sources 	| testing 	| Need to test and add docs pre-defined Mapbox tilesets (countries,states, zipcodes, counties)  	|
| auto-populate vector property and vector layername sources 	| blocked 	| Power BI custom visuals do not support dynamic dropdowns in the capabilities.json 	|
| Choropleth format options - categorical color selection 	| blocked 	| Categorical color selection in format pannel requires categorical dataViewModel - need to confirm change to this data view model. 	|
| Choropleth format options - outline-*, fill-opacity 	| closed 	|  	|
| Tooltips 	| testing 	| Need to find a better way to update tooltips during mousemove interactions with nearby polygons without degrading performance.   	|
| Render multiple layers in the same map including Choropleth 	| blocked 	| .  Tracking with Power BI, feature to enabled multiple dataViewMappings https://github.com/Microsoft/PowerBI-visuals/issues/251.  @szilardhuber would this be solved if we used the `categorical` dataViewMapping? 	|
