### ISSUE TITLE
Add support for WMS/WMTS

### ISSUE THREAD

**Issue by ce-goddard** [mapbox/mapboxgl-powerbi#81]
There is a measurable demand for WMS map layers support. [Users](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/13375065-add-wms-map-layers) want to be able to add WMS layers (and ideally other map services) to the maps in PowerBI. 

One user stated how "any potential solution would likely involve Leaflet or Mapbox with a WMS plugin like https://github.com/heigeo/leaflet.wms. There has been work in this area around custom visuals, but nothing has been released to the Gallery."

**Comment by ryanbaumann** [comment]
Thanks, @ce-goddard, this seems like a solid idea to hit for users coming from ArcGIS and Geoserver raster tile layers.

**Comment by ryanbaumann** [comment]
@ce-goddard prototype to work from here -> https://github.com/mapbox/mapboxgl-powerbi/pull/84

**Comment by ryanbaumann** [comment]
Removing from milesetone 1.1, moving to 1.2

**Comment by ryanbaumann** [comment]
cc/ @samgehret

**Comment by samgehret** [comment]
@ryanbaumann made PR for this feature to master.

**Comment by mzdraper** [comment]
@samgehret Per your comment in https://github.com/mapbox/mapboxgl-powerbi/pull/288#issuecomment-474109649, can this be closed?

**Comment by samgehret** [comment]
@mzdraper yep. closing this issue!
