### ISSUE TITLE
Documentation and Examples for Choropleth layer

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#82]
* Add workbook file example for Choropleth map to `/examples` folder in this repo
* Add documentation to www.mapbox.com/help/power-bi for Choropleth layers

**Comment by ryanbaumann** [comment]
Tracking documentation for the Choropleth layer at

https://github.com/mapbox/mapboxgl-powerbi/issues/142

**Comment by ryanbaumann** [comment]
@kalimar can you try creating the example for the Choropleth map in Power BI?  It should....

- [ ] Power BI Desktop file saved in the /examples folder of this repo
- [ ] Use a US Postcodes tilesset included with the Mapbox Visual for Power BI
- [ ] Use this dataset of [US Population by postcode](https://dl.dropbox.com/s/likl86i7sfc2n9q/2010_us_population_by_postcode.csv)

**Comment by ryanbaumann** [comment]
@kalimar can you drop your workbook example here?  We'll bundle this up as an example in the repo.

**Comment by kalimar** [comment]
Here's the example using existing Power BI shapes, https://app.powerbi.com/groups/me/reports/ebfef389-9425-43b2-98bc-68821852ed70?ctid=629a70b2-32b9-4126-951e-17604cf456ec

And here's an example using custom polygons: https://app.powerbi.com/groups/me/reports/e188e4eb-60ed-47d7-acc0-b026ce747bcd?ctid=629a70b2-32b9-4126-951e-17604cf456ec

**Comment by otravers** [comment]
@kalimar The two Power BI example links you posted don't load for me (HTTP ERROR 401), are they shared publicly?

**Comment by ryanbaumann** [comment]
@otravers - @samgehret is working on our Power BI integration now.  @samgehret could you publish a sample PBIX file to the /examples folder in the repo?  Your FCC visualization would be perfect.

**Comment by samgehret** [comment]
@otravers the FCC example is now in the examples folder.
