### ISSUE TITLE
Add option to add 3D buildings to a default Mapbox Style

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#90]
For Mapbox default styles, a common request is how to add 3D buildings.  We should enable this as a check-box in the format pannel if and only if the user has selected a compatible base map style for 3D buildings:

Everything except for the `Custom` and `Satellite` map style options should support this option.

**Comment by ryanbaumann** [comment]
Tracking in https://github.com/mapbox/mapboxgl-powerbi/pull/100

**Comment by ryanbaumann** [comment]
This is easier to do now with the latest Mapbox Studio changes.  Moving to Milestone 1.2

**Comment by visarn** [comment]
Hi Ryan

I was wondering if my map style on mapbox already has 3d building bby changing building height. I was wondering why it does not show up on power bi?

Thank you

**Comment by samgehret** [comment]
@ryanbaumann Should I move this into 1.3? Seems like a short time to turn this around.

**Comment by ryanbaumann** [comment]
yes @samgehret
