### ISSUE TITLE
Add `linestring` map layer

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#92]
Users want to be able to map `linestrings` in a similar way to choropleth/fill layers.

1. By passing a series of long/lat points, grouped by a dimension, and connected in an ordered fashion over another dimension.  (EX: Long/Lat grouped by `trip id` ordered by `timestamp`)
2. By uploading a custom shapefile / geojson file, and joining Power BI data to the geometry over a key (like an inner join).  This is the same functionality as the `choropleth` layer type.

# Proposal

Add a `linestring` layer type to the Mapbox Visual for Power BI that supports use cases 1. and 2. above.

Reference layer type from Mapboxgl-Jupyter - https://github.com/mapbox/mapboxgl-jupyter/issues/81

**Comment by PedroRiveraTorresMoir** [comment]
Hi @ryanbaumann , amazing work on the visual! I was wondering if this feature is still on the pipeline or currently went on the backlog. Knowing when or if this will be released would helps us plan the deployment of certain capabilities.

Thanks!

**Comment by ryanbaumann** [comment]
cc/ @samgehret to comment on priority here, @PedroRiveraTorresMoir.  Now that we have the Choropleth layer complete, a linestring layer using vector-tile sources created from shapefiles / geojson files is feasible to implement.

**Comment by PedroRiveraTorresMoir** [comment]
Hi @samanpwbb, any news on this this feature? Knowing if there's a roadmap or not for it helps us determine how to prioritize the mapping efforts inside our companies. 

Linestrings are often overlooked in Business Intelligence but they are almost as important for operational insights as polygons (think pipeline status for water and gas, road and pedestrian path traffic, and many many other applications . I believe many users would find them useful at a time where a lot of infrastructure companies don't yet understand the power of merging GIS, BIM and operations. I believe it could be a useful way to have Mapbox develop clients in those industries. Thanks for any info on this!

**Comment by samgehret** [comment]
@PedroRiveraTorresMoir It's currently scoped into our [next release](https://github.com/mapbox/mapboxgl-powerbi/projects/3) and we are evaluating the LOE currently.

**Comment by PedroRiveraTorresMoir** [comment]
Hi @samgehret . Great progress with V3, this visual will be very helpful! Is there an ETA you could share on when this feature may be released?

**Comment by pablodidi** [comment]
@ryanbaumann @samgehret any news on this feature? We found this extremely powerfull. Choropleth layer with linestrings from a shape file in BI. We are looking for this for governmental purposes.

**Comment by ryanbaumann** [comment]
This is currently on the backlog, though it's a good candidate for a PR!  We'd be happy to review it.  Cc @samgehret

**Comment by pablodidi** [comment]
We are really interested in the new Choropleth Linestring Layer. As it was said above, it will bring new possibilities such as managing linear projects like roads and highways with PowerBI.

**Comment by PedroRiveraTorresMoir** [comment]
hi @ryanbaumann , hope everything is going well. Is there an estimated release date on this feature that you could share or is it in the backlog? We are about to choose the BI solution for our organizations and line-string visuals are critical. Thanks

**Comment by ryanbaumann** [comment]
@PedroRiveraTorresMoir we're starting to scope our next version features for v1.5, and this is a feature we're considering - https://github.com/mapbox/mapboxgl-powerbi/projects/5 cc/ @samgehret

**Comment by PedroRiveraTorresMoir** [comment]
Sweet, that'd be super useful. Thanks for considering it @ryanbaumann

**Comment by pablodidi** [comment]
hi @samgehret @ryanbaumann, it is very sad to notice that this feature is not any more in To do list in 1.5. We were really needing a linestring visual. Is there a possibility to include this feature again?

**Comment by PedroRiveraTorresMoir** [comment]
Unfortunately, having this postponed for a fourth time will have us using a different mapping solution for our city in the coming deployment. Hopefully it will be deployed later down the road so we can reevaluate Mapbox as a solution for our GIS needs.

**Comment by indiciagerry** [comment]
@ryanbaumann 
Please add this to 1.6...

**Comment by ryanbaumann** [comment]
@indiciagerry adding to list of feature to track for 1.7 - 1.6 will be focused on refactoring to the new PBI Visuals API versions and JS Bundles to fix a number of existing bugs.

**Comment by magmagreza** [comment]
@ryanbaumann, is this issue still on the to do list for 1.7? A lot of people need this capability! Thanks.
