### ISSUE TITLE
Document that Mapbox Visual for Power BI supports Publish to Web

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#94]
Other custom visualizations do not support Publish to Web - but the Mapbox Visual does.  We should add explicit docs that call this out in the Project Readme and Tutorial.

**Comment by vitaly-livshits** [comment]
On a related note, does MapBox fully support the Power BI Report Server? Are there any differences in the level of functionality provided by MapBox on Power BI Service vs. Power BI Report Server?

**Comment by vitaly-livshits** [comment]
@ryanbaumann, can you please advise on the above? We are investigating a possible on-prem reporting architecture with PBI and this would help us plan accordingly.

**Comment by ryanbaumann** [comment]
@vitaly-livshits yes, Mapbox supports all aspects of Power BI Report Server (March 2018 Edition) that I've tested so far.  I can't certify that 100% of the functionality is there, but based on my test, so far there's nothing missing.  If there is missing functionality you find, please open an issue and we'll work with you to address it ASAP.

![example-powerbi-reportserver](https://user-images.githubusercontent.com/4342845/40626816-f32831c4-626f-11e8-9e29-c0bb013cd7bc.png)

**Comment by VBADekker** [comment]
Hi, 
I don't know if I should post this here but I'm new to both Mapbox and Github.
I've made a chloropleth map with the Mapbox visual however, when I want to publish it to web (my own workspace) it draws a blank.
![mapbox publish to web probleem](https://user-images.githubusercontent.com/37701501/41472605-4200cce8-70b7-11e8-9371-68a21aff2ae0.PNG)
Any idea what I might have done wrong?

**Comment by ryanbaumann** [comment]
Closing in favor of https://github.com/mapbox/mapboxgl-powerbi/issues/201
