### ISSUE TITLE
Support Drill-down for Choropleth layers

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-powerbi#95]
## Feature

Add drilldown support for Choropleth map layers as per https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Drilldown.md.

### To Do

- [x] Swap dataView to use the `Categorical` dataView model in Power BI.  https://github.com/mapbox/mapboxgl-powerbi/issues/125
- [x] Add new fields to `capabilities.json` to accept user-input for multiple vector layers, one per each level of hierarchy the user specifies.  Ideally we would not put a maximum number of hierarchies allowed, but in practice, 3 levels of hierarchy is a minimum requirement.
- [x] Setup drilldown support to the layer as per https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Drilldown.md when a user right-clicks on a feature in the map.
- [x] When a user specifies a geo-hierarchy in the `location` data panel by adding more than one data item, the map will group/aggregate by the current drill level (state, county, etc.).  
    * For each level, the map will perform a data-join to the matching hierarchy level vector tile specified in the Format pannel.

This will work conceptually just like the drill down choropleth map custom visual https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381044?tab=Overview

Conceptual example - the Power BI implementation will only support Polygon/Choropleth layers:  https://www.mapbox.com/labs/vt-polygons/tile-query/

![](https://cl.ly/3i0r213M2U2r/download/Screen%20recording%202018-04-10%20at%2007.21.16%20AM.gif)

**Comment by samgehret** [comment]
Tested using drilldown branch, looks to be working. 
![drilldownpowerbi](https://user-images.githubusercontent.com/3859246/41061562-d74379d6-6987-11e8-83dd-d9a0c60615a9.gif)

**Comment by ryanbaumann** [comment]
This is complete in https://github.com/mapbox/mapboxgl-powerbi/pull/163

**Comment by Mike-Honey** [comment]
I got this feature working with 2 levels - both Custom Tilesets. Thanks so much for all the hard work to get this going.

But when I drill from Level 1 to Level 2, the filtered set of polygons are shown, but it doesnt autozoom in to them (like in the gif above) ?

Level 1 - all polygons (correctly auto-zoomed):
![image](https://user-images.githubusercontent.com/9509644/41287715-f7c75d72-6e86-11e8-93dd-d297c7db7c3d.png)

After Drill Down on bottom-right red polygon: 
![image](https://user-images.githubusercontent.com/9509644/41287771-2555963c-6e87-11e8-96da-1ce3026e7e39.png)

**Comment by ryanbaumann** [comment]
@mike-honey thanks, pumped it works well!  Auto-zoom to a subset of vector tile features is not currently supported - we're tracking that feature request here. https://github.com/mapbox/mapboxgl-powerbi/issues/133   Cc @samgehret
